### ISSUE TITLE
[systemd] lightdm autologin fails somehow

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#103]
This is really strange. Yesterday I did a dev-build with **manjaro-tools-git (r1276.120bfcb-1)**. However, todays build with latest manjaro-tools-git lightdm doesn't autologin anymore. I tried to fix it in devel branch, but still no working solution ...

**Comment by Kirek** [comment]
https://github.com/manjaro/manjaro-tools/commit/cfba31048292e3f444a7ee3109510ddaf4335f62#diff-32a62f488a1357cc18e5ec5be510c002
Changed there.
autologin var is never set here because this is called from the livecd script.
In fact autologin should be setup in the installer and selected by the user, not in buildiso...

**Comment by philmmanjaro** [comment]
Well, I tested also **manjaro-tools 0.9.8** which failed me also. I checked all lightdm.conf files. Here is the working log output of yesterdays build:
<pre>[manjaro@manjaro Desktop]$ sudo cat /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.14.0, UID=0 PID=1019
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Registered seat module xlocal
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.02s] DEBUG: Loading properties from config section SeatDefaults
[+0.02s] DEBUG: Seat seat0: Starting
[+0.02s] DEBUG: Seat seat0: Creating user session
[+0.08s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.08s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.10s] DEBUG: Seat seat0: Creating display server of type x
[+0.12s] DEBUG: Quitting Plymouth
[+0.15s] DEBUG: Using VT 7
[+0.15s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.15s] DEBUG: DisplayServer x-0: Logging to /var/log/lightdm/x-0.log
[+0.15s] DEBUG: DisplayServer x-0: Writing X server authority to /run/lightdm/root/:0
[+0.15s] DEBUG: DisplayServer x-0: Launching X Server
[+0.15s] DEBUG: Launching process 1032: /usr/sbin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.16s] DEBUG: DisplayServer x-0: Waiting for ready signal from X server :0
[+0.17s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.17s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+2.54s] DEBUG: Got signal 10 from process 1032
[+2.54s] DEBUG: DisplayServer x-0: Got signal from X server :0
[+2.54s] DEBUG: DisplayServer x-0: Connecting to XServer :0
[+2.55s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+2.55s] DEBUG: Session pid=1105: Started with service 'lightdm-autologin', username 'manjaro'
[+2.69s] DEBUG: Session pid=1105: Authentication complete with return value 0: Success
[+2.69s] DEBUG: Seat seat0: Session authenticated, running command
[+2.69s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+2.70s] DEBUG: Session pid=1105: Running command /etc/lightdm/Xsession startxfce4
[+2.70s] DEBUG: Creating shared data directory /var/lib/lightdm-data/manjaro
[+2.70s] DEBUG: Session pid=1105: Logging to .xsession-errors
[+2.88s] DEBUG: Activating VT 7
[+2.88s] DEBUG: Activating login1 session c1
[+2.88s] DEBUG: Seat seat0 changes active session to c1
[+2.88s] DEBUG: Session c1 is already active
</pre>

**Comment by philmmanjaro** [comment]
And this is what I get now:
<pre>[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.14.0, UID=0 PID=964
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.00s] DEBUG: Registered seat module xlocal
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.02s] DEBUG: Monitoring logind for seats
[+0.02s] DEBUG: New seat added from logind: seat0
[+0.02s] DEBUG: Loading properties from config section SeatDefaults
[+0.02s] DEBUG: Seat seat0: Starting
[+0.02s] DEBUG: Seat seat0: Creating user session
[+0.09s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.09s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.10s] DEBUG: Seat seat0: Failed to find session configuration none
[+0.10s] DEBUG: Seat seat0: Can't find session 'none'
[+0.10s] DEBUG: Seat seat0: Creating greeter session
[+0.13s] DEBUG: Seat seat0: Creating display server of type x
[+0.14s] DEBUG: Quitting Plymouth
[+0.18s] DEBUG: Using VT 7
[+0.18s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.18s] DEBUG: DisplayServer x-0: Logging to /var/log/lightdm/x-0.log
[+0.18s] DEBUG: DisplayServer x-0: Writing X server authority to /run/lightdm/root/:0
[+0.18s] DEBUG: DisplayServer x-0: Launching X Server
[+0.18s] DEBUG: Launching process 976: /usr/sbin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.18s] DEBUG: DisplayServer x-0: Waiting for ready signal from X server :0
[+0.18s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.18s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+2.70s] DEBUG: Got signal 10 from process 976
[+2.70s] DEBUG: DisplayServer x-0: Got signal from X server :0
[+2.70s] DEBUG: DisplayServer x-0: Connecting to XServer :0
[+2.71s] DEBUG: Seat seat0: Display server ready, starting session authentication
[+2.71s] DEBUG: Session pid=1049: Started with service 'lightdm-greeter', username 'lightdm'
[+2.78s] DEBUG: Session pid=1049: Authentication complete with return value 0: Success
[+2.78s] DEBUG: Seat seat0: Session authenticated, running command
[+2.78s] DEBUG: Session pid=1049: Running command /usr/sbin/lightdm-gtk-greeter
[+2.78s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm
[+2.78s] DEBUG: Session pid=1049: Logging to /var/log/lightdm/x-0-greeter.log
[+2.96s] DEBUG: Activating VT 7
[+2.96s] DEBUG: Activating login1 session c1
[+2.96s] DEBUG: Seat seat0 changes active session to c1
[+2.96s] DEBUG: Session c1 is already active
[+3.64s] DEBUG: Session pid=1049: Greeter connected version=1.14.0 resettable=false
[+4.66s] DEBUG: Session pid=1049: Greeter start authentication for manjaro
[+4.66s] DEBUG: Session pid=1073: Started with service 'lightdm', username 'manjaro'
[+4.76s] DEBUG: Session pid=1073: Got 1 message(s) from PAM
[+4.76s] DEBUG: Session pid=1049: Prompt greeter with 1 message(s)
[+14.22s] DEBUG: Seat seat0 changes active session to 
[+19.25s] DEBUG: Seat seat0 changes active session to c2</pre>

... I had to login manually:
<pre>[+52.21s] DEBUG: Seat seat0 changes active session to c1
[+52.21s] DEBUG: Session c1 is already active
[+56.32s] DEBUG: Session pid=1049: Continue authentication
[+56.34s] DEBUG: Session pid=1073: Authentication complete with return value 0: Success
[+56.35s] DEBUG: Session pid=1049: Authenticate result for user manjaro: Success
[+56.35s] DEBUG: Session pid=1049: User manjaro authorized
[+56.35s] DEBUG: Session pid=1049: Greeter sets language en_US.utf8
[+56.46s] DEBUG: Writing /home/manjaro/.dmrc
[+56.47s] DEBUG: Session pid=1049: Greeter requests session xfce
[+56.47s] DEBUG: Writing /home/manjaro/.dmrc
[+56.47s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session
[+56.47s] DEBUG: Session pid=1049: Sending SIGTERM
[+56.60s] DEBUG: Session pid=1049: Greeter closed communication channel
[+56.60s] DEBUG: Session pid=1049: Exited with return value 0
[+56.60s] DEBUG: Seat seat0: Session stopped
[+56.60s] DEBUG: Seat seat0: Greeter stopped, running session
[+56.60s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0
[+56.60s] DEBUG: Session pid=1073: Running command /etc/lightdm/Xsession startxfce4
[+56.60s] DEBUG: Creating shared data directory /var/lib/lightdm-data/manjaro
[+56.60s] DEBUG: Session pid=1073: Logging to .xsession-errors
[+56.69s] DEBUG: Activating VT 7
[+56.69s] DEBUG: Activating login1 session c3
[+56.69s] DEBUG: Seat seat0 changes active session to c3
[+56.69s] DEBUG: Session c3 is already active
</pre>

**Comment by Kirek** [comment]
https://github.com/manjaro/manjaro-tools/commit/3fb92f36d3b640493ec0adb2ade1d939002ba651#diff-7ef5e7eef393988280dcaf9a2e382cf7

**Comment by Kirek** [comment]
Simply its not setup, its protected by the "autologin" var, in the livecd this is empty, also we call this function specifically to setup autologin, doesn't need to be protected by a var.

**Comment by udeved** [comment]
We need to write the autologin var to the profile.conf which is copied to livecd.
I confused it, and statically set it up in wrong file.

**Comment by Kirek** [comment]
But why? Why the livecd user shouldn't autologin? It's a needed feature someone asked for it?

**Comment by udeved** [comment]
Huh?
We set up autologin var same as custom var.
autologin var was empty/unused, because it was configure in wrong conf file.
This way, you can simply switch autologin on or off.
I just forgot to write the autologin value also to profile.conf on iso, so it gets loaded.

**Comment by udeved** [comment]
@philmmanjaro 

Did you add the autologin var to profile.conf?
The confusion is overcome.

**Comment by philmmanjaro** [comment]
Please check the lightdm log I posted. It doesn't matter if I use manjaro 0.9.8 or the latest git snapshot. Autologin fails. However the packages are the same. So this is weird. This is my profile:
<pre>##########################################
###### use this file in the profile ######
##########################################

# possible values: openrc,systemd
initsys="systemd"

displaymanager="lightdm"

################ install ################

# unset defaults to given value
# kernel="linux318"
kernel="linux40"

# unset defaults to given value
# efi_boot_loader="grub"

# set uefi partition size
# efi_part_size=31M

# unset defaults to given value
# plymouth_theme=manjaro-elegant

# unset defaults to given values
# names must match systemd service names
# start_systemd=('bluetooth' 'cronie' 'ModemManager' 'NetworkManager' 'org.cups.cupsd' 'tlp' 'tlp-sleep')

# unset defaults to given values,
# names must match openrc service names
# start_openrc=('acpid' 'bluetooth' 'consolekit' 'cronie' 'cupsd' 'dbus' 'syslog-ng' 'NetworkManager')

################# livecd #################

# unset defaults to given value
# hostname="manjaro"

# unset defaults to given value
# username="manjaro"

# unset defaults to given value
# password="manjaro"

# unset defaults to given values
# addgroups="video,audio,power,disk,storage,optical,network,lp,scanner,wheel"

# unset defaults to given values
# names must match systemd service names
# services in start_systemd array don't need to be listed here
# start_systemd_live=('livecd' 'mhwd-live' 'pacman-init' 'pacman-boot')

# unset defaults to given values,
# names must match openrc service names
# services in start_openrc array don't need to be listed here
# start_openrc_live=('livecd' 'mhwd-live' 'pacman-init' 'pacman-boot')</pre>

**Comment by Kirek** [comment]
The contents of /etc/lightdm/lightdm.conf in the livecd would be more helpfull, as we can see what's modified.

**Comment by philmmanjaro** [comment]
Here we go:
<pre>[manjaro@manjaro Desktop]$ sudo cat /etc/lightdm/lightdm.conf
#
# General configuration
#
# start-default-seat = True to always start one seat if none are defined in the configuration
# greeter-user = User to run greeter as
# minimum-display-number = Minimum display number to use for X servers
# minimum-vt = First VT to run displays on
# lock-memory = True to prevent memory from being paged to disk
# user-authority-in-system-dir = True if session authority should be in the system location
# guest-account-script = Script to be run to setup guest account
# logind-check-graphical = True to on start seats that are marked as graphical by logind
# log-directory = Directory to log information to
# run-directory = Directory to put running state in
# cache-directory = Directory to cache to
# sessions-directory = Directory to find sessions
# remote-sessions-directory = Directory to find remote sessions
# greeters-directory = Directory to find greeters
#
[LightDM]
#start-default-seat=true
#greeter-user=lightdm
#minimum-display-number=0
#minimum-vt=7
#lock-memory=true
#user-authority-in-system-dir=false
#guest-account-script=guest-account
#logind-check-graphical=false
#log-directory=/var/log/lightdm
run-directory=/run/lightdm
#cache-directory=/var/cache/lightdm
#sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions
#remote-sessions-directory=/usr/share/lightdm/remote-sessions
#greeters-directory=/usr/share/lightdm/greeters:/usr/share/xgreeters

#
# Seat defaults
#
# type = Seat type (xlocal, xremote)
# pam-service = PAM service to use for login
# pam-autologin-service = PAM service to use for autologin
# pam-greeter-service = PAM service to use for greeters
# xserver-command = X server command to run (can also contain arguments e.g. X -special-option)
# xserver-layout = Layout to pass to X server
# xserver-config = Config file to pass to X server
# xserver-allow-tcp = True if TCP/IP connections are allowed to this X server
# xserver-share = True if the X server is shared for both greeter and session
# xserver-hostname = Hostname of X server (only for type=xremote)
# xserver-display-number = Display number of X server (only for type=xremote)
# xdmcp-manager = XDMCP manager to connect to (implies xserver-allow-tcp=true)
# xdmcp-port = XDMCP UDP/IP port to communicate on
# xdmcp-key = Authentication key to use for XDM-AUTHENTICATION-1 (stored in keys.conf)
# unity-compositor-command = Unity compositor command to run (can also contain arguments e.g. unity-system-compositor -special-option)
# unity-compositor-timeout = Number of seconds to wait for compositor to start
# greeter-session = Session to load for greeter
# greeter-hide-users = True to hide the user list
# greeter-allow-guest = True if the greeter should show a guest login option
# greeter-show-manual-login = True if the greeter should offer a manual login option
# greeter-show-remote-login = True if the greeter should offer a remote login option
# user-session = Session to load for users
# allow-user-switching = True if allowed to switch users
# allow-guest = True if guest login is allowed
# guest-session = Session to load for guests (overrides user-session)
# session-wrapper = Wrapper script to run session with
# greeter-wrapper = Wrapper script to run greeter with
# guest-wrapper = Wrapper script to run guest sessions with
# display-setup-script = Script to run when starting a greeter session (runs as root)
# display-stopped-script = Script to run after stopping the display server (runs as root)
# greeter-setup-script = Script to run when starting a greeter (runs as root)
# session-setup-script = Script to run when starting a user session (runs as root)
# session-cleanup-script = Script to run when quitting a user session (runs as root)
# autologin-guest = True to log in as guest by default
# autologin-user = User to log in with by default (overrides autologin-guest)
# autologin-user-timeout = Number of seconds to wait before loading default user
# autologin-session = Session to load for automatic login (overrides user-session)
# autologin-in-background = True if autologin session should not be immediately activated
# exit-on-failure = True if the daemon should exit if this seat fails
#
[SeatDefaults]
#type=xlocal
#pam-service=lightdm
pam-autologin-service=lightdm-autologin
#pam-greeter-service=lightdm-greeter
#xserver-command=X
#xserver-layout=
#xserver-config=
#xserver-allow-tcp=false
#xserver-share=true
#xserver-hostname=
#xserver-display-number=
#xdmcp-manager=
#xdmcp-port=177
#xdmcp-key=
#unity-compositor-command=unity-system-compositor
#unity-compositor-timeout=60
#greeter-session=example-gtk-gnome
#greeter-hide-users=false
#greeter-allow-guest=true
#greeter-show-manual-login=false
#greeter-show-remote-login=true
user-session=xfce
#allow-user-switching=true
#allow-guest=true
#guest-session=
session-wrapper=/etc/lightdm/Xsession
#greeter-wrapper=
#guest-wrapper=
#display-setup-script=
#display-stopped-script=
#greeter-setup-script=
#session-setup-script=
#session-cleanup-script=
#autologin-guest=false
autologin-user=manjaro
autologin-user-timeout=0
#autologin-in-background=false
#autologin-session=UNIMPLEMENTED
#exit-on-failure=false

#
# Seat configuration
#
# Each seat must start with "Seat:".
# Uses settings from [SeatDefaults], any of these can be overriden by setting them in this section.
#
#[Seat:0]

#
# XDMCP Server configuration
#
# enabled = True if XDMCP connections should be allowed
# port = UDP/IP port to listen for connections on
# key = Authentication key to use for XDM-AUTHENTICATION-1 or blank to not use authentication (stored in keys.conf)
#
# The authentication key is a 56 bit DES key specified in hex as 0xnnnnnnnnnnnnnn.  Alternatively
# it can be a word and the first 7 characters are used as the key.
#
[XDMCPServer]
#enabled=false
#port=177
#key=

#
# VNC Server configuration
#
# enabled = True if VNC connections should be allowed
# command = Command to run Xvnc server with
# port = TCP/IP port to listen for connections on
# width = Width of display to use
# height = Height of display to use
# depth = Color depth of display to use
#
[VNCServer]
#enabled=false
#command=Xvnc
#port=5900
#width=1024
#height=768
#depth=8
</pre>

**Comment by philmmanjaro** [comment]
Somehow lightdm doesn't find the session configuration:
<pre>[+0.10s] DEBUG: Seat seat0: Failed to find session configuration none
[+0.10s] DEBUG: Seat seat0: Can't find session 'none'</pre>
then it loads the greeter. It would be best if you try to build xfce-minimal systemd for yourself.

**Comment by philmmanjaro** [comment]
This is really weird. It doesn't matter what is configurated in lightdm.conf. This is what Arch is recommending:

**Enabling autologin**

Edit the LightDM configuration file and ensure these lines are uncommented and correctly configured (/etc/lightdm/lightdm.conf)
```
[SeatDefaults]
pam-autologin-service=lightdm-autologin
autologin-user=username
autologin-user-timeout=0
session-wrapper=/etc/lightdm/Xsession
```

LightDM goes through PAM even when autologin is enabled. You must be part of the autologin group to be able to login without entering your password:
```
# groupadd autologin
# gpasswd -a username autologin
```
To match it, I simply added:
```
pam-autologin-service=lightdm-autologin
autologin-user-timeout=0
```
... which didn't change anything. It might be inside of **systemd**. I still don't know how to list the order of loaded services, so I may check if some had changed ... May [livecd change](https://github.com/manjaro/manjaro-tools-livecd/commit/9b225ecdcbf30ef621a4aa1668ea6cd84f112b97) seems not to be the origin of this issue. It doesn't matter, as I tested it locally by reverting it ... Some is really fishy here ...

**Comment by Kirek** [comment]
built xfce-minimal with latest manjaro-tools https://github.com/manjaro/manjaro-tools/commit/07e0659c936bb124b8b825936fa612bcd7b61800 and it autolog without problems.

**Comment by philmmanjaro** [comment]
Ok, I'll check again. Might be a glitch in the Matrix ... I assume you used unstable branch ...

**Comment by philmmanjaro** [comment]
Hmm. Really weird. Seems this issue is back. Also I got reports from others regarding this matter ...

**Comment by philmmanjaro** [comment]
Hmm, current build with XFCE and lightdm works again with latest devel-branch. Weird.

**Comment by drevoborod** [comment]
this issue is actual also for INSTALLED archlinux with XFCE+lightdm.

**Comment by philmmanjaro** [comment]
Yeah, we will see how often it will happen after all. Really a weird issue, though.
