### ISSUE TITLE
[buildiso] graceful exit after errors

### ISSUE THREAD

**Issue by ryanvade** [manjaro/manjaro-tools#104]
An enhancement suggestion. If an error occurs it would probably be good if cleanup would occur.  Remove stale files that can't be removed unless you reboot, for example if pacman can't find a package you want installed to the image.

**Comment by ryanvade** [comment]
A similar system would be good if you stop the proccess during building ( ctrl + C for example)

**Comment by philmmanjaro** [comment]
@ryanvade: please post about your error you're still facing, as we thought we already implemented it with https://github.com/manjaro/manjaro-tools/issues/78.

**Comment by udeved** [comment]
@ryanvade 

Which version do you use?
The devel branch should be fine, I changed yesterday some checks.
buildiso is not run if it fails profile check or buildset sanity check.

**Comment by ryanvade** [comment]
For example, if you add a package to the list which is not able to be installed then you still get image files that can't be deleted due to "Stale File" issues.  I also think pressing ctrl + c should stop the application not just the current process. Its not just errors, if a user wants to stop for some reason shouldn't the tools cleanup?

**Comment by udeved** [comment]
Which version do you use?

What you describe does not happen with git devel version.

**Comment by ryanvade** [comment]
The last time it happened was with manjaro-git-tools built two days ago.  I have not had the issue since.

**Comment by ryanvade** [comment]
Just for record this is what I mean:
```
==> Start building [gnome]
 --> Profile: [gnome]
==> Cleaning up ...
  -> Deleting chroot 'gnome-image'...
rm: cannot remove '/var/lib/manjaro-tools/buildiso/gnome/i686/gnome-image': Device or resource busy
  -> Deleting chroot 'root-image'...
rm: cannot remove '/var/lib/manjaro-tools/buildiso/gnome/i686/gnome-image': Is a directory
 --> Loading Packages: [Packages] ...
```
Caused by cancelling a previous build then trying again.

**Comment by philmmanjaro** [comment]
For that we need a proper **pre-unmount** before starting a session.

**Comment by udeved** [comment]
Can also be done with umount_handler at build_image calls.

**Comment by philmmanjaro** [comment]
Great, then we call that!

**Comment by udeved** [comment]
I think I already added it in pkglist branch.

**Comment by philmmanjaro** [comment]
Ok, then simply backport it to master.
