### ISSUE TITLE
increase checksum secuirty

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-tools#105]
a md5 checksum is ok to check, whether the download was corrupted or not. but it is not a good security feature, because it can be tampered with.

sha-256 or sha-512 checksums offer much better security. should they be made default in the manjaro-tools?

**Comment by udeved** [comment]
Hmm, I am undecided, it can be set in manjaro-tools.conf

**Comment by excalibur1234** [comment]
yes, i know. 

i do that. but i have not seen anybody else doing it. it seems that anybody else in the team is using the default setting.

i am not mad, if you keep md5 as default. just think about it. you can also ask the team what they think.

**Comment by udeved** [comment]
What do you think team?

**Comment by Kirek** [comment]
Change the default to sha256, but really this is not a security feature it's to check against corrupted downloads.
