### ISSUE TITLE
Add support for overlayfs

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#106]
Since linux318 **overlayfs** is supported within Manjaro Linux. Currently we are using **aufs** within buildiso for all kernels. It would be also good to support another filesystem for our install medias. Here is a small example for how to use **overlayfs**:
```
mkdir -p /tmp/{lower,merged,upper,work}
sudo mount -t overlay overlay -o lowerdir=/tmp/lower,upperdir=/tmp/upper,workdir=/tmp/work /tmp/merged
```
A full documentation can be found [here](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/overlayfs.txt).

**Comment by Kirek** [comment]
Even it's it supported since linux318, until linux40 it didn't gain all features we need: multiple lower layers.

**Comment by philmmanjaro** [comment]
Yes, only with **linux40** or higher we should enable **overlayfs**. That's why we should re-add displaying kernel version in -q switch again.

**Comment by Kirek** [comment]
First try https://github.com/manjaro/manjaro-tools/commit/2a06b641c1154d1bb1c3efe104c0ea101b452930

**Comment by ryanvade** [comment]
Is there a benefit to using overlayfs?

**Comment by philmmanjaro** [comment]
@ryanvade: if we don't try we never would know. To have options is always good. We try to use it anyway with our Manjaro 0.9-series ...

**Comment by telephone** [comment]
> Is there a benefit to using overlayfs?

It's pretty awesome with [profile-sync-daemon](https://github.com/graysky2/profile-sync-daemon) and [anything-sync-daemon](https://github.com/graysky2/anything-sync-daemon) :+1:.

**Comment by Kirek** [comment]
With overlayfs branch an linux40 it currently boot to desktop (checked kde and xfce) using only overlayfs, seems to be some problems with starting calamares thought.

**Comment by philmmanjaro** [comment]
@Kirek: can you post me any terminal log of **calamares** using the **-d** switch? Does **thus** start up?

**Comment by Kirek** [comment]
After testing thus (crashed when trying to rsync the new system because the thus.conf was not created in that iso), tried calamares again and started. It seems it didn't like the system partitions and closed itself, after thus recreated the partitions it worked fine...
Rebooted, and installed the new system with calamares without problems.

**Comment by philmmanjaro** [comment]
@Kirek: Calamares don't support **lvm/luks** yet. That's why. Regarding **thus**, yes - the config needed to be modified first. This means your work is "working" ;). Please adjust the code as mentioned by @udeved earlier and push all overlayfs related stuff in a separate lib we can source.

**Comment by udeved** [comment]
The idea is to dynamically source the proper lib according to switch, and we adjust the code and use same function names for the two file system mount operations.

**Comment by Kirek** [comment]
What's to separate? they are one line commands...

**Comment by udeved** [comment]
Nevermind, is it ready to merge?

**Comment by udeved** [comment]
I actually like the overlayfs.
It much better in handling mounted images.
Need to correct couple of things thogh after my changes.

**Comment by udeved** [comment]
Whats the mimimum kernel req for overlayfs so we can document it in the config?
Starting with 4.0 series?
3.19 doesn't work, 4.1 does.

**Comment by Kirek** [comment]
4.0 is the minimum, it added support for multiple lower layers

**Comment by udeved** [comment]
Ah, thx, exactly what the error cause, joining multiple images.

**Comment by philmmanjaro** [comment]
Currently I'm building 4.1 again. Somehow the i686 build doesn't boot up on my end. I might have found a patch for that matter, still don't know why x86_64 boots, though ...

**Comment by udeved** [comment]
I will try with kernel 4.0. 
I've only tested x86_64 iso yet, but building with overlayfs enabled is fine.

**Comment by philmmanjaro** [comment]
With build I ment the kernel itself. I always hit a kernel fault.
