### ISSUE TITLE
Implement a pkgcache per iso as requested by anex

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#11]

**Comment by udeved** [comment]
I don't know if this is a practiable thing anex.

It would be very difficult to keep the package cache for an entire iso in sync, clean, make sure no old version is still in cache.

Already the lng and xorg cache can be tricky, and its only useful if you immediately rebuild to avoid the xorg download every time.

I would close this for now.
Perhaps we can repoen it at some point, but I currently see no elegant way to achieve this.

**Comment by anexation** [comment]
yea i agree im going to close this thanks though artoo
