### ISSUE TITLE
Gain iso-profiles clone/pull ability?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#113]
As title says.
We could drop iso-profile packages this way..

**Comment by philmmanjaro** [comment]
So you want to use just our git-repositories and don't release any iso-profile packages? As developers it doesn't matter, as we mostly use git versions anyway. Here we have to think as users and how to use our product. User should use fixed versions we released. Therefor the given profiles should work. As of now I see issues in profiles only work properly with git-versions of manjaro-tools. I think when manjaro-tools has a standard we can find a proper way to handle this matter. All is possible ...

**Comment by udeved** [comment]
Kirek got me the idea, he asked why we do profile packages, and I kind of agree.
Most people use git anyway I guess.

**Comment by udeved** [comment]
Btw, whats the approcimate time taböe for 0,9,0
I thnk we should do a manjaro-tools-0.9.9 soon, ie merge devel branches

**Comment by Kirek** [comment]
Well first we have to thing why we release this profiles packages.
To me the idea is to release a manjaro-tools/profiles packages that work well together, so people can just install the packages, copy the profiles somewhere and build and iso.

If we implement download profiles with manjaro-tools, it should be something like "buildiso --download-profiles" and this profiles should work with the installed version of manjaro-tools.
And I think it should download a tarball, not git clone: for example https://github.com/manjaro/manjaro-tools-iso-profiles/archive/master.tar.gz. People who want to use git can do it themselves.

**Comment by Kirek** [comment]
PD: still I think the profiles package is mostly useless, because in the reality this profiles usually became broken after a while, and we already recommend to download latest master.
Maybe it will be a lot easier to just say "download the profiles from github" in the tutorials...

**Comment by udeved** [comment]
If we do this, we always need to properly tag profiles instead of just using a commit.

**Comment by philmmanjaro** [comment]
Well, regarding Manjaro 0.9.0 release. We decided to jump on the 0.9.x wagon when Calamares is ready to be used. So we are now almost at Calamares 1.1 release by the end of this week. Current 1.1-rc3 can be tested within my current [0.9.0-dev-build](http://sourceforge.net/projects/manjarotest/files/0.9.0/xfce-minimal/0.9.0-dev/) or the current [Netrunner Rolling build](http://arch.netrunner-os.com/ISO/). If we say it is ready to go, we can release it as needed. If not, we wait. Don't make releases of [b]manjaro-tools[/b] a dependency of any ISO-releases.

**Comment by udeved** [comment]
INo worries, I won't.
I was just asking, as calamares seems to be coming close again to be used.
The reason I asked, I wanted to have some time before calamares to merge devel profiles, and also devel in master and do a 0.9.9 release we need for profile changes.
In my view, we can merge rather sooner than later, before too many pkglist commits in master.
We would need some time before we do manjaro-0.9.0 to fine tune the new Package lists.
Some Package may got lost in the transition, nothing breaking though.
My aim would be than we got at least the 3 official iso buildable for both inits, which works, but needs some tuning of package selection..

**Comment by udeved** [comment]
Last user post
https://forum.manjaro.org/index.php?PHPSESSID=1rj490a9rj2p580nkqgjh6j6p2&topic=26253.msg224142

I do think a valid point.

**Comment by philmmanjaro** [comment]
Well, users should use the provided packages if they use the stable release. If they develop they should use the git version. Seems we missed to release a 0.9.12 snapshot of our profiles. Will note that one down for our **0.9.13** release.
