### ISSUE TITLE
[util-iso] local-repo problem

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#115]
*original posted by @oberon2007*

local-repo.db is recognized during installation of root- and i3-Overlay-images but then I get ```"error: failed retrieving file 'local-repo.db' from disk : Couldn't open file /home/bernhard/local-repo/local-repo.db"```
see: http://pastebin.com/u17DTyfh

**Comment by Kirek** [comment]
Pretty sure this fixes it https://github.com/manjaro/manjaro-tools/commit/276d2a1be5640772ea5ef52d12ee6820035a4e3e

**Comment by philmmanjaro** [comment]
@oberon2007: can you confirm it?

**Comment by udeved** [comment]
I have him on irc, but it takes a bit to confirm due to unknown reasons. I suspect a broke local-repo

**Comment by philmmanjaro** [comment]
Well, there is no pressure here. Take all the time needed ;) And hopefully your neighbours are so kind even if it gets louder ...

**Comment by udeved** [comment]
I pushed the poor man last hour, but thats the downside with local repos, you can't build these profiles.

**Comment by philmmanjaro** [comment]
Well, I understand the usage of local repos. But to support it and maintain those packages might be hard. They will be listed as AUR packages, as we don't ship them offical. It would be rather better to add those packages to [community] rather than to a personal local repo. For users to build their own thing, yes - but not for an official community edition of Manjaro!

**Comment by udeved** [comment]
I am waiting for him to send me the packages, I can also ask him to send the PKGBUILDS, as they are not on AUR.

**Comment by udeved** [comment]
I tested my self, https://github.com/manjaro/manjaro-tools/commit/276d2a1be5640772ea5ef52d12ee6820035a4e3e did fix it.

**Comment by philmmanjaro** [comment]
Great. Thx. Seems we are back on the workflow. Everybody is fixing issues. Makes me really happy to see our dreamteam working :+1:

**Comment by udeved** [comment]
Part great, now I need to fix the i3 merge conflicts, or I simply delete it and readd after merge, which is probably faster than fixing dozens of files in i3

**Comment by oberon2007** [comment]
For me not a problem if you delete i3 in master. There is nothing relevant. Everything is up-to-date in devel. :) Good night now!

**Comment by oberon2007** [comment]
Confirm that I have finally been able to build the d*** ISO with the local-repo, too 8^)

**Comment by philmmanjaro** [comment]
@udeved: you can rename the i3-devel profile, copy over the i3-master profile and do a diff as I did with [manjaro-tools-iso-profiles|#34](https://github.com/manjaro/manjaro-tools-iso-profiles/pull/34). The conficts might have happen due some backports of mine in some other profiles. Anyway, I think you'll manage it.

**Comment by udeved** [comment]
Its a huge diff :octopus: 
I think I will delete and readd the one from devel.

**Comment by oberon2007** [comment]
please do that! ... in you sleep?

**Comment by philmmanjaro** [comment]
Yes, delete master. Commit the changes as one commit. Then merge the history of 'devel' to 'master'. Would be the best option here.

**Comment by udeved** [comment]
@philmmanjaro 

Rebase master?

**Comment by philmmanjaro** [comment]
* clone master branch
* delete everything except **.git**
* clone devel branch to a second dir
* copy over all files from 'devel' to empty 'master' without **.git**
* push those changes to 'master'
* create a pull-request to merge 'devel' into 'master'

Result: history is also transfered

**Comment by udeved** [comment]
Ok, that's basically the same like quickly correcting the Packages-Desktop in each profile and do only that for i3. i mean copy i3 devel in master.
couple of minutes...

**Comment by philmmanjaro** [comment]
There are several ways to Rome ;)

**Comment by oberon2007** [comment]
Mystery solved after I had the same issue again today when attempting to build the other arch.
Problem is when you use Mousepad to paste in local-repo at the very end of pacman-xxx.conf the \n at the end can go missing. Weird still that only the last image has a problem with that while the first images are built successfully. Maybe there's a difference in the code at that moment that could be more "tolerant"? ;) Anyway, will not trust Mousepad again! :D
