### ISSUE TITLE
proper disabling 'plymouth'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#117]
Seems we have a small issue with disabling 'plymouth' on our current **manjaro-tools 0.9.9** release. In XFCE-minimal we have it enabled for only systemd. It is fine for me that OpenRC disables it. So when it is set to false in **profile.conf** also **sysmenu** and **grub** needs to be modified, so we get rid off 'quiet' and 'splash'. **grub**, if I remember correctly is already fixed for that. Only **sysmenu** must be edited during creation of the menu.

**Comment by udeved** [comment]
Yes, its a small issue I forgot, and realized after release we need to clean up isolinux.cfg and perhaps set chroot/etc/default/grub.

In what way does "quiet" option disturb plymouth? Quite is just quite initramfs loading I think.

**Comment by philmmanjaro** [comment]
For plymouth you need ```quiet splash``` in **isolinux.cfg** and **/etc/default/grub**. To display text during bootup both variables have to been removed. We already have **write_isolinux_cfg()**. We simply should add variables like ```quiet="quiet"``` and add ```$quiet``` to the lines if plymouth is true. Similar for **splash**.

**Comment by udeved** [comment]
Afaik, 'quiet' option is set on openrc iso too, 'splash' as well.
That's why I noticed it, openrc needs "splash" removed, which is purely cosmetic doesn't do any harm.

**Comment by philmmanjaro** [comment]
yeah, I know. In **thus** you can find this:
```        plymouth_bin = os.path.join(self.dest_dir, "usr/bin/plymouth")
        if os.path.exists(plymouth_bin):
            use_splash = "splash"
        else:
            use_splash = ""

        if "swap" in self.mount_devices:
            cmd_linux_default = ('resume=UUID={0} quiet {1}'
                                 .format(self.swap_uuid, use_splash))
        else:
            cmd_linux_default = 'quiet {0}'.format(use_splash)```

If quiet is set, you don't see the text on bootup. So quiet has also to be removed. At least splash needs to be removed for sure. But on isolinux.cfg I suggest to get rid of 'quiet' too.

**Comment by udeved** [comment]
Just to summarize:

Plymouth needs splash but not quiet?
Never ever used plymouth, so no experience with it.

If we remove quiet, we get verbose boot on systemd, including initramfs, and just verbose initramfs on non systemd.

**Comment by philmmanjaro** [comment]
Plymouth needs 'quiet' so no text is displayed and 'splash'. To display text on bootup you have to get rid of both. 'quiet' simply removes any text display on bootup. 'splash' is used to display 'plymouth'. I already fixed it now.
