### ISSUE TITLE
Implement a pkgcache gpt xorg drivers to reduce downlaoding every build

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#12]

**Comment by aadityabagga** [comment]
Hey, shouldnt the xorg cache be divided into 2 folders according to arch, like xorg -> i686 and xorg -> x86_64

I built an iso for x86_64 and all packages lumped under single xorg folder.

**Comment by Kirek** [comment]
It would be a nice feature, but you should open a new issue not reopening and old one :)

**Comment by aadityabagga** [comment]
Hehe, I thought why open another when there is one already present ;)

**Comment by udeved** [comment]
The documentation clearly states that you shouldn't use -x if you build for different arch.

**Comment by aadityabagga** [comment]
not interested in pursuing further.
