### ISSUE TITLE
add feature to publish iso files on server

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#121]
Currently I'm using some personal scripts to maintain my install medias on sourceforge. To create check-sums we already implemented:
<pre>md5sum *x8*iso > manjaro-xfce-minimal-0.9.0-dev-x86_64-md5sum.txt
sha1sum *x8*iso > manjaro-xfce-minimal-0.9.0-dev-x86_64-sha1sum.txt
sha256sum *x8*iso > manjaro-xfce-minimal-0.9.0-dev-x86_64-sha256sum.txt
sha256sum *i686*iso > manjaro-xfce-minimal-0.9.0-dev-i686-sha256sum.txt
sha1sum *i686*iso > manjaro-xfce-minimal-0.9.0-dev-i686-sha1sum.txt
md5sum *i686*iso > manjaro-xfce-minimal-0.9.0-dev-i686-md5sum.txt</pre>

On the other hand I'm using rsync to upload my images to sourceforge:
<pre>#!/bin/sh
user=[sourceforge user]
project=[sourceforge project]
path=0.9.0/xfce-minimal/0.9.0-dev
files=*0.9.0*
pwfile=`pwd`/passwd
sshpass -f $pwfile rsync -vP  --progress -e ssh $files $user,$project@frs.sourceforge.net:/home/frs/project/m/ma/$project/$path
#sshpass -f $pwfile rsync -vP  --progress -e ssh $files $user,$project@frs.sourceforge.net:/home/frs/project/m/ma/$project/$path
#sshpass -f $pwfile rsync -vP  --progress -e ssh $files $user,$project@frs.sourceforge.net:/home/frs/project/m/ma/$project/$path
#sshpass -f $pwfile rsync -vP  --progress -e ssh $files $user,$project@frs.sourceforge.net:/home/frs/project/m/ma/$project/$path
#
#shutdown -h now</pre>

As you can see I'm using also sshpass to provide the needed password in a separate file called **passwd**. Optionally I shutdown my system when the images are larger. 

As the connection might break I call the rsync cmds several times. 

````
6.34.181.57: Broken pipe

rsync: [sender] write error: Broken pipe (32)
rsync error: unexplained error (code 255) at io.c(820) [sender=3.1.1]
````

Using rsync will continue to upload your images. If you have minimal changes you upload in seconds to get the new image there. All you have to use is the same filename.

````
./up.sh
manjaro-xfce-minimal-0.9.0-dev-i686-build.log
        132,441 100%  125.64MB/s    0:00:00 (xfr#1, to-chk=13/14)
````

It might be good if we would have a proper solution within our **manjaro-tools**.

* either config file
* or switches to adjust the needed settings
* option to pass the needed password ad-hoc

**Comment by udeved** [comment]
Lets say we have a publishiso script.
How do we handle passwords?
Plain text password files is no good I think.

**Comment by philmmanjaro** [comment]
Please check [**sshpass**](http://linux.die.net/man/1/sshpass) for this. It either needs a file with plain text or the password added with -p switch in plain text. Especially read the **Security Considerations** section.

**Comment by udeved** [comment]
Yes, I know, so we don't store a ssh password locally, we always use password switch.
Or do we also want to store an encrypted password locally?

**Comment by ryanvade** [comment]
I don't think storing of the password is a good idea. Too many problems..even if it is encrypted. Then you have to worry about the encryption.

**Comment by philmmanjaro** [comment]
Well, somehow you need to "store" it as your upload might get broken and with a re-try you need it again. If you upload several images you do it over night without yourself present ;)

**Comment by ryanvade** [comment]
Perhaps this tool should only work with ssh key login? No passwords to worry about.

**Comment by philmmanjaro** [comment]
Well, maybe you didn't get it yet how sourceforge sftp upload works with rsync. If the pipe breaks a new cmd needs the password again. As we want it to be automated the password has to be stored somewhere. Maybe in RAM ...

**Comment by ryanvade** [comment]
I don't use sourceforge so no, I don't know how they deal with sftp.

**Comment by udeved** [comment]
I will try to make it generic, so not tied to SF.

**Comment by udeved** [comment]
Ok, some ideas I want to share before implementing something.

Apart from password question, we use a centralized location to store isos,
We can use it, but how do we want to handle what iso gets uploaded?

We could make the cache_dir_iso to have subdirs, named according to iso, and we specify what iso to upload.
We could also have all isos uploaded that are in the cache_dir_iso, and perhaps have a blacklist to exclude some iso. 
Or, we have eg /etc/manjaro-tools/deploy.d/{xfce, net, kde} , created when iso is built, and we use then a target arg to select upload.

Please share your thoughts.

**Comment by udeved** [comment]
~~~
$ deployiso -q
==> manjaro-tools
  -> version: r1653.59e9e19
  -> user_config: /home/devtux/.config/manjaro-tools.conf
==> HOST:
  -> cache_dir_iso: /build/manjaro-tools/iso
  -> dist_release: 15.09
==> REMOTE:
  -> remote_url: frs.sourceforge.net
  -> remote_project: manjaro-lxqt-openrc
  -> remote_target: /home/frs/project/m/ma
  -> remote_user: udeved
  -> remote_pwd: Please set your password!
  -> url: udeved,manjaro-lxqt-openrc@frs.sourceforge.net:/home/frs/project/m/ma/manjaro-lxqt-openrc
~~~

Now we have to think about password storage and what mechanism we want for iso selection.

**Comment by udeved** [comment]
It would be easier, if all iso were uploded to the same location.
Reason, we can come up with a server structure that gets created before upload with ssh login.
But, if we want to create remote folders, it would be good to have a common structure.

eg
~~~
official releases
|
|-----xfce
|-----kde

community releases
|
|----cinnamon 
|----lxqt
~~~

How should openrc iso integrate?
We use openrc appended to iso file name.
Probably best was to simply have subfolders in above structure.

**Comment by philmmanjaro** [comment]
Great effort so far. Yes, we have to think about how we structure the server for this. Also more people need then access to upload to the **manjarolinux** project. However we can start with the **manjarotest** project first. Most have only access to **manjarodev**.

**Comment by udeved** [comment]
I have created a sandbox repo, we we can play around with structure.
Phil has admin access.
https://sourceforge.net/projects/manjaro-testing/

**Comment by udeved** [comment]
Quick overview.

I implemented subfolders for the cache_dir_iso in buildiso, so the cache_dir basically holds server tree.
deployiso can be called with profile name to select the iso folder to upload, else it will take cache_dir as default(not implemented yet).
Before uploading, deployiso has to be run with -c arg, to create a release folder on server.

We now have a version generator for the dist_release var.

The downside with SF, before any release is created, the shell service Vserver needs to be manually started atm, or else the server will not be found when trying to connect.

**Comment by ringo32** [comment]
personal: a user should readout the iso what is a preview or rc or fixed iso if a month later a iso rebuild cause of repo as example, people will find the iso and use it as stable iso's but since its on unstable.. is bit mixed up..
even manjaro got history of minor version, and all most fixed stable version. i understand the version would be te same.. only got issues with it , if you can read from the iso file if its a preview rc series...given only to minor is not enough..

**Comment by udeved** [comment]
We should do away with preview vetsions and such things.

**Comment by ringo32** [comment]
people would read 15.12.1 as a fixed version.

**Comment by udeved** [comment]
Nope, ringo, seriously, its a good scheme, we need one, except you come up with something alternative and viable. We can't afford to pollute server with dozens of differently named files and folders, we need order there.

**Comment by ringo32** [comment]
only i would not know to understand , if peopel download iso A but some days after iso A got fixed  and tells isue about iso A how do you explain it, download the iso again that is fixed?

**Comment by udeved** [comment]
Sure, I understand your beef with this, because if some iso is borked, the user has to download anyway new one.

**Comment by philmmanjaro** [comment]
well, we can name them also **-pre1** and so on. Then it would be clearer. But let us roll with this one on the test-server first to see if some needs still to be changed.

**Comment by ringo32** [comment]
also if a build had a borked function lets say. iso A but the fix to name it also iso A not iso A.1 as example, there are users that saves the iso and also mayby weeks after it comes with that iso. how to tell he got that iso. would easier to tell the iso got fixed and a fixed release is up. eventually from te community can tell it. but on first point community wont understand the issue on first place because he had iso a and iso a is current release.. even ubuntu as example 14.04 release there fixed release would be 14.04.1

**Comment by udeved** [comment]
Ringo, quite frankly, let us just establish a structure without worrying what community may or may not understand. Manjaro-tools are development tools, targeting manjaro devs primarily to make life easier.

@philmmanjaro 

Do you think its a viable version scheme for the minor releases? It is basically the same what kde-apps do.
I reverted this scheme back due to the big fuzz it produced. 

Open question to me, if we do say 15.11, what codename does it have and what distrib_release version does it have?

**Comment by ringo32** [comment]
i think codenames you can pull it of as current development this case 15.11 can have bellatrix

**Comment by udeved** [comment]
Good you say that, because Bellatrix is 15.09, hence we should use 15.09.2, the thing you guys disliked so much but did not answer how to handle this otherwise.

**Comment by ringo32** [comment]
Would be ruff if you have every month a different codename Also it can differce from versioning....it can go purely go to Development stage does not mean you must follow 15.09.1 does not tell about that iso is build and developed... codename would have more milestone then a iso build date

**Comment by udeved** [comment]
I stop here, we go in circles, which seriously pisses me off.
You don't need a dev version, if iso has released every month n a rolling release distro.
You would use minor versions to be dev versions, and codenamed version release as major release.
Is it so difficult to understand?

**Comment by udeved** [comment]
Does anybody know how how to start a shell session on SF without login?
Their manual says this to login to remote shell, but I only want to create the 4h lasting session.

    ssh -t USER,PROJECT@shell.sourceforge.net create

So, if we want to use ssh, eg to create folders, we need to start a 4h session first, ugly.

I currently use rsync and an empty dir to create more than one level deep folders.

**Comment by udeved** [comment]
Seem to work without -t arg, but it is painfully slow.
