### ISSUE TITLE
file names pkgs and md5

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#122]
The feature of including 'openrc' now should also be added for the names of pkg-lists and checksum files... :)

**Comment by udeved** [comment]
What  would be the reason to name pkglists?
We have tags for that in the lists.

**Comment by oberon2007** [comment]
Because when the pkg list for an openrc-iso overwrites an existing one for the systemd-iso in the same destdir it is wrong for the iso with the same name. It will include the openrc-packages...

**Comment by udeved** [comment]
You are supposed to clean the chroot before you build for a different init.
So I still don't get the issue here with pkglists.

**Comment by oberon2007** [comment]
I mean those files: /var/cache/manjaro-tools/iso/*pkgs.txt and *iso.md5

**Comment by udeved** [comment]
The checksums is made from iso file name, and for openrc, it takes the openrc appended name.
Have you updated the git version?

I can change the pkgs.txt. 
My use the chache dir is just as temporary location, so I don't store iso files there.

**Comment by oberon2007** [comment]
I'm building with r1529.219d33f-1, yes and it wrote a 'manjaro-i3-0.9.0dev-i686.iso.md5' for a 'manjaro-i3-openrc-0.9.0dev-i686.iso' file.
I'm making updated dev-builds, four versions in a row (32/64/systemd/openrc). So they all just go to the some dir. Of course I can move them - just since we have the feature of 'openrc' being included in the iso-file names it would be logical to have consistant naming for all corresponding files, I think.

**Comment by philmmanjaro** [comment]
**compress_images()** uses **${iso_file}** which is defined by **load_profile()**. Therefor your checksum file should have the same name as given iso-image. I patched now the lines for pkgs_file.

Please add followed line before ```line 614``` in **/usr/lib/manjaro-tools/util-iso.sh**
<pre>	msg3 "Debug -  compress_images(): ${iso_file}"</pre>
Post me the snippet of your log if you still have the issues with your checksum file.

**Comment by oberon2007** [comment]
Fixed, thank you! :)
