### ISSUE TITLE
file ownership

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#123]
There seems to be something wrong with ownership of the resulting files. As you can see the checksum file of the 64bit-ISO is owned by root while all others are owned by user.

-rw-r--r-- 1 bernhard users  974127104 08.07.2015 16:42 manjaro-i3-openrc-0.9.0dev-i686.iso
-rw-r--r-- 1 bernhard users         70 08.07.2015 16:43 manjaro-i3-openrc-0.9.0dev-i686.iso.md5
-rw-r--r-- 1 bernhard users      14871 08.07.2015 16:22 manjaro-i3-openrc-0.9.0dev-i686-pkgs.txt
-rw-r--r-- 1 bernhard users 1117487104 08.07.2015 17:24 manjaro-i3-openrc-0.9.0dev-x86_64.iso
-rw-r--r-- 1 root     root          72 08.07.2015 17:24 manjaro-i3-openrc-0.9.0dev-x86_64.iso.md5
-rw-r--r-- 1 bernhard users      16145 08.07.2015 17:02 manjaro-i3-openrc-0.9.0dev-x86_64-pkgs.txt

**Comment by philmmanjaro** [comment]
This is really odd. Never checked it on my end. Never cared ...

**Comment by udeved** [comment]
Easily fixed.
We call chown before checksum is created, hnece checksum has root ownership.

**Comment by oberon2007** [comment]
Not a big deal ;) I was just surprised when I deleted some old files and then realized that I was using the file browser as normal user ...

**Comment by oberon2007** [comment]
Either the chown is not working, or it is undone later:
```
$ la /var/cache/manjaro-tools/iso/manjaro-i3-o*
-rw-r--r-- 1 bernhard users 972029952 09.07.2015 22:30 manjaro-i3-openrc-0.9.0dev-i686.iso
-rw-r--r-- 1 bernhard users        70 09.07.2015 22:30 manjaro-i3-openrc-0.9.0dev-i686.iso.md5
-rw-r--r-- 1 bernhard users     14878 09.07.2015 22:06 manjaro-i3-openrc-0.9.0dev-i686-pkgs.txt
```

**Comment by udeved** [comment]
Its fine, its exactly user/groups its supposed to be, except you want it root owned.

**Comment by oberon2007** [comment]
Ok. Good. I thought since the files live in /var/cache they'd be supposed to be owned by root. But I agree that there's no reason for that :)
