### ISSUE TITLE
[buildiso]add ability to run image in qemu after build

### ISSUE THREAD

**Issue by ryanvade** [manjaro/manjaro-tools#126]
I noticed that in testiso there is some rudimentary qemu support already.  Are there plans to continue qemu support further?  I think adding support for running the created image right after building would be a good enhancement.  Something like this maybe:
```
buildiso -p gnome  -b testing -a x86_64 -c -qemu -ram 6G -qemu_image /home/ryanvade/qemu.cow -qemu_options "-enable-kvm"
```
perhaps the ability to create an image with the ISO name could be useful too?

**Comment by udeved** [comment]
Actually, I don't plan to support qemu directly from buildiso.
