### ISSUE TITLE
[buildiso] modifying boot screen

### ISSUE THREAD

**Issue by ryanvade** [manjaro/manjaro-tools#128]
I am wondering if it is possible to modify the boot screen (change wallpaper, default boot option, etc)?  I assume it is syslinux, if so where is the pkgbuild? Is there a better way to modify it?

**Comment by philmmanjaro** [comment]
Well, we are using [gfxboot](https://github.com/manjaro/artwork-gfxboot). See how Sonar Linux modified [theres](https://github.com/manjaro/artwork-gfxboot-sonar).
A binary version of the generated files we put in our [profile](https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/shared/isolinux).

**Comment by ryanvade** [comment]
Thank you for the links.
