### ISSUE TITLE
Use linux41, overlayfs and the new version scheme by default

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools#131]
Default kernel: linux41
overlayfs=true
version scheme something like: manjaro-xfce-2015.08-1-Bellatrix-x86_64.iso

Should we change that now in preparation for the next release? 
Probably it wont be sooner than September, taking into account our current release pace.

This way we can start finding issues with overlayfs, etc

**Comment by philmmanjaro** [comment]
Yes, we can do that. It doesn't matter if **overlayfs=true** by default. If **manjaro-tools** find kernels lower than **4.0** it will automatically switch back to **aufs3**.

**Comment by philmmanjaro** [comment]
Implemented with 0c4fe33f9e366ee3fe5ae4aeed1d83e03c8ddccb
