### ISSUE TITLE
[overlayfs] Systemd: Could Not Start Commit Transient Machine-ID on disk

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#132]
Hi guys, with commit 394fd987efd4ac0e45cfa96061cbd5709e3cc111 I already tried to fix this minor issue. Using Aufs we don't have it. Seems **overlayfs** is behaving differently in that case. Has somebody a clue why we have this "issue"?

**Comment by Kirek** [comment]
Fixed with newer kernels (4.2 or 4.1 with backported patches)
