### ISSUE TITLE
switch_root: failed to unlink ro_branch still present on rc3

### ISSUE THREAD

**Issue by AJSlye** [manjaro/manjaro-tools#137]
Can we please see if we can fix this?
Not that this message is critical, it's just annoying.

**Comment by philmmanjaro** [comment]
Why, it doesn't hold us back to boot the image. If you find time to debug it, fine. At the moment it is low prio on my end.

**Comment by AJSlye** [comment]
Good enough.

**Comment by AJSlye** [comment]
I accidentally hot the wrong button, clemens doesn't want to see this error.

**Comment by philmmanjaro** [comment]
Here is an really old [take on the matter](http://chakraos.org/forum/viewtopic.php?id=8492). Do you still use **aufs** on your end?

**Comment by philmmanjaro** [comment]
Also here the part of the **aufs** manual:
```
config AUFS_BR_RAMFS
	bool "Ramfs (initramfs/rootfs) as an aufs branch"
	help
	If you want to use ramfs as an aufs branch fs, then enable this
	option. Generally tmpfs is recommended.
	Aufs prohibited them to be a branch fs by default, because
	initramfs becomes unusable after switch_root or something
	generally. If you sets initramfs as an aufs branch and boot your
	system by switch_root, you will meet a problem easily since the
	files in initramfs may be inaccessible.
	Unless you are going to use ramfs as an aufs branch fs without
	switch_root or something, leave it N.
```

Current **aufs config** can be found [here](https://github.com/manjaro/packages-core/blob/master/linux41/config.aufs).

**Comment by philmmanjaro** [comment]
However, we might even try the **Ubuntu-way**:
```
CONFIG_AUFS_BDEV_LOOP=y
# CONFIG_AUFS_BRANCH_MAX_1023 is not set
CONFIG_AUFS_BRANCH_MAX_127=y
# CONFIG_AUFS_BRANCH_MAX_32767 is not set
# CONFIG_AUFS_BRANCH_MAX_511 is not set
# CONFIG_AUFS_BR_FUSE is not set
CONFIG_AUFS_BR_HFSPLUS=y
# CONFIG_AUFS_BR_RAMFS is not set
# CONFIG_AUFS_DEBUG is not set
# CONFIG_AUFS_EXPORT is not set
# CONFIG_AUFS_FHSM is not set
CONFIG_AUFS_FS=m
# CONFIG_AUFS_HNOTIFY is not set
# CONFIG_AUFS_RDU is not set
CONFIG_AUFS_SBILIST=y
# CONFIG_AUFS_SHWH is not set
# CONFIG_AUFS_XATTR is not set
```

**Comment by Kirek** [comment]
the message is still there with overlayfs

**Comment by philmmanjaro** [comment]
We might need to take a look at our **hooks** as in:
```
    NOTES
           switch_root will fail to function if newroot is not the root of a mount. 
           If you want to switch root into a directory  that  does  not  meet this 
           requirement then you can first use a bind-mounting trick to turn any 
           directory into a mount point:

                  mount --bind $DIR $DIR
```

**Comment by AJSlye** [comment]
Yes I'm using overlayfs as well.

**Comment by AJSlye** [comment]
This could also be what is causing the plymouthd issue:
    If you sets initramfs as an aufs branch and boot your
    system by switch_root, you will meet a problem easily since the
    files in initramfs may be inaccessible.

**Comment by philmmanjaro** [comment]
For more info on the hooks you can take also a look [here](https://github.com/manjaro/manjaroiso/commits/master/src/hooks/miso)

**Comment by AJSlye** [comment]
I'll have to look at that when I have time to sit and read it. ;)

**Comment by AJSlye** [comment]
On a side note: have you already looked at systemd 2.2.5's switch to take the place of su?

**Comment by Kirek** [comment]
Its 225 :)
Yes, I looked at machinectl shell, though it doesn't replace the su binary or anything like that, even if it does almost the same thing.

**Comment by AJSlye** [comment]
So it does almost the same thing but not the same thing. Hmm, interesting, I'll need to do some reading when I get a chance.  :)

**Comment by Kirek** [comment]
Look are the original issue about that: https://goo.gl/ZGvjNM

**Comment by philmmanjaro** [comment]
Well, I searched a lot. **switch_root** apparently only works on true initrd (cpio style, not using squashfs). So one option would be to silence **switch_root** in the **init** hook on livecd-kernel-image. Archlinux don't has it as they use **dmsnapshot**.

**Comment by AJSlye** [comment]
Excuse me for not being knowledgeable on such things, but what is the advantage of squashfs?
And is there another option other than switch_root?

**Comment by philmmanjaro** [comment]
**switch_root** root works, but creates those warnings with [squashfs](http://www.tldp.org/HOWTO/SquashFS-HOWTO/whatis.html). However using **dmsnapshot** in combination seems to make it work. However **aufs** and **overlayfs** might have some issues as you can read ;)

**Comment by AJSlye** [comment]
So, have you decided how to proceed on this issue yet?

**Comment by philmmanjaro** [comment]
There is no issue. It is just a warning message ...

**Comment by AJSlye** [comment]
Yes, but is there a way we can suppress it for now?

**Comment by philmmanjaro** [comment]
What do you think I'm trying to do for 3 hours?

**Comment by AJSlye** [comment]
I wasn't saying that, I know you've been working hard on it.
I was just wondering if you've found anything yet. ;)
I do apologize if I unintentionally offended.

**Comment by AJSlye** [comment]
I've been keeping an eye on this for packaging for Clemens as the git gets commits:
https://quickgit.kde.org/?p=scratch%2Fhein%2Fsimplemenu.git
