### ISSUE TITLE
provide msg functions with manjaro-system?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#138]
Should we move the util-msg.sh to manjaro-system package?

We could use the functions in PKGBUILD etc too

**Comment by philmmanjaro** [comment]
Hmm, interesting. What exactly do you have in mind and how to use it?

**Comment by udeved** [comment]
Well, atm we source the util-msg.sh in manjaro-tools.
I noticed that some PKGBUILDs use also msg functions, and if we install the msg lib with eg manjaro-system, we can use the msg functions for system stuff too. Kind of unified terminal msg.

**Comment by philmmanjaro** [comment]
Well, I think there is not much development in this file. For now I suggest to keep it in **manjaro-tools** and simply add the current version also to **manjaro-system**. We can decide later if we move it then completely.

**Comment by udeved** [comment]
Basically, I would like to have the small import function somehow available, so all scripts can use it to source other scripts.

**Comment by philmmanjaro** [comment]
Ok. I'm fine with that.

**Comment by udeved** [comment]
We would need to make it sourced on session login I think, or we put it in bashrc
