### ISSUE TITLE
manjaro-tools-efiboot

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#139]
guys, there is a big disadvantage with getting the systemd-efi.
We constantly have to update it which isn't necessary, we just use it to get the iso booted.
For example I added it to manjaro-tools group, now systemd has already 226 and 225 is not available at url
If we use simply last gummiboot from seblu pkg archive as source, we don't have to rebuild the package from new source if we change minor stuff in the build.

**Comment by Kirek** [comment]
And why you don't change the version to 226?

**Comment by udeved** [comment]
Why not just a keep a static target, and be done with it?
Its overblown to get a systemd package that often has new releases just to extract a totally small sized file to get the iso booted in efi.

**Comment by udeved** [comment]
What I am saying, it doesn't make sense.
If you want to really keep always latest systemd efi file, then we make it so that you use it from your system, and I integrate the stupid efi thing in eudev-systemdcompat, which already gets systemd and libsystemd package.
But, I would prefer last gummiboot.

**Comment by Kirek** [comment]
No, gummiboot is dead.
Just change a single number in the pkgbuild, run updpkgsums, spend 5 seconds downloading the systemd package and build it.
It's not that difficult.

**Comment by udeved** [comment]
I already do that for the eudev-systemdcompat package, which is installed on openrc systems, we just have to change copy path, and I will also gut out the efi file then.
Why so complicated and maintaing two packages which do the very same thing?

**Comment by udeved** [comment]
So lets drop that package, on systemd host, the efi file is copied from host, and on openrc the same.
As said, I will make eudev-systemdcompat supply the efi file.

**Comment by philmmanjaro** [comment]
I forgot to update it. Will do now.

**Comment by udeved** [comment]
Don't, I have stuff ready to commit.

**Comment by udeved** [comment]
https://github.com/manjaro/packages-extra/commit/a99d8a214f86e7a630fbe8a6016172563b14f5c0

**Comment by philmmanjaro** [comment]
Hmm, for now I added it back (https://github.com/manjaro/packages-extra/commit/6655c0e7cda34637505cd97cd52172b66a8bf233) as we have to see what we do about it. I've first to review the code changes to see if they make sense. As of now we have **0.9.12** as our stable released package which needs **manjaro-tools-efiboot**.

**Comment by udeved** [comment]
Its all fine as it is.
manjaro-tools-efi-shell upgrades manjaro-tools-efiboot, and the package just provides the two shells.
We copy the systemd-efi from the chroot.

**Comment by philmmanjaro** [comment]
Ok, you want to provide the efi-file with **eudev-systemdcompat**. In this case the outdated **gummiboot**. You also know that with each **systemd** release the efi changes will go on? **gummiboot** is now **systemd-boot**. The mainmaintainer is and was always a **systemd** developer. Soon or later you will hit rock bottom with this decision as efi changes are and will be maintained by **systemd** from now on.

What is so hard to understand that fact? So once take a look at [systemd-boot](https://github.com/systemd/systemd/tree/master/src/boot/efi) and see for yourself that the development is still going on there. We already had a [long discussion](https://github.com/manjaro/manjaro-tools/commit/39ca4a96ed18e78cf6ab15bc6dfa76bfcb48590f) about it. We is there a need to reopen that topic and even change the source code without even asking the team?

**Comment by udeved** [comment]
https://github.com/manjaro/packages-extra/blob/master/manjaro-tools/PKGBUILD

because I can any time simply drop gummiboot, and take systemd-efi, since I already get the binary systemd package.
So, I don't see why we should have this small efi file tied to the efi shells. Both inits have the efi file installed on system in same location.

**Comment by philmmanjaro** [comment]
Ok. I'm fine with it. As long as you keep an eye on it.

**Comment by udeved** [comment]
So let me worry about efi and openrc, and you guys get what you want for systemd.
Middle ground, but I refuse to be forced to something without being asked.

**Comment by philmmanjaro** [comment]
Totally fine with me. We will see when the switch will be ;)

**Comment by udeved** [comment]
What switch?

**Comment by philmmanjaro** [comment]
With switch I mean, when we release **0.9.13**. I assume your changes are already made in **unstable branch**. Let me built at least a new **dev-build** to test those new changes you made. If all works as expected I see no point in holding back the new version of **manjaro-tools**.

**Comment by udeved** [comment]
I updated unstable with eudev-systemdcompat-226, which contains for 64bit the efi file in same location as on systemd.

**Comment by philmmanjaro** [comment]
Then all is there what we need for **0.9.13**. Let me first do a **dev-build** to varify that all works.
