### ISSUE TITLE
no pacman-mirrors done on the live-cd ?

### ISSUE THREAD

**Issue by Esclapion** [manjaro/manjaro-tools#140]
The mirrorlist points to Africa server who is not very powerfull. When installed in VBox, it's OK.

**Comment by philmmanjaro** [comment]
Well, Africa in A. It is always our first server listed when generated the list without internet connection. And no in live-cd we skipped it so far. It takes too long. You can add a script when your desktop starts.

**Comment by Kirek** [comment]
The updated pacman-mirrors: https://github.com/manjaro/pacman-mirrors/tree/refractor 
It supports randomizing the mirrorlist without any internet connection or pinging.
I still haven't pushed it because it needs more testing.
