### ISSUE TITLE
release 0.9.13

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#141]
This is just a note to myself. Preconditions:

* create a new **dev-build**
* verify the changes
* create a proper change-log
* release the package to **unstable branch**

**Comment by philmmanjaro** [comment]
Build passed for x86_64 with version r1601.9fe7969

**Comment by philmmanjaro** [comment]
Build passed for i686 with version r1601.9fe7969

**Comment by philmmanjaro** [comment]
Install passed both, i686 & x86_64. No regressions found so far.

**Comment by udeved** [comment]
Good. :smile:

**Comment by philmmanjaro** [comment]
New [Capella images](http://sourceforge.net/projects/manjarotest/files/15.12/xfce-minimal/15.12-dev/) for public testing uploaded ...

**Comment by philmmanjaro** [comment]
**0.9.13-rc1** released to **stable**
