### ISSUE TITLE
"plymouthd: Could not start boot splash, no such file or directory"

### ISSUE THREAD

**Issue by AJSlye** [manjaro/manjaro-tools#142]
When booting the live ISO with plymouth, if you hit esc or a function key plymouth is supposed to switch between itself and the text console. however this only works if you hit this twice really fast, after about a sec or two this no longer works and it can't find the splash any longer. This works on shutdown with no issues.

**Comment by AJSlye** [comment]
I was watching the buildiso process and shouldn't plymouth be loaded after these in initcpio:  
[miso_overlayfs] 
[miso_loop_mnt] 
[miso_pxe_common] 
[miso_pxe_http] 
[miso_kms]

Just a thought, I maybe wrong.

**Comment by AJSlye** [comment]
gohlip posted this in the forum on another topic, bit i'm thinking that maybe it's this kind of little mistake that could be part of the issue:
"Manjaro's grub puts the initrd line wrongly for separate boot partition.
There's initrd /boot/intel-ucode.img /boot/initramfs-xxxx.img
when it should be initrd /intel-ucode.img /initramfs-xxxx.img"

**Comment by philmmanjaro** [comment]
Well, the wiki says:

Add **plymouth** to the HOOKS array in **mkinitcpio.conf**. It must be added **after** base and udev for it to work:
```
/etc/mkinitcpio.conf
HOOKS="base udev plymouth [...] "
```

**Comment by philmmanjaro** [comment]
Seems I was totally confused by your post @AJSlye. I restored the old **grub-2.02.beta2-10** as else Arch never would have adopted our patch.

**Comment by philmmanjaro** [comment]
ucode is always installed at **/boot/intel-ucode.img**. `make_system_path_relative_to_its_root /boot/intel-ucode.img` detects the relative path and creates `/intel-ucode.img` if needed.

**Comment by philmmanjaro** [comment]
@AJSlye: did you test to re-arrange the **mkinitcpio.conf** to your suggestion and tested it yet?

**Comment by AJSlye** [comment]
No, I went to bed last night. The point wasn't intel-ucode, it was the Manjaro's grub puts the initrd line wrongly for separate boot partition part.

I'm going to take a look at the 2014.09 ISO which plymouth works correctly on, and see what might have changed since then. The 2014.09 was based on the Manjaro-kde-0.8.10 ISO.

**Comment by philmmanjaro** [comment]
There is no issue what so ever. Otherwise you won't even been able to boot your installation after selecting a separate **/boot** partition. This would have been noticed by our community from the get-go. I also tested the current version of grub. No issues to been found:

```
[johnd@john-pc Desktop]$ cat /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a device; this may
# be used with UUID= as a more robust way to name devices that works even if
# disks are added and removed. See fstab(5).
#
# <file system>                           <mount point>  <type>  <options>  <dump>  <pass>
UUID=c0ab3fd8-c1bc-41ae-89ab-834f4783f188 /boot          ext4    defaults,noatime 0       2
UUID=6c78034b-e53e-4c53-adba-0ba3b12a0f2a /              ext4    defaults,noatime 0       1
[johnd@john-pc Desktop]$ sudo update-grub
[sudo] password for johnd: 
Generating grub configuration file ...
Found background: /usr/share/grub/background.png
Found Intel Microcode image: /boot/intel-ucode.img
Found linux image: /boot/vmlinuz-4.1-x86_64
Found initrd image: /boot/initramfs-4.1-x86_64.img
Found initrd fallback image: /boot/initramfs-4.1-x86_64-fallback.img
Found memtest86+ image: /boot/memtest86+/memtest.bin
done
[johnd@john-pc Desktop]$ sudo cat /boot/grub/grub.cfg | grep intel-ucode
	initrd	/intel-ucode.img /initramfs-4.1-x86_64.img
		initrd	/intel-ucode.img /initramfs-4.1-x86_64.img
		initrd	/intel-ucode.img /initramfs-4.1-x86_64-fallback.img
```

**Comment by AJSlye** [comment]
I wasn't referring to the intel-ucode itself, just the possibility that something might be pointed in the wrong direction. while searching I found that this error can come up when plymouthd can't reconnect to the graphics adaptor and/or find the proper resolution again (KMS / vesa mode setting). The other reason this error can occur had to do with the fstab, but I can't seem find that forum post again.

**Comment by philmmanjaro** [comment]
Well, **plymouth** is not officially supported by Arch. If we find a solution I'm happy for it. However current **grub** might not be related to this issue here.

**Comment by AJSlye** [comment]
Agreed, however if it is in the grub file I'll let you know, but not until
after I have a look at whatever changes leszek had made to your
Manjaro-kde-0.8.10 released ISO for netrunner-rolling 2014.09 that made
this work. This is not a show stopper bug for me, just an annoyance. You
can go ahead and either close it, move it elsewhere or whatever else you
think is appropriate.

**Comment by philmmanjaro** [comment]
Simply keep me updated if you find something.

**Comment by AJSlye** [comment]
No problem.

**Comment by AJSlye** [comment]
One quick update, I'm wondering now if this is a systemd issue.
Using the latest ISO that I built, if I hit esc I still get the virtual console with the output in it, however now when I hit esc again I no longer get this error, it's just saying starting plymouth splash again but the plymouth splash doesn't actually reload.

**Comment by AJSlye** [comment]
OK, your version of Plymouth is 0.8.9-1, in the AUR there are 3 pkgbuilds:
plymouth 0.9.2-3
plymouth-git 0.9.2.r0.g2c437c3-1
and
plymouth-legacy 0.8.8-4

I'm not sure which one your pkgbuild is based off of but I'm going to do some tests with these pkgbuilds to see if any of these would fix our issues here.

**Comment by AJSlye** [comment]
I'm also confused by one of your post, is grub-2.02.beta2-10 older than upstreams  grub-1:2.02.beta2-5?

**Comment by philmmanjaro** [comment]
**grub-2.02.beta2-10** is from the source code newer than that what Arch is shipping. I released a repacked version as **grub-2.02.beta2-11** as you got me confused with the **ucode** stuff. Now the old package is restored.

**Comment by philmmanjaro** [comment]
I've now added a new package called **plymouth-dev**. This was tested by Eugen F. Also we had a regression with **0.8.9** in regard of [luks](https://forum.manjaro.org/index.php?topic=26911.0) so the normal **plymouth** package is back to **0.8.8**.

**Comment by AJSlye** [comment]
Does the new plymouth-dev package fix the issue here?

**Comment by philmmanjaro** [comment]
You may want to try it yourself if your issue is fixed by this. Eugen just tests it against password entries with luks encryption.

**Comment by AJSlye** [comment]
I finally got a chance to try this out and still no luck.
