### ISSUE TITLE
remove package from working copy of the chroot

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#144]
Corresponding to the -i option it would be a great feature to be able to uninstall a certain pkg from the chroot.
At the moment when I build pkg with conflicting dependencies one after the other I have to delete the chroot completely - or am I missing something here?

**Comment by AJSlye** [comment]
I don't remember an -i option unless you mean the -n (Install and run namcap check) option?
You could always use the -c option (Recreate chroot) or the -w option (Clean up).

**Comment by oberon2007** [comment]
man buildpkg lists `-i PKG Install a package into the working copy of the chroot.`
Does -c not delete the whole chroot? What exactly will -w do?

**Comment by philmmanjaro** [comment]
```
Usage: buildpkg [options] [--] [makepkg args]
    -p <pkg>           Buildset or pkg [default: default]
    -a <arch>          Arch [default: i686]
    -b <branch>        Branch [default: unstable]
    -r <dir>           Chroots directory
                       [default: /var/lib/manjaro-tools/buildpkg]
    -i <pkg>           Install a package into the working copy of the chroot
    -c                 Recreate chroot
    -w                 Clean up cache and sources
    -n                 Install and run namcap check
    -s                 Sign packages
    -q                 Query settings and pretend build
    -h                 This help
```

A remove function we don't have yet ...

**Comment by oberon2007** [comment]
Yes, that's exactly what I mean :)

**Comment by AJSlye** [comment]
Oops, I apologize. I was looking at the wiki:
https://wiki.manjaro.org/index.php?title=Manjaro-tools#buildpkg

**Comment by udeved** [comment]
Why do you want to remove a package from chroot?
Can you explain your problem with example?

**Comment by oberon2007** [comment]
Example: I build conky-i3 which requires conky.
After that I want to build lua-clock-manjaro which requires conky-lua, which conflicts with conky.
I have to delete the chroot to be able to build it.

**Comment by udeved** [comment]
Yes, recreate chroot is probably best in this case.

**Comment by oberon2007** [comment]
Unfortunately not, because conky-lua still uses 1.9 and conky is at 1.10 with new config-syntax :stuck_out_tongue: So that means to provide something like ``buildpkg -R conky`` is not feasilbe? Like, just the opposite function of -i <pkg>? Complicated?

**Comment by oberon2007** [comment]
Would you mind pointing me to the place in the code where the -i option lives?

**Comment by udeved** [comment]
Its doable, but the devil is in the details what pacman removal args to use.
Simple _R option could generate errors if other stuff depend on the package.
So, the clean solution is indeed recreating choot in my view.
We'd kind of pollute the chroot I thnk, undermining the purpose of building in chroot, and the chroot could end up like a normal system when makepkg is run.

**Comment by oberon2007** [comment]
Yes I understand :-) thanks!

**Comment by udeved** [comment]
The only case we have to remove a package from chroot is when building eudev stuff, so libsystemd has to go from chroot. I am thinking about a way to improve this with fake groups.
