### ISSUE TITLE
[buildiso livecd]

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#145]
For a strange reason since very recently i3status is not able to set LC_ALL=C when trying to launch and fails.
No idea how this problem can occur only now. i3status has not changed and also an older version has the same issue.
Trying to export the variable from .xinitrc is ineffective, why?
Please see here: https://forum.manjaro.org/index.php?topic=26538.new#new
and here: https://github.com/i3/i3status/issues/64

**Comment by oberon2007** [comment]
Is it this? https://github.com/manjaro/manjaro-tools/commit/8d677ab5a5f402481aedbb8c362a16a8dc5e1112

**Comment by Kirek** [comment]
Well, easy to test if that's commit, just select a language that's not en_US or de_DE at boot and see how it goes.

**Comment by oberon2007** [comment]
I have reverted the commit in the chroot and that solves it.

**Comment by oberon2007** [comment]
Do you have a suggestion for a workaround? Or could we revert it?

**Comment by oberon2007** [comment]
Will if ``$DESKTOP_SESSION = "i3"`` already be present at that moment?

**Comment by oberon2007** [comment]
So if you don't want to revert it we could do ``if [ $DESKTOP_SESSION = "i3" ]; then`` ?

**Comment by Kirek** [comment]
No, if this causes a problem we just revert it. It only saves a second or so.

**Comment by oberon2007** [comment]
Great, thank you. I have spent all those seconds today finding the problem ... ... :laughing:

**Comment by Kirek** [comment]
Done

**Comment by oberon2007** [comment]
Well unfortunately now with **manjaro-tools-iso 0.9.15-3** I have the same problem again 
```$ i3status
Could not set locale. Please make sure all your LC_* / LANG settings are correct.
```
What has happened since? Please help.

**Comment by oberon2007** [comment]
Since I cannot reopen this I have created a new issue https://github.com/manjaro/manjaro-tools/issues/167
