### ISSUE TITLE
failed to create mhwd-image

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#146]
Hi , today try to build an iso for pantheon profile and found a strange issue.. i try 4 time and the buildiso exit with error .. this the query verbose
http://pastebin.com/1BJ3nbEA
and this the error
http://pastebin.com/tVGmBYV2
if you see my repo for pantheon : pantheonrepo works but when it called for mhwd-image exit with error .
i try to add in my real pacman.conf and with pacman -Syy it work fine exactly before mhwd-image i not understand why..

**Comment by philmmanjaro** [comment]
```
error: failed retrieving file 'pantheonrepo.db' from disk : Couldn't open file /home/stefano/pantheonrepo/x86_64/pantheonrepo.db
error: failed to update pantheonrepo (download library error)
error: failed to prepare transaction (could not find database)
  -> overlayfs: unmount mhwd-image
==> ERROR: Exit make_image_mhwd
```

why do you use a local repository?

**Comment by Ste74** [comment]
Because i have forked a packages to alucryd repo root work with mutter 3.14
. Pantheon not work fine with 3.16.
I have a repo on a tuxfamily server but to build and test use a localrepo.
Il 27/set/2015 21:59, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by philmmanjaro** [comment]
Well, seems that overlay doesn't know your local repo, though.

**Comment by Ste74** [comment]
This is the strange before this point. It work.
Il 27/set/2015 22:10, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by philmmanjaro** [comment]
Ask @udeved what might got wrong here. I think you should add that local repo to your profile **pacman.conf**.

**Comment by Ste74** [comment]
Ok,tomorrow try to add.., talk about it with artoo on irc dev channel this
evening but no idea.
Il 27/set/2015 22:18, "Philip Müller" <notifications@github.com> ha scritto:

**Comment by udeved** [comment]
There is currently no support for local repos.
The custom repo has to be accessible online.
I made it so to ensure a profile can always be built by anybody.
Ie local repos are removed from custom pacman.conf

**Comment by philmmanjaro** [comment]
Works as designed then ;)

**Comment by Ste74** [comment]
Sound good...yeah tomorrow upload on repoarch on tuxfamily server and trust
to rebuild. Thank guys
