### ISSUE TITLE
buildpkg does not update pkgver in PKGBUILD

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#147]
When I run makepkg on a pkg, the pkgver array will be updated. However when I run buildpkg that does not happen. Is that intentional?

**Comment by philmmanjaro** [comment]
The **PKGBUILD** gets updated only thru **makepkg** or inside the chroot we use in **manjaro-tools**. For example **calamares-dev** is versioned **2.0a2**, which is the current alpha branch it is at. If we want to have also the **PKGBUILD** updated in our **packages git-repo** we have to copy it from the chroot back to the folder it get sourced from.

**Comment by philmmanjaro** [comment]
The same will happen if you build a pkg with **devtools** in a chroot. But I didn't tested it yet.

**Comment by Kirek** [comment]
In devtools it event explicitly invokes makepkg with "holdver" flag.

**Comment by udeved** [comment]
Yep kirek, it is intended behavior.
