### ISSUE TITLE
Automate buildpkg

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#149]
It would be very nice to have the ability to to put a buildlist as cron job and then auto boxit the built packages.

Any thoughts?

**Comment by philmmanjaro** [comment]
Roland will rework our build-system soon. We will use some part of **manjaro-tools** for this new feature. This will also allow us to build every package or install-media on our build-server. This will happen after our re-launch of our web-server.

**Comment by udeved** [comment]
sounds good.

What parts will it use?
I plan to enhance pkgbuilding for eudev, so that it already creates a eudev chroot, without libsystemd.
Leads me to next thought, probably a separate repo for this alternative stuff?

**Comment by philmmanjaro** [comment]
It will be a re-write in **go**. Roland will use ideas from **boxit** and **manjaro-tools**. Keep on developing **manjaro-tools** as it is. The new environment will happen earliest in Spring 2016. Development by DesertBit can be tracked [here](https://github.com/desertbit).
