### ISSUE TITLE
make buildiso path independent?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#153]
We got deployiso being path independent, it can be run from anywhere.

Do we want buildiso to detect the iso-profiles, so it can be run from anywhere too?

**Comment by philmmanjaro** [comment]
Would be nice to have, but how do you search for profiles and save their location for the next time?

**Comment by udeved** [comment]
We would be searching for a unique file in the iso-profiles, eg .manjaro-tools.
However, this doesn't play out well if we have say sonar in $HOME as well.
We could save path in new user config location.

**Comment by philmmanjaro** [comment]
Ok, then step by step. It doesn't have to be in **0.9.15**. There is no rush for it.

**Comment by oberon2007** [comment]
I agree, would be great to have! For me it would be sufficient to have a default location for **iso-profiles** and the option to change the path in **manjaro-tools.conf** manually.

**Comment by udeved** [comment]
I got a working buildiso being path independent.

We should think about how to detect or tell buildiso what iso-profiles directory it is supposed to run in.
The easiest would be to configure it in a variable, but I think a detection is better, that stores the path in a file, eg in $HOME/.config/manjaro-tools/iso-profiles.conf

**Comment by udeved** [comment]
Some thoughts.

In order to detect iso profiles repos, we need a consistent naming for repo additions.

eg 
manjaro-iso-profiles
netrunner-iso-profiles
sonar-iso-profiles

I had some test, where detected repo paths are written to a  $HOME/.config/manjaro-tools/$repo.conf

The difficulty is to set $repo without a consistent naming.

**Comment by udeved** [comment]
Ok, it now also works with any repo name.

Upon buildiso run, it tries to detect iso-profiles repos in $HOME.
If found, it writes a $reponame.conf with run_dir=$path that is sourced.
To select repo, it has to be defined in manjaro-tools.conf.
