### ISSUE TITLE
no default DM

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#155]
lightdm service is only enabled when ``displaymanager="lightdm"`` is explicitly set in **profile.conf**
I think this used to be the default.
Has this been intentionally changed? If so it should be made clear in **profile.conf.example** I think, because you assume that listed and commented out means that it is the default.

**Comment by udeved** [comment]
Default setting if commented displaymanager="none"

Documentation is not up-to-date yet.

**Comment by oberon2007** [comment]
OK. Thanks.

**Comment by oberon2007** [comment]
great new avatar btw :D
