### ISSUE TITLE
Clean chroot now with every build?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#157]
I noticed now that we clean-up the chroot on every build. Is this now default and wanted?

**Comment by udeved** [comment]
Not that I am aware of.
But, we changed the git version in the scripts to have a git id rather than version number.
This causes check_chroot to recreate the chroot, because the version check detects new chroot version.
Perhaps its not ideal for our git package to have a git version variable.

**Comment by philmmanjaro** [comment]
No, I'm talking about the regular build. Maybe it doesn't like to have **0.9.15-rc1** as version. Simply install the current non-git-version and try to build a package. It will recreate the chroot every time. That's why I was wondering ...

**Comment by udeved** [comment]
Hmm, it works for me with git version, updating chroot works on my end.

Please review https://github.com/manjaro/packages-extra/commit/a70c0855b95b5628ad91d1eef7f3f2070d504f47

**Comment by philmmanjaro** [comment]
Will check that later ...

**Comment by philmmanjaro** [comment]
Hmm, the latest changes gave me now this:
```
==> ERROR: chroot '/var/lib/manjaro-tools/buildpkg/stable/x86_64/phil' is not at version r1784.d895624. Please rebuild.
```
Will check what will happen next if I build another package in the same chroot. The funny thing is, I'm doing **unstable** here. Some is wrong with the check.

**Comment by philmmanjaro** [comment]
Ah, forget the stable cmd. manjaro-tools.conf changed it's location. I forgot about that.

**Comment by philmmanjaro** [comment]
Ok, I can confirm: removing the check doesn't do anything. It still deletes the chroot on each build of a package. So we have to fix this issue on **systemd** systems.

**Comment by philmmanjaro** [comment]
I'm stupied. Did again a **-c** build ... Tilt.
