### ISSUE TITLE
convert iso-profiles to new structure

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#159]
We have to convert the iso-profiles to the new structure. Also we have to inform Sonar Linux about the changes and build at least one of their profiles to check if some bigger issues are there.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles-sonar/commit/681064aafa0187a34dc11ac2fab787384d21aa4d

The little script works for sonar too, but I have to build one of the sonar profiles yet.

**Comment by philmmanjaro** [comment]
Ok, then create also there a branch and notify at least Kendell about the upcoming changes.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles-sonar/tree/profiles/15.12.rc

Testing branch is done.
