### ISSUE TITLE
buildiso not working at all since latest git pull of iso-profiles

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#160]
I have just installed the newest tools **r1627.1a4aff8** and pulled the iso-profiles.
When I launch **buildiso** I hear that the harddrive is busy but get no terminal output at all and nothing else happens.
I have removed the tools with -Rsn, reinstalled, deleted the chroot manually, rebooted, but nothing changes that.

**Comment by udeved** [comment]
Please posŧ buildiso command with -qv args.

**Comment by oberon2007** [comment]
It's the same. It gives me no output at all - only a busy hdd 8-|

**Comment by udeved** [comment]
Then post the manjaro-tools.conf please.
I need more info, but I can tell already, that your revision number is outdated.

Current revision is at 1788.xxxx

**Comment by udeved** [comment]
Btw, don't build manjaro-tools-git in chroot.

**Comment by udeved** [comment]
Just run makepkg -sri.
You don't have current version, my bet is, you built it in chroot. 
buildpkg does not update revisions and takes the version that is set in the PKGBUILD.

**Comment by oberon2007** [comment]
I was always using makepkg. Have deleted the sources again. Now I have **r1788**
.config is the default installed by the pkg. Have deleted the profiles and did a fresh git pull. It's the only profile directory on the system.
Still same behaviour :-/ what else can I do?

**Comment by udeved** [comment]
I have no idea without some output or something.
buildiso works perfectly.

**Comment by oberon2007** [comment]
maybe the output itself is the problem. Since the hdd is working, I will now just let it run and see if it produces any files in the end. Will also try with a different terminal emulator then to see if I get any output there. Right now I am using urxvt

**Comment by udeved** [comment]
Whats the content of $HOME/.config/manjaro-tools folder?

**Comment by oberon2007** [comment]
It's empty since the latest de- and reinstall

**Comment by oberon2007** [comment]
Looks like this is everything that happens since 10 minutes:
[img]http://imgur.com/D0lLCsCl.png[/img]

**Comment by udeved** [comment]
So it uses default /etc/manjaro-tools/manjaro-tools.conf

There should be a manjaro-tools-iso-profiles.conf in your user config dir.

Can you plerase post the config? Give me something to work with, a guessing game won't do here.

**Comment by oberon2007** [comment]
Seen the screenshot of htop? It is obviously just searching for a file named **.buildiso**

**Comment by udeved** [comment]
What is the location of the iso-profiles folder? It must be in $HOME.

**Comment by oberon2007** [comment]
yes it is. **~/manjaro/manjaro-tools-iso-profiles**

**Comment by udeved** [comment]
Ok, place your user config, and create a manjaro-tools-osp-profiles.conf in he user dir.

Paste

run_dir="your/full/path/to/repo" in the file.

**Comment by oberon2007** [comment]
ok. now no searching for .buildiso anymore but I have four processes of **udisksd**

**Comment by udeved** [comment]
My guess is, thge problem is not related to buildiso at all.

The detection of the repo errors out if no repo is found.

**Comment by oberon2007** [comment]
no wait! the udisks processes are not related to buildiso
but it is still looking for **.buildiso** despite the config file!

**Comment by oberon2007** [comment]
**~/manjaro-tools-osp-profiles.conf** is the location, correct?

**Comment by udeved** [comment]
Yes, something is screwed up with your system and processes.
I already wondered why you have a subshell spawned from bash.

I can guarantee you, the detection works as intended and does not make problems.

Still, its very thin info that makes it difficult to help here.

**Comment by oberon2007** [comment]
and **manjaro-tools.conf** is now in **~/.config/manjaro-tools**
Still it is trying to find **.buildiso** forever

**Comment by oberon2007** [comment]
everything worked perfectly fine until tonight... :| I haven't changed anything since the last ISO build this afternoon - except pulling the profiles...

**Comment by oberon2007** [comment]
ok. it's related to the terminal! it works with xterm! hah!

**Comment by udeved** [comment]
I am tired of english now.
 Säubere mal $HOME/.config/manjaro-tools/*

Du hast nicht richitg gelesen, der Pfad stimmt nicht den du benutzt.

Hast du nun in $HOME/.config/manjaro-tools/manjaro-tools.conf?

**Comment by oberon2007** [comment]
Doch doch! Ich habe **$HOME/.config/manjaro-tools/manjaro-tools.conf**
und **$HOME/manjaro-tools-osp-profiles.conf**
Nicht richtig?

**Comment by oberon2007** [comment]
Seit ich nun buildiso einmal erfolgreich aus **xterm** gestartet habe läuft es auch wieder in urxvt - sehr merkwürdig! Jedenfalls muss es was mit dem Terminal zu tun haben...
Danke dir mal und gute Nacht jetzt! :)

**Comment by udeved** [comment]
Ich guck jetzt Aldo-McGregor, und stelle mir vor, Aldo vermöbelt die Merkel oder jemand von der grün-roten Verbrecherbande.

**Comment by oberon2007** [comment]
:D wenns hilft ... ;) Tschüß! Bis bald dann! :)

**Comment by philmmanjaro** [comment]
Ihr seid alle Strange. Welche **terminal** hattest Du denn verwendet?

**Comment by oberon2007** [comment]
;) Das Problem war aufgetaucht mit **urxvt** über daemon. Dann hatte ich buildiso einmal aus **xterm** gestartet und seit dem Moment funktioniert es wieder ... 8^)

**Comment by oberon2007** [comment]
**urxvt** starte ich über dieses Script:
```
#!/bin/sh
urxvtc $@
if [ $? -eq 2 ]; then
  urxvtd -q -o -f
  urxvtc $@
fi
```
