### ISSUE TITLE
[manjaro-tools.conf] iso_name useless var?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#163]
As it is now, we have two very similar variables, that is
iso_name
dist_name

We currently mix them in code. 
Is there any reason we shouldn't remove iso_name from configuration?

Usecase is:

iso_name=manjaro
dist_name=Manjaro

iso_name=sonar
dist_name=Sonar

We can achieve the same by converting dist_name to lower cases, and let iso_name be non configurable, but determined by dist_name.

**Comment by philmmanjaro** [comment]
Fine. Simplify it then ...
