### ISSUE TITLE
shell-init: error retrieving current directory

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#164]
Ok, this is a silly bug but I want to mention it. I started **buildiso** in the directory `/var/lib/manjaro-tools/buildiso/kde/x86_64/` which got cleaned during the process. Logically we get following error output:

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```

This might worry some users, maybe ...

**Comment by udeved** [comment]
I can fix it, should be easy. ;)

**Comment by udeved** [comment]
Kind of silly to 'fix' after looking at it, because we'd have to cover any subdir of iso_cache.
