### ISSUE TITLE
deal with profile structure in master branch

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#165]
At least with the release of **v0.10.0-rc1** we should have migrated **master** branch of our iso-profiles to its needed structure of **devel** branch.

**Comment by philmmanjaro** [comment]
See also: https://github.com/manjaro/manjaro-tools-iso-profiles/issues/87

**Comment by udeved** [comment]
Just curious, why would we have a rc1?
I find this kind of pointless, in my view, rc should be only assigned to 1.0-rc,

**Comment by philmmanjaro** [comment]
Fine with me, do you change some on the given v0.10.0 or not, or is it final then?

**Comment by udeved** [comment]
"Final" in the sense, that 0.10 could be released without feeling bad about it.
The structure is stable, so 0.10.x will be fixes, I played around with the logger for buildiso, we may add some more user override data in $HOME if we want and so, but I don't plan changes in profiles shared folder, except we find out, the Packages-Desktop files for sonar or netrunner are redundant.

**Comment by philmmanjaro** [comment]
Ok, fine with me. So everything is prepared and tested. Sounds good. We should inform all about the upcoming profile change and then no worries about it ;)
