### ISSUE TITLE
Investigate and possibly fix on btrfs

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#168]
buildiso seems to be in need for some special btrfs code.
Reports on forum indicate, something subvolume doesn't get mounted.

https://forum.manjaro.org/index.php?topic=29267

**Comment by philmmanjaro** [comment]
Well, to test it somebody has to create a  btrfs partition. Maybe build inside a virtual machine ;)

**Comment by philmmanjaro** [comment]
Seems to be also related to this matter: https://forum.manjaro.org/index.php?topic=27438.0

**Comment by ryanvade** [comment]
btrfs subvolumes are under heavy rewrites and most of the developers are not considering it stable at the moment until kernel 4.5.  There is also a bug with systemd 228 (systemd-tmpfiles) and btrfs subvolumes in the Arch core repo. Maybe these bugs are related?

https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg48899.html

**Comment by philmmanjaro** [comment]
Maybe. Most of **manjaro-tools** is developed on **openrc**. Most users use **systemd**. We will look into it.

**Comment by udeved** [comment]
On the forums, eugen tested, and it seems to be a systemd thingy.
He said it builds fine on openrc with btrfs.

**Comment by philmmanjaro** [comment]
Yep, it is a known issue with **systemd**. See also the post from @ryanvade.
