### ISSUE TITLE
Budgie session for V10.1 autologin livecd

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#169]
Hi , in the new version the session is called in /usr/bin/budgie-desktop and it contain 
exec gnome-session --session=budgie-desktop $*
(see this for more explain : https://github.com/solus-project/budgie-desktop/tree/master/session ).
In my util-iso-image.sh have modified this :
elif [ -e "$1/usr/bin/budgie-desktop" ] && [ -e "$1/usr/share/xsessions/budgie-desktop.desktop" ]; then
			default_desktop_executable="budgie-desktop"
			default_desktop_file="budgie-desktop"
			msg2 "Detected Budgie desktop environment"
but with gdm start gnome-shell and with lightdm loop into lightdm ..

where i wrong ?

**Comment by Ste74** [comment]
well i put in .xinitrc 
exec budgie-desktop
and with sartx work fine ..

**Comment by Ste74** [comment]
My workaround is modify the /var/lib/AccountsService/users/manjaro file and change Xsession=gnome with budgie-desktop . I have put this file in budgie-overlay folder and in livecd-overlay but when the iso is created in livecd manjaro file return Xsession=gnome :\ .. expect that ? My workaround at this moment is before create squashfs change the file in buildiso folder and then use -cs array ..

**Comment by korrode** [comment]
Could it be that the check for Gnome at L192 of util-iso-image.sh is succeeding, and thus the check for Budgie is never occurring?
https://github.com/manjaro/manjaro-tools/blob/e5b953329917794580fbb61b6d9a698902efda33/lib/util-iso-image.sh#L192

Try moving the elif statement for Budgie *above* the one for Gnome in the detect_desktop_env function in util-iso-image.sh

**Comment by udeved** [comment]
I suppose the first match is taken if there are two similar scripts called for different desktop env.

I need to test install budgie in vbox, I have currently no clue about this budgie thingy.

**Comment by udeved** [comment]
@Ste74 

What user-session is set in lightdm.conf in live session?

**Comment by Ste74** [comment]
For this release not used lightdm, switched on gdm because for use lightdm
budgie need gnome-session but i see after play with gdm. I have to upload
the change in profile. You see my first msg.. now budgie session is called
with budgie-desktop and no budgie-session ....
Il 30/dic/2015 20:36, "udeved" <notifications@github.com> ha scritto:

**Comment by Ste74** [comment]
@udeved  , uploaded now .. OT .. why smartgit unitialized 2 file on bspwn ? 
![screenshot_20151230_211214](https://cloud.githubusercontent.com/assets/11218234/12056730/11dd0234-af3a-11e5-9de1-2217556ca243.png)

**Comment by udeved** [comment]
Ste, but gdm or lightdm is same, gdm pulls in gnome-session.
Can you try with lightdm and add the packages?

**Comment by Ste74** [comment]
you mean add gnome-session in pkg's and try to rebuild an iso with lightdm ?

**Comment by philmmanjaro** [comment]
As @korrode already pointed out. Budgie needs to be checked before **gnome-session**. So your modification needs to be on top of that check. See also **KDE4** and **KDE5**.

**Comment by philmmanjaro** [comment]
@Ste74: please provide us the **build.log**. As of now it is a **else-if routine**. I think we should better change it to a **case routine**. If Several sessions are available, in this case **gnome-session** and **budgie-desktop** one has to be prefered. With the current modification it normally should detect **gnome-session** and then **budgie-desktop**. Can you also post the display manager configuration files, so we can see what was added there?

**Comment by udeved** [comment]
Right Phil, I am on it.
Was gonna try with associative array like this:

~~~
declare -A desktop_list=(
	[plasma]=startkde
	[kde-plasma]=startkde
	[gnome]=gnome-session
	[xfce]=startxfce4
	[cinnamon]=cinnamon-session-cinnamon
	[mate]=mate-session
	[enlightenment]=enlightenment_start
	[LXDE]=lxsession
	[lxqt]=lxqt-session
	[pekwm]=pekwm
	[pantheon]=pantheon-session
	[budgie-desktop]=budgie-session
	[i3]=i3
	[openbox]=openbox-session
	[fluxbox]=startfluxbox
	[deepin]=startdde
)
~~~

**Comment by udeved** [comment]
Or we query pacman db for the session package in chroot inst5ead of binaries and files detection?

**Comment by philmmanjaro** [comment]
@udeved: [budgie-desktop]=budgie-desktop

And I think **gnome-session** is now a dependency ?!?

```
cat /usr/bin/budgie-desktop
#!/bin/sh
exec gnome-session --session=budgie-desktop $*
```

@Ste74: please confirm that. This would mean that the current package shouldn't work at all.

**Comment by Ste74** [comment]
@philmmanjaro ok... few minute for finish process

**Comment by Ste74** [comment]
yes , confirm , gnome-session is a dependency for budgie , i not see because i switched on gdm but in aur repo maintener update the pkgs ,
https://forum.manjaro.org/index.php?topic=29623.msg246250#msg246250

**Comment by philmmanjaro** [comment]
I'll push some new packages to [unstable]. Please check later if that works now. Also provide then the **build.log** output from the terminal ...

**Comment by Ste74** [comment]
@philmmanjaro i am embaracced but where locate the build.log ? :\

**Comment by philmmanjaro** [comment]
@Ste74: please save the output of your terminal. Set a higher history value so you have all. @udeved added a log-function, but I think it is not yet enabled. Proof me wrong Marcus ...

**Comment by Ste74** [comment]
ok , no problem , I thought there was a log file.
with lightdm and addiction of gnome-session the sistem not start.. :\ 
here the log...
https://gist.github.com/Ste74/9908b8964c3054cd1116

**Comment by philmmanjaro** [comment]
Well, you have no default desktop set and the routine just detected **gnome-session**:
```
==> Configuring [budgie-image]
  -> Setting plymouth manjaro-extra-elegant ....
  -> Configuring Displaymanager ...
  -> No default desktop environment set, trying to detect it.
  -> Detected Gnome desktop environment
  -> Configured: lightdm
```

Point me to your profile.

**Comment by Ste74** [comment]
you intend all budgie folder ? If yes i upload in our manjaro-profile repo time ago , the only difference is now the use of lightdm , in online repo i have set gdm
https://github.com/manjaro/manjaro-tools-iso-profiles/tree/master/community/budgie

**Comment by philmmanjaro** [comment]
Seems we have forgotten to mention that we have some options you can override now. You can set the desktop you want to load explicitly now:

```
# set desktop environment
# default_desktop_executable="none"
# default_desktop_file="none"
```

See also https://github.com/manjaro/manjaro-tools/blob/master/lib/util.sh#L292

**Comment by udeved** [comment]
@philmmanjaro 

If I understood correctly, we got for budgie key--value pair:

budgie-desktop.desktop & gnome-session

Yes?

**Comment by philmmanjaro** [comment]
@udeved: no. We have budgie-desktop and budgie-desktop. We don't add the **.desktop** here:
/usr/bin/budgie-desktop & /usr/share/xsessions/budgie-desktop.desktop

However **gnome-session** is also present. @Ste74 should use the override to get sure.

**Comment by udeved** [comment]
I know, but in the current code, we got 
 ~~~
default_desktop_executable="budgie-session"
default_desktop_file="budgie-desktop"
~~~

Note, the .desktop file extension is omitted here.

**Comment by philmmanjaro** [comment]
Yep, this is now corrected (97d0a31e516cd96fd8ccf4b2500387696c55ba41).

**Comment by Ste74** [comment]
@philmmanjaro , in my local util-iso-image.sh but the problem to recognize the desktop remain..to set explicitly the de have to implement in manjaro-tools?

**Comment by philmmanjaro** [comment]
Man, it is already implemented. Read the [updated docu](https://github.com/manjaro/manjaro-tools-iso-profiles/commit/a763644f2a4d3c269f5ef87c0b6ff7fa58bbcc95).

**Comment by udeved** [comment]
See
https://github.com/manjaro/manjaro-tools/commit/5436834f7a6ad7fe16b0e22eac5e5247cef672dc

**Comment by Ste74** [comment]
:p guys is 23.10 :p .. my eyes are little :p ..  ok tomorrow try the new commit .. ;-)

**Comment by udeved** [comment]
Phil, I think it eventually makes sense to revert your last master commit.

**Comment by philmmanjaro** [comment]
I don't think that it is my fault that there is a merge conflict now:
```
[phil@manjaro manjaro-tools]$ git merge origin/devel
automatischer Merge von lib/util.sh
automatischer Merge von lib/util-iso.sh
KONFLIKT (Inhalt): Merge-Konflikt in lib/util-iso.sh
automatischer Merge von lib/util-iso-image.sh
KONFLIKT (Inhalt): Merge-Konflikt in lib/util-iso-image.sh
automatischer Merge von bin/buildiso.in
Entferne .kateproject
Automatischer Merge fehlgeschlagen; beheben Sie die Konflikte und committen Sie dann das Ergebnis.
```

**Comment by udeved** [comment]
Its no problem, Ihad just locally commited my changes to the detection when you pushed yours that targeted "old" detection.

**Comment by philmmanjaro** [comment]
No problem. We will see.

**Comment by Ste74** [comment]
Ok .. guys , finish to build now an iso with unstable repo aaaaaaaand ok remove all my workaround the autologin in livecd work fine but not after installation . Both thus and calamares with autologin put me in gnome session :\

**Comment by philmmanjaro** [comment]
Then we have to see if something still is needed to be setup there. Are the files the same as within the live-session? Check the displaymanager settings and compare them.

**Comment by Ste74** [comment]
Hi @philmmanjaro , i check now.. in the folder
/build/manjaro-tools/buildiso/budgie/x86_64/budgie-image/var/lib/AccountsService/user/ is present file
gdm 
and in
/build/manjaro-tools/buildiso/budgie/x86_64/livecd-image/var/lib/AccountsService/user/ is present file manjaro
this file in gdm contain the default desktop ( or last ) used

**Comment by philmmanjaro** [comment]
Seems I've to do a spin on my own to fix the issue for you ...

**Comment by philmmanjaro** [comment]
This should fix the autologin issue:

https://github.com/manjaro/thus/commit/fbc9ac12bab5fe08960a79fb120ae50418e339e6
https://github.com/calamares/calamares/commit/196ae4aaafc8911767fe992dc06ee63d8342c565

**Comment by philmmanjaro** [comment]
New installers now in [unstable]: https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20151228/005462.html

**Comment by philmmanjaro** [comment]
Seems a rework was needed:

https://github.com/manjaro/thus/commit/b44f7d41d49ce69522f3553aa2e2378ac9854bb3
https://github.com/calamares/calamares/commit/8cbefa12e042ac85239b0312d4477cb21c241823

**Comment by philmmanjaro** [comment]
New installers now in [unstable]: https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20151228/005465.html
@Ste74: please confirm that it works in both installers with and without autologin now to set budgie as default session.

**Comment by Ste74** [comment]
@philmmanjaro calamares work fine , thus no .. it put me in a gnome session :( .. i can upload my spin for you .. in this spin i try to unceck
DesktopEnvironment('/usr/bin/budgie-session', 'budgie-desktop'), # Budgie v8.x but nothing change with check or unceck :( 
my spin is in upload for you ..

**Comment by Ste74** [comment]
@philmmanjaro :( i can upload an iso for you .. try both calamares and thus . Calamares work fine put me in a budgie session but no thus. It put me in a gnome session . I can try to comment the 
DesktopEnvironment('/usr/bin/budgie-session', 'budgie-desktop'), # Budgie v8.x
but nothing change .

**Comment by Ste74** [comment]
Ok .. problem is gdm .. with lightdm works all fine ... Switch with lightdm .. not understand why gdm with thus installer no set fine the session but is equal .

**Comment by philmmanjaro** [comment]
I tested it with **lightdm** only for now. It depends. Maybe gdm needs to be before budgie. What was set as session in gdm?

**Comment by ringo32** [comment]
i do suggest to make a new profile for dconf ,   and change te session  from gnome to budgie-desktop , in /gnome/desktop/session       http://i.imgur.com/HxqxGA0.png    it is stil gnome , budgie, and GDM probably is two hand on a belly ??   also Vbox update from iso 11 keyboard was first ok , but later on it changed to italian :p

**Comment by philmmanjaro** [comment]
@ringo32: the complete ISO is set to Italian by default. However, since the rewrite of **budgie** gnome-session is used. This package is providing the desktop files for Gnome. Therefor we see this extra gnome session.

**Comment by ringo32** [comment]
oh i got wrong i guess :p

**Comment by ringo32** [comment]
what is cons and prons  lightdm vs gdm, gnome-shell get attached so with gdm is also a semi gnome edition aswell ? (gnome-shell) further i dont know what it cause have to take the changes on manjaro-tools first too peak at it

**Comment by philmmanjaro** [comment]
What is your exact question? We set **budgie** as default in this profile. You can see it here:
https://github.com/manjaro/manjaro-tools-iso-profiles/commit/398dad0268262243bb360107cadd55329af45bf0 Other changes I already pointed out in posts before.

**Comment by Ste74** [comment]
If you agree for now I will work on the profile using lightdm pending developments

**Comment by philmmanjaro** [comment]
@Ste74: for me it is fine to **lightdm**. Works and tested on my end.

**Comment by Ste74** [comment]
I agree , also to me ;)

**Comment by philmmanjaro** [comment]
New Budgie is now pushed to testing and unstable. Use whatever branch for your test build to check if still something is missing.
