### ISSUE TITLE
we need a rework on 'machineid'

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#170]
This is the default settings of **Calamares**
```
---
# Whether to create /etc/machine-id for systemd.
systemd: true
# Whether to create /var/lib/dbus/machine-id for D-Bus.
dbus: true
# Whether /var/lib/dbus/machine-id should be a symlink to /etc/machine-id
# (ignored if dbus is false, or if there is no /etc/machine-id to point to).
symlink: true
```

However we set **openrc** basics by default, even on **systemd** systems:
```
write_calamares_machineid_conf(){
	local conf="$1/etc/calamares/modules/machineid.conf"
	echo "systemd: false" > $conf
	echo "dbus: true" >> $conf
	echo "symlink: false" >> $conf
}
```

So we have to investigate why we changed it and correct it for both **init systems**!

**Comment by udeved** [comment]
Basically, openrc doesn't need /etc/machine-id, it will create it if not present via init script.

**Comment by philmmanjaro** [comment]
So we remove the code and use the default settings shipped by **calamares** or what is the best option here? Since **manjaro-tools** detects the **init system** we can make it a little more dynamic ...

**Comment by udeved** [comment]
I had the idea to bind mount machine-id, just like we bind mount /etc/resolv.conf
