### ISSUE TITLE
[deployiso] -u doesn't seem to do what I expect

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#172]
I have copied the existing i3 ISOs to **manjaro-testing/community/i3**
Then I built a new ISO openrc-x86_64 with a minor change (only added an empty directory in /etc/skel).
But now starting ``deployiso -p i3 -u`` now seems to upload the complete ISO again. Why's that?
Is it ok that the systemd and openrc ISOs share the x86_64 folder on the server btw?

**Comment by udeved** [comment]
Just wait, you will notice that update works as intended, the upload speed will exceed the defined limit.

**Comment by oberon2007** [comment]
ok. I'll report later then ... :)

**Comment by udeved** [comment]
The iso is organized in blocks, so you don't only upload the folder, you upload the changes/diff of the entire iso. You may have a wrong idea how the diff works in iso case.

**Comment by oberon2007** [comment]
I see. Exciting! :) How does deployiso decide which ISO to update when there are systemd and openrc present? Will it read the current settings from **profile.conf** or does it compare the file versions of both ISOs of the current arch?

**Comment by udeved** [comment]
It updates either both or what iso changed.

deployiso doesn't care for files, it only syncs folders and their contents.
So deployiso bavigates the structure in the $cache_dir/iso/...

**Comment by oberon2007** [comment]
Got it. But it will not delete content that has been removed locally, or will it?

**Comment by udeved** [comment]
I don't think so. 
There is no intentional option to delete stuff with deployiso.

**Comment by philmmanjaro** [comment]
It won't delete what is on the server. It will just upload the source to the target. If the target is already there, it tries to upload just the differences in a higher speed.
