### ISSUE TITLE
lightdm greeter-session not defined

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#176]
**/etc/lightdm/lightdm.conf** written by manjaro-tools doesn't define the greeter-session. Not a problem apparently as long as the default lightdm-gtk-greeter is used, but Deepin needs:
```[SeatDefaults]
greeter-session=lightdm-deepin-greeter
```

**Comment by philmmanjaro** [comment]
Then we should add this feature. Otherwise it would make no sense if we are not complete.

**Comment by oberon2007** [comment]
Yes, please. It is necessary because the way things are now we have no way to add a custom **/etc/lightdm/lightdm.conf** for the live-environment...
I have looked at the code in **util-iso-image.sh** but it's not something I can fix I'm afraid ;) ::)

**Comment by udeved** [comment]
Should work now, please reopen if something is wrong

**Comment by oberon2007** [comment]
Hm. Didn't work.
Built with **r1848.35376c7**
In live greeter-session line in **/etc/lightdm/lightdm.conf** looks like this:
``#greeter-session=example-gtk-gnome``

**Comment by oberon2007** [comment]
I'm not authorized to reopen apparently ;)

**Comment by udeved** [comment]
There is nothing I can do about, if you screw up your deepin packages.

There is no lightdm-deepin-greeter.conf.The deepin greeter conflicts with your ui package. so I have no clue what's going on here.

**Comment by philmmanjaro** [comment]
The code seems fine to me. Where is your **lightdm-deepin-greeter.conf** located as we just modify the **/etc/lightdm/*greeter.conf** file.

**Comment by oberon2007** [comment]
Also jetzt mal langsam bitte! This is a Deepin package. I am not scewing up anything here. Everything i do here is customize the greeter screen. deepin-greeter works differently and has no lightdm-gtk-greeter.conf. The file we need to modify is /etc/lightdm.conf as I already said. Using the file in overlay works fine.

**Comment by udeved** [comment]
I just tried to build deepin, the ui packages does not provide a greeter.conf, and the deepin-greeter package conflicts with ui package.

**Comment by philmmanjaro** [comment]
Btw. The code only handles **greeter.conf** files and not the **lightdm.conf** file. So which file do you need to be modified?

**Comment by oberon2007** [comment]
**/etc/lightdm/lightdm.conf** needs to contain ``greeter-session=lightdm-deepin-greeter``
as I said in the beginning. That's all
The ISO builds perfectly fine for me by the way!

**Comment by udeved** [comment]
The code lists greeter.conf, and writes matching greeter to lightdm.conf

**Comment by udeved** [comment]
No greeter.conf no modification to lightdm.conf.

All other greeters use greeter,conf.
You should supply one with package, even if empty. I think its simply not implemented to have a config for greeter.

**Comment by oberon2007** [comment]
the resulting lightdm.conf written by manjaro-tools contains ``#greeter-session=example-gtk-gnome`` and not llightdm-deepin-greeter, I'm sorry.

**Comment by philmmanjaro** [comment]
Let me fix this.

**Comment by udeved** [comment]
@oberon2007 

Yes, because your deepin packages do not provide a deepin-greeter.conf

**Comment by philmmanjaro** [comment]
gtk-greeter.conf has no **user-session**. this is stored in **lightdm.con**.

**Comment by oberon2007** [comment]
It is not MY package ;) Please complain in China:
https://github.com/linuxdeepin/dde-session-ui

**Comment by philmmanjaro** [comment]
There is no need to go thru extra hoops. It is fixed now. **lightdm.conf** is now also considered as there is no need to ship a **greeter.conf** at all. These are only needed if they have some extra settings and configs not handled poperly by **lightdm.conf** itself.
