### ISSUE TITLE
Add support for amdgpu

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#180]
I'm working currently on adding support for amdgpu. Followed issues we have:

- the driver only works with kernel 4.2 or higher
- we have to add a function to disable mhwd config for amdgpu (done)
- we have to find a way to remove the package **xf86-video-amdgpu** from being installed when the kernel is not ready for it yet

**Comment by philmmanjaro** [comment]
In **util-iso** followed functions it seems we have to add a kernel version detection routine and add **xf86-video-amdgpu** to be removed if the kernel doesn't support **amdgpu** yet:
```
	if [[ ${1##*/} == 'Packages-Mhwd' ]]; then
		packages_cleanup=$(sed "$_com_rm" "$1" \
			| grep cleanup \
			| sed "$_purge_rm" \
			| sed "$_kernel" \
			| sed "$_clean")
	fi
```

**Comment by philmmanjaro** [comment]
@udeved: any thoughts on this one?

**Comment by udeved** [comment]
Can't we check /proc/config.gz nd grep the config string?
If it exists, we remove xorg driver?

**Comment by philmmanjaro** [comment]
You mean some like `zcat /proc/config.gz | grep CONFIG_DRM_AMDGPU=`?

**Comment by philmmanjaro** [comment]
so replace `[[ ${_used_kernel} < "42" ]] && packages_cleanup="$packages_cleanup xf86-video-amdgpu"` with `[[  -z $(zcat /proc/config.gz | grep CONFIG_DRM_AMDGPU=) ]] && packages_cleanup="$packages_cleanup xf86-video-amdgpu"` then? Remove `_used_kernel=${kernel:5:2} \` ...

**Comment by udeved** [comment]
Yes, something like that.
Haven't looked at our changes yet, but if we check for config string, we are basically no bound to a specific kernel version.

**Comment by philmmanjaro** [comment]
Well, I think proc is only active on the host system. We have to find that config file in the **root-image folder** and check for that one.

**Comment by philmmanjaro** [comment]
... as of now it should work by detecting the kernel version. It is not perfect but for having the config file it seems we have to install kernel headers.
