### ISSUE TITLE
/usr/lib/manjaro-tools/util.sh: line 92: Binary: command not found

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#184]
strange issue, what might that be? maybe I've to restart cos of **glibc** update.

**Comment by udeved** [comment]
Please restart, I was gonna push the torrent creation for deployiso.

**Comment by philmmanjaro** [comment]
Seems not to be **glibc** as it happens also with **0.10.3**. So something changed with todays **unstable** update.

**Comment by philmmanjaro** [comment]
Hmm, strange. On **i686** it seems to be fine with the new **glibc** ...

**Comment by udeved** [comment]
Well, this needs more info.
Where does it occur? buildpkg?

**Comment by philmmanjaro** [comment]
Maybe related to 03e37e8afb8a0f8bdfdb5d9f0df12af9d8bec5b0. It happens with several things, even with **signpkgs**:
```
==> Signing package /home/phil/dev/boxit-work/unstable/core/linux314-headers-3.14.61-1-x86_64.pkg.tar.xz with key philm...
/usr/lib/manjaro-tools/util.sh: line 96: Binary: command not found
```

However only on **x86_64**.

**Comment by udeved** [comment]
I can't confirm or reproduce it on 2 systems, but both openrc running.

**Comment by philmmanjaro** [comment]
If I search the net I find [this](http://ask.metafilter.com/167995/Help-me-do-my-job-with-minimal-effort). Some dude has an issue with a one-liner:
```
while read -r word; do $(grep -F $word /path/to/biglist.txt) && \
echo ${word}2 >> /path/to/output.txt; done < /path/to/small_wordlist.txt
```

**Comment by philmmanjaro** [comment]
What does `[[ -z ${!var} ]] && eval $(grep "^${var}=" "$1")` anyway? Is `${!var}` correct?

**Comment by udeved** [comment]
It loads variables in makepkg.conf.

Perhaps something is wrong with your makepkg.conf?

**Comment by philmmanjaro** [comment]
```
load_vars() {
  local var

  [[ -f $1 ]] || return 1

  for var in {SRC,SRCPKG,PKG,LOG}DEST MAKEFLAGS PACKAGER CARCH GPGKEY; do
      [[ -z ${!var} ]] && eval $(grep "^${var}=" "$1")
	echo "debug: $var"
  done

  return 0
}
```

Here some debug:
```
[phil@manjaro xorg]$ buildpkg -p xf86-video-intel
debug: SRCDEST
debug: SRCPKGDEST
debug: PKGDEST
debug: LOGDEST
debug: MAKEFLAGS
/usr/lib/manjaro-tools/util.sh: line 96: Binary: command not found
debug: PACKAGER
debug: CARCH
debug: GPGKEY
debug: SRCDEST
debug: SRCPKGDEST
debug: PKGDEST
debug: LOGDEST
debug: MAKEFLAGS
/usr/lib/manjaro-tools/util.sh: line 96: Binary: command not found
debug: PACKAGER
debug: CARCH
debug: GPGKEY
```

**Comment by philmmanjaro** [comment]
Hmm, seems to be done with some locale. It couldn't handle **Müller**, **Mueller** works.

**Comment by philmmanjaro** [comment]
```
locale
LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
```

**Comment by udeved** [comment]
Is thius perhaps related to the locale trouble you had with perl too?

**Comment by philmmanjaro** [comment]
Maybe ...

**Comment by udeved** [comment]
Atm, we export this in util-msg.sh

~~~
export LC_MESSAGES=C
export LANG=C
~~~

**Comment by philmmanjaro** [comment]
That would explain it. C can't handle **ü**. Using **ue** fixed it ...
