### ISSUE TITLE
deployiso function 

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#187]
This is only a question where i not found answer . For now deployiso work whit sourceforge server , it possible need staging function whit sourceforge shell ? I ask because the iso ( this need more time for uploading ) is immediatly visible on sourceforge  although he has not finished upload.

**Comment by udeved** [comment]
It is possible to create eg remote directories with shell, but you got to manually start the sf shell and it lasts 4 hours.
If sf shell was running 24/7, this would be a good alternative.

**Comment by Ste74** [comment]
Only 4 hours ? but if inactive or always ?

**Comment by udeved** [comment]
Always. :(
This makes ssh sf shell unusable for our needs, and the shell starts terribly slow.

**Comment by udeved** [comment]
https://sourceforge.net/p/forge/documentation/Shell%20Service/

**Comment by Ste74** [comment]
:( damn it

**Comment by oberon2007** [comment]
Can I add a question? Is is possible to stage folders through the shell? I only know how to do that in the web-interface... ;)

**Comment by Ste74** [comment]
Lol @oberon2007 is my original question but obviously my english was incomprehensible

**Comment by udeved** [comment]
Best way to create folders was ssh, to also check if it already exists.
But, as mentioned, the shell service needs to be started and its slow.

**Comment by oberon2007** [comment]
Yes, creating is fine. But what about staging them? In the web-interface that's a nice feature that you can keep the folders invisible until they are ready for primetime... ;)
I think @philmmanjaro does it like that, he should know! I always have to use the webpage for that, because I don't know how to do it from the shell :)

**Comment by udeved** [comment]
Well, shell is not viable option unfortunately.
Just saying, what you are asking would require a permanently running shell service on the server.

**Comment by oberon2007** [comment]
I'm not sure if we're talking about the same thing. I mean adding an attribute for sourceforge for any folder, like this function of the web-interface:
![staging](https://cloud.githubusercontent.com/assets/11800714/13205608/0b94e2da-d8ec-11e5-9817-f5f63572f3ff.png)

**Comment by Ste74** [comment]
If you read here https://sourceforge.net/p/forge/documentation/Shell%20Service/ is not mentioned

**Comment by udeved** [comment]
@oberon2007 

Yes, we talking the same thing.
But how do you propose this gets created with rsync?

We don't have a shell as viable option, and it doesn't make sense to enhance this any further for a SF hosting. Ideally, we have a server with ssh access up.

**Comment by oberon2007** [comment]
ok. I was not aware how staging works and that it requires an active shell. I thought quite naively obviously that this would be like a flag for a directory that gets stored on the server... :)
