### ISSUE TITLE
Should we use gpg signatures also for our ISO images?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#188]
Hi team,

should we use also gpg signatures for our ISO images? Seems some are [more sensitive](http://blog.linuxmint.com/?p=2994) now ...

**Comment by oberon2007** [comment]
I think that's a great idea. Works really simple once you have your gpg keys set up...
https://www.gnupg.org/gph/en/manual/x135.html
```
$ gpg --output manjaro-cinnamon-minimal-16.02-x86_64.iso --decrypt manjaro-cinnamon-minimal-16.02-x86_64.iso.sig
gpg: assuming signed data in 'manjaro-cinnamon-minimal-16.02-x86_64.iso'
gpg: Signature made Mon 22 Feb 2016 16:39:00 CET using RSA key ID 663CA268
gpg: Good signature from "Bernhard Landauer <oberon@manjaro.org>" [ultimate]
```

**Comment by udeved** [comment]
We should add a counterpart to signpkg, signiso.

**Comment by udeved** [comment]
~~~
==> Creating [sha256] sum ...
  -> sha256 sum: fcc199eff684ecf4fc75675c784e378c9d6461781f4bdca0d8fca7624c9f5d5a  manjaro-lxqt-minimal-openrc-16.02-x86_64.iso
==> Done [sha256] sum
==> Signing iso /build/manjaro-tools/iso/minimal/lxqt-minimal/16.02/x86_64/manjaro-lxqt-minimal-openrc-16.02-x86_64.iso with key
~~~

**Comment by oberon2007** [comment]
Awesome! :sunglasses: Thank you!!

**Comment by philmmanjaro** [comment]
We should communicate how to setup the **gpg-keyring** for **manjaro-tools**.

**Comment by udeved** [comment]
Yes, it uses makepkg.conf provided key however.

A guide how to configure ssh and gpg agent.

**Comment by philmmanjaro** [comment]
I assume by default disabled and therefore optional until properly set up ...

**Comment by udeved** [comment]
Yes, only on -s arg.

**Comment by oberon2007** [comment]
resonance to the first signed ISO is quite positive :) Some more suggestions here fyi https://forum.manjaro.org/index.php?topic=31426.msg258941#msg258941
