### ISSUE TITLE
manjaro-tools-iso-git-r1918.a300acd-1 stopps after de-image creation with error

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#189]
Seems some is wrong within **manjaro-tools-iso-git-r1918.a300acd-1**. It simply stops after de-image creation with an error message. Using however **manjaro-tools-iso-git-r1909.6a8a408-1** with the same profile, the ISO get created.

```
(253/253) installing zfs-utils                   [######################] 100%
 --> Killing chroot process: dbus-launch (28243)
 --> Killing chroot process: dbus-daemon (28244)
Generating locales...
Generation complete.
  -> Copying mate-overlay ...
==> Configuring [mate-image]
  -> Setting plymouth sonar-elegant ....
  -> Configuring Displaymanager ...
 --> Loading [/usr/share/manjaro-tools/desktop.map] ...
  -> Trying to detect desktop environment ...
  -> Detected: mate
  -> Configuring AccountsService ...
  -> Configured: gdm
 --> Configuring [systemd] ....
  -> Setting bluetooth ...
  -> Setting cronie ...
  -> Setting ModemManager ...
==> ERROR: A failure occurred in /var/lib/manjaro-tools/buildiso/mate-sonar/x86_64/mate-image().
    Aborting...
```

**Comment by udeved** [comment]
Related to #45

**Comment by philmmanjaro** [comment]
Well, it happens even without logging.

**Comment by udeved** [comment]
See my last comment, its the wrapper function I guess.

**Comment by philmmanjaro** [comment]
I think it is more or less the **run_safe** function ...

**Comment by udeved** [comment]
Right, but we can easily debig this...

Comment out 

    &> /dev/null

in util-iso-image.sh

**Comment by udeved** [comment]
~~~
--> Configuring systemd ....
  -> Setting bluetooth ...
Created symlink /etc/systemd/system/dbus-org.bluez.service, pointing to /usr/lib/systemd/system/bluetooth.service.
Created symlink /etc/systemd/system/bluetooth.target.wants/bluetooth.service, pointing to /usr/lib/systemd/system/bluetooth.service.
  -> Setting cronie ...
Created symlink /etc/systemd/system/multi-user.target.wants/cronie.service, pointing to /usr/lib/systemd/system/cronie.service.
  -> Setting ModemManager ...
Operation failed: No such file or directory
==> ERROR: A failure occurred in /build/manjaro-tools/buildiso/mate-sonar/x86_64/mate-image().
    Aborting...
~~~

**Comment by philmmanjaro** [comment]
Hmm, now I wonder why it slipped thru in older versions ... https://github.com/manjaro/manjaro-tools-iso-profiles/commit/f30934f1c018daf056dfe6ee242fe24983787aff

**Comment by udeved** [comment]
because we suppressed output, and the wrapper function has an exit trap, that seems to influence exit codes of calls.

**Comment by udeved** [comment]
So how does MM get activated properly on systemd?

**Comment by philmmanjaro** [comment]
Well it was not installed in sonar editions. We should check the warper function again. Catching the error code is ok, but then we should know where to look. in **kde-minimal** for example I get it cos **cups** is not installed and I try to activate it ...

**Comment by udeved** [comment]
The exit trap is basically cool, we can expand it for #174.
Good opportunity to make the exits safe.

**Comment by udeved** [comment]
We need to check if the service file exists.

**Comment by philmmanjaro** [comment]
I don't complain about the error exit. This is great and wanted. However we should print out the error at least.

**Comment by udeved** [comment]
Hang on, we need to remove all stderr to /dev/null stuff.

**Comment by udeved** [comment]
&> /dev/null

This needs to go so we get errors printed.

**Comment by philmmanjaro** [comment]
Take your time. No pressure.

**Comment by udeved** [comment]
Just pushed the logger to tackle this.
It was expected to produce all kind of little errors. ;)

**Comment by philmmanjaro** [comment]
And it seemed it worked just fine ...

**Comment by udeved** [comment]
The basic logging ability works fine,yes. :)

**Comment by udeved** [comment]
With the last commits, kde-minimal builds for me with systemd.
