### ISSUE TITLE
Sets get created in root directory?

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-tools#19]
```
$ mkset -c i3
[sudo] password for aaditya: 
==> Creating [/i3.set] ...
  -> Adding i3-git
  -> Adding i3bar-icons
  -> Adding i3blocks
```
But it is not present in /etc/manjaro-tools/set, but rather in /i3.set

**Comment by udeved** [comment]
fixed in devel branch.

I forgot to change loading path after some changes.

**Comment by aadityabagga** [comment]
will check when devel is merged to master.

btw why is it necessary to recreate chroot everytime there is a change in version numbers

**Comment by udeved** [comment]
If something was changed in chroot, it would ensure you have a recent chroot.
