### ISSUE TITLE
Problems with cache_dir ? ;)

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#199]
I seem to be doing something wrong here ;)
I used to have set ``cache_dir`` in **~/.config/manjaro-tools/manjaro-tools.conf** to
``cache_dir=/home/bernhard/manjaro``
Now because I keep having [this](https://github.com/manjaro/manjaro-tools/issues/198#issue-138434942) problem while @philmmanjaro seems to not have the same issue, I tried to set my **cache_dir** back to the default, but it looks like I'm not able to convince manjaro-tools about that :wink:
First I commented out my custom path at user level, then I defined explicitly ``cache_dir=/var/cache/manjaro-tools`` there
then I checked in **/etc/manjaro-tools/manjaro-tools.conf** and there the default is untouched.
Still I see that buildpkg is trying to use my custom path:
```
==> Leaving fakeroot environment.
==> Finished making: manjaro-tools-git r1979.1dc80fc-1 (Sat Mar 5 09:13:40 UTC 2016)
mv: cannot stat '/home/bernhard/manjaro/pkg/manjaro-tools-base-git-r1931.01e4382-1-x86_64.pkg.tar.xz': No such file or directory
==> ERROR: /home/bernhard/manjaro/pkg/unstable/x86_64/manjaro-tools-base-git-r1931.01e4382-1-x86_64.pkg.tar.xz does not exist!
mv: cannot stat '/home/bernhard/manjaro/pkg/manjaro-tools-pkg-git-r1931.01e4382-1-x86_64.pkg.tar.xz': No such file or directory
==> ERROR: /home/bernhard/manjaro/pkg/unstable/x86_64/manjaro-tools-pkg-git-r1931.01e4382-1-x86_64.pkg.tar.xz does not exist!
mv: cannot stat '/home/bernhard/manjaro/pkg/manjaro-tools-iso-git-r1931.01e4382-1-x86_64.pkg.tar.xz': No such file or directory
==> ERROR: /home/bernhard/manjaro/pkg/unstable/x86_64/manjaro-tools-iso-git-r1931.01e4382-1-x86_64.pkg.tar.xz does not exist!
==> Finished building [manjaro-tools-git] 
```
What am I missing here?

**Comment by oberon2007** [comment]
Ah. Maybe clean the chroot? I'm trying that now...

**Comment by oberon2007** [comment]
So. cleaning the cache doesn't help either. It's not giving up the custom path...
I still get: `` cannot stat '/home/bernhard/manjaro/pkg/...``

**Comment by udeved** [comment]
Why the hell do you build manjaro-tools-git in chroot?
Just curious.

**Comment by oberon2007** [comment]
It's just an example to demonstrate my problem. I wanted a git-versioned pkg to show you what I mean. I simply used the same example as Philip did in the other thread. Normally I don't :wink: I install it with makepkg :smile:

**Comment by udeved** [comment]
I am aware of this, see referenced issue.

**Comment by oberon2007** [comment]
I still don't know how I can reset **cache_dir=** to the default now.

**Comment by udeved** [comment]
Reset works.
Check both manjaro-tools.conf

**Comment by oberon2007** [comment]
As described above. It has no effect for me.

**Comment by oberon2007** [comment]
**/etc/manjaro-tools/manjaro-tools.conf** and **~/.config/manjaro-tools/manjaro-tools.conf** are both set to:
```
cache_dir=/var/cache/manjaro-tools
```

**Comment by udeved** [comment]
Cache_dir set to my build partition:
~~~
==> PATHS:
  -> work_dir: /build/manjaro-tools/buildpkg/unstable/x86_64
  -> pkg_dir: /build/manjaro-tools/pkg/unstable/x86_64
  -> build_mirror: http://mirror.netzspielplatz.de/manjaro/packages/unstable
~~~

Cache_dir unset:
~~~
==> PATHS:
  -> work_dir: /build/manjaro-tools/buildpkg/unstable/x86_64
  -> pkg_dir: /var/cache/manjaro-tools/pkg/unstable/x86_64
  -> build_mirror: http://mirror.netzspielplatz.de/manjaro/packages/unstable
~~~

**Comment by oberon2007** [comment]
ok. it works for successful pkgs ;)
It was just for the error in the other example it continues to tell me about the other path ... 
So, this is not really a problem.
Thanks

**Comment by udeved** [comment]
No, its also works just on -q option.
