### ISSUE TITLE
DE detection

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#200]
We detect DEs with a [desktop.map] (https://github.com/manjaro/manjaro-tools/blob/devel/data/desktop.map) file.

Do bspwm, jwm have a launcher and a binary?

launcher:binary

**Comment by oberon2007** [comment]
There is a **/usr/bin/jwm** and a **/usr/bin/bspwm-session**

**Comment by udeved** [comment]
But no launchers? ie *.desktop /usr/share/xsessions?

**Comment by oberon2007** [comment]
also **usr/share/xsessions/jwm.desktop** and **/usr/share/xsessions/bspwm.desktop**

**Comment by udeved** [comment]
Ah ok, thx, I will add it to detection map file.

**Comment by oberon2007** [comment]
:+1:

**Comment by udeved** [comment]
Note, this is only useful if the profile uses a DM.

**Comment by oberon2007** [comment]
Yes, sure. **bspwm** doesn't :wink: JWM has **lxdm**
