### ISSUE TITLE
iso-filename-monsters

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#201]
Is it really necessary to add "community" to the file names like for example:
**manjaro-cinnamon-community-16.06-dev-x86_64.iso** :wink: 
Since a given edition can only be either official or community anyway depending on the profile, what use is there in having that included in the filenames at all?
Of course it makes sense with **-minimal-**
But in consequence wouldn't you have to call a cinnamon-minimal
**manjaro-cinnamon-minimal-community-16.06-dev-x86_64.iso** then?? :laughing:

**Comment by udeved** [comment]
Minimal counts as minimal, hence filename contains minimal, because the edition folder is named minimal.
Part of iso name is tied to edition(category) name

**Comment by oberon2007** [comment]
I know. But why is "community" needed in the filenames at all?

**Comment by oberon2007** [comment]
Is there a problem with commenting out https://github.com/manjaro/manjaro-tools/blob/master/lib/util-iso.sh#L197 / at least locally if I prefer that?

**Comment by udeved** [comment]
Community is in filename, because its needed.
People can't mistake it for official release, and since people don't read nowadays,
they are kind of focred to notice what iso file they use.
I don't recommend to comment it out.
