### ISSUE TITLE
signiso

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#202]
It would be great to include a separate possibility to sign ISO files for when you need to sign them after they have been built.
When using buildiso -s most of the time I miss the moment when I need to enter my passphrase and then I have to do the signing separately. Also sometimes you will want to sign older ISOs.
I use a simply script now with
``find $PWD -maxdepth 1 -name '*.iso' -exec signfile {} \;``
Could we have something like this included with the tools?

**Comment by udeved** [comment]
Nope, there is already a signfile script you can use.
No extra options for buildiso, its frozen atm, and only bugfixes.

**Comment by oberon2007** [comment]
You mean use signfile plus the full filename?

**Comment by udeved** [comment]
Right.
