### ISSUE TITLE
last commit broke sign iso ?

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#205]
Hi guys same error https://forum.manjaro.org/index.php?topic=32600.0
the folder remain accessible only for root.

**Comment by udeved** [comment]
It works for me.

**Comment by Ste74** [comment]
After your correction it working , today no .. i have also switched from normal release : no git but is equal .. the iso folder remain property of root

**Comment by udeved** [comment]
Ah, you mean after kirek's commit. 
I'll check, haven't updated git package onn my system.

**Comment by Ste74** [comment]
yes :wink:

**Comment by philmmanjaro** [comment]
@Ste74: https://github.com/manjaro/manjaro-tools/commit/1997440c299623164500255e0ea1f6faa95b14fe is the commit you claim to break it?

**Comment by Ste74** [comment]
@philmmanjaro , yes .. i use custom partition for manjaro-tools and before the sign iso option work after no because the iso folder not change permission : iso folder remain property of root and not change in my user.

**Comment by philmmanjaro** [comment]
What is your exact **packager=** name in the config of **makepkg.conf**? Also, does it work again when you just revert that patch? Simply [comment this line](https://github.com/manjaro/packages-extra/blob/master/manjaro-tools/PKGBUILD#L24) and build **manjaro-tools** for yourself ...

**Comment by Ste74** [comment]
Sorry fo delay try to create a iso with last stable (0.11.3) .. i can close now work without remove the patch i not understand what is changed before and after but possible my mistake :stuck_out_tongue_winking_eye:
