### ISSUE TITLE
Add switch to create build without exit 32 and 64 bit

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#206]
Only a little idea .. my level of scripting is 5 ,  your level 1000 :wink: well why not add a switch to build iso and build pkg whit only one switch ? When buildiso o buildpkg go to end the switch (if enable) GO TO top of script and able the other arch . Example i have creted a simple script to build both 32 and 64 , i use that to build with one command all architecture.

**Comment by udeved** [comment]
We can't do that, because buildpkg has a 3rd architecture option 'multilib'

**Comment by Ste74** [comment]
Well multilib when have to use ? If host is 32 bit and i want build a 64 bit ? Sorry for this newbie question . O when i have 64 and want enable 32 ? I never used ..

**Comment by udeved** [comment]
You need multilib if you build 32bit packages for x86_64, eg lib32-systemd, aka multilib.
You usually only need lib32 packages for steam, games, skype on x86_64.

**Comment by Ste74** [comment]
Exactly then it is what I thought thank you .. mate  :smiley:
