### ISSUE TITLE
chroot: failed to run command '': No such file or directory

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#207]
Somehow **manjaro-chroot** doesn't work anymore:
```
[phil@manjaro phil]$ manjaro-chroot root
chroot: failed to run command '': No such file or directory
[phil@manjaro phil]$ ls
root
```
maybe related to: https://github.com/manjaro/manjaro-tools/commit/1997440c299623164500255e0ea1f6faa95b14fe

**Comment by udeved** [comment]
You use it wrongly.

either 

    manjaro-chroot -a

or eg manual mounting with:

    manjaro-chroot /mnt /bin/bash

**Comment by udeved** [comment]
I think we can close this.
I can't find any wrong here.

![manjaro-chroot] (http://s32.postimg.org/z0le3cjdx/Screenshot_20160503_160602.png)
