### ISSUE TITLE
[vbox?] lightdm fails

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#208]
i3-ISO built just now with latest tools:
![lightdm_fail](https://cloud.githubusercontent.com/assets/11800714/14943916/ef3a3258-0fe5-11e6-89b0-69c101c8cea4.png)
```
==> manjaro-tools
  -> version: 0.11.5
  -> user_config: /home/bernhard/.config/manjaro-tools/manjaro-tools.conf
==> PROFILE:
  -> sets_dir_iso: /etc/manjaro-tools/iso.d
  -> buildsets: community|default|minimal|official|sonar
  -> buildset_iso: i3
  -> is_buildset: false
  -> run_dir: /home/bernhard/manjaro/manjaro-tools-iso-profiles
==> OPTIONS:
  -> arch: x86_64
  -> branch: unstable
  -> chroots_iso: /var/lib/manjaro-tools/buildiso
  -> initsys: systemd
  -> kernel: linux44
==> ARGS:
  -> clean_first: true
  -> images_only: false
  -> iso_only: false
  -> sign: false
  -> is_log: false
==> DIST SETTINGS:
  -> dist_name: Manjaro
  -> dist_release: 16.06pre3
  -> dist_codename: Daniella
==> ISO SETTINGS:
  -> iso_label: MJRO1606
  -> iso_publisher: Manjaro Linux <http://www.manjaro.org>
  -> iso_app_id: Manjaro Linux Live/Rescue CD
  -> iso_compression: xz
  -> iso_checksum: md5
  -> use_overlayfs: true
  -> iso_fs: overlayfs
==> BUILD QUEUE:
 --> Profile: [i3]
  -> work_dir: /var/lib/manjaro-tools/buildiso/i3/x86_64
  -> iso_dir: /home/bernhard/manjaro//iso/community/i3/16.06pre3/x86_64
  -> iso_file: manjaro-i3-16.06pre3-x86_64.iso
  -> displaymanager: lightdm
  -> autologin: true
  -> nonfree_xorg: true
  -> pxe_boot: true
  -> plymouth_boot: false
  -> multilib: true
  -> efi_boot_loader: grub
  -> efi_part_size: 31M
  -> hostname: manjaro-i3
  -> username: manjaro
  -> password: manjaro
  -> addgroups: video,audio,power,disk,storage,optical,network,lp,scanner,wheel
  -> start_systemd: bluetooth cronie ModemManager NetworkManager org.cups.cupsd tlp tlp-sleep
  -> start_systemd_live: manjaro-live mhwd-live pacman-init
  -> disable_systemd: pacman-init
  -> is_custom_pac_conf: fals
```

**Comment by oberon2007** [comment]
**/etc/lightdm/lightdm.conf**:
```
[LightDM]
run-directory=/run/lightdm
[Seat:*]
pam-autologin-service=lightdm-autologin
user-session=i3
session-wrapper=/etc/lightdm/Xsession
autologin-user=manjaro
autologin-user-timeout=0
```

**Comment by oberon2007** [comment]
xfce-minimal built with same setup just now works fine...

**Comment by oberon2007** [comment]
So, **lightdm.conf** is fine. The identical one on my own installed system works fine.
Attempting to launch **lightdm** from another tty gives
```
** (lightdm:1779): CRITICAL **: session_get_login1_session_id: assertion 'session != NULL' failed
```

**Comment by philmmanjaro** [comment]
Did you checked also the greeter config yet?

**Comment by oberon2007** [comment]
I'm on that track meanwhile, too, yes!
I just went through my commits since the last successful built on March 29 and am actually right now squashing another version without the mouscursor theme in the greeter config. Might be that ``cursor-theme-name = Chameleon-Pearl-Regular-0.5`` needs quotes or double quotes or maybe that xcursor name with the numbers and stuff in it is just too much :wink:

**Comment by udeved** [comment]
buildiso doesn't manipulate greeter.conf yet.

Perhaps the conf has changed, and you need to update the conf in your profiles?
greeter.conf is the only file you ideally deploy for lightdm.

**Comment by oberon2007** [comment]
Yes, that's what I'm doing. I deploy only that file. Restoring **lightdm-gtk-greeter.conf** of the last successful build didn't help. I'm now trying with the default...

**Comment by oberon2007** [comment]
So, it's the same failure with the default lightdm-gtk-greeter.conf
I have no idea where else to look.
Since the last successful build (on March 29) there have only been tiny cosmetic changes to the profile. The profile and settings I have used then and now are on branch ``i3-solarized`` if you would like to have a look. In the profile there where only [two commits](https://github.com/manjaro/manjaro-tools-iso-profiles/commits/i3-solarized/community/i3) and for the settings only [these tow](https://github.com/manjaro/desktop-settings/commits/i3-solarized/community/i3), so really nothing essential has changed...

**Comment by udeved** [comment]
Are we sure we are not hitting the vbox mystery again.
Two threads on that in forum, also involving lightdm.

**Comment by korrode** [comment]
Indeed.

Have you checked Xorg.0.log yet?
Likely it's not LightDM that's falling over, it's the Xorg server.

**Comment by udeved** [comment]
I can't see reason why its buildiso related.
No code changes for a couple of weeks.

Right, xorg.log would be nice.

**Comment by oberon2007** [comment]
![vbox](https://cloud.githubusercontent.com/assets/11800714/14959925/456507b4-1092-11e6-97ed-53d20fee272d.png)

**Comment by philmmanjaro** [comment]
Hi all, I just built a new i3-i686 image. No issues at all.

![i3](https://cloud.githubusercontent.com/assets/5050022/14961507/2c0364a2-109a-11e6-9023-1dc76122b6c1.png)

**Comment by philmmanjaro** [comment]
Another analysis told me that **r1909.6a8a408** and **0.11.5-2** can't produce bootable **x86_64** images. I try again with a **i686** build.

**Comment by oberon2007** [comment]
Oh! And I just double checked: My xfce-minimal 64bit of yesterday is broken, too - obviously I had booted the wrong ISO... :stuck_out_tongue_closed_eyes:

**Comment by oberon2007** [comment]
So the x86_64 vb-driver maybe?

**Comment by oberon2007** [comment]
This doesn't look related to the tools. Even rolling back to **0.11.4** doesn't help and that was the version my last working ISO was built with.

**Comment by philmmanjaro** [comment]
I can confirm that the **x86_64** is currently broken. Let me check my last **xfce** build. **i686** just runs fine.

**Comment by philmmanjaro** [comment]
@oberon2007: it must be something in your **i3-x86_64** profile. My [current development builds](https://sourceforge.net/projects/manjarotest/files/16.06-dev/) I had created yesterday just booted fine on my end with Virtualbox 5.0.20.

**Comment by oberon2007** [comment]
Did you look at my commits? It is so weird! I have an ISO here that was built with https://github.com/manjaro/manjaro-tools-iso-profiles/commit/cddac936711d0e293aae950df7cd7b718582a1f7 and https://github.com/manjaro/desktop-settings/commit/192d298a11d4a089956bb764fb16132bf01c7658 (on the i3-solarized branch now). As you can see, practically nothing has changed.
Also how does it make sense that the issue is only with one arch? It looks like it must be caused by a package!

**Comment by oberon2007** [comment]
The **xfce-minimal** x86_64, that I built last night at 10pm has the same issue!
What time did you build yours? Then we can check boxit, which packages where updated inbetween...

**Comment by philmmanjaro** [comment]
`823M  1. Mai 20:38 manjaro-xfce-minimal-16.06-dev-x86_64.iso` ... but I don't think it is packages related.

**Comment by oberon2007** [comment]
https://lists.manjaro.org/pipermail/manjaro-packages/Week-of-Mon-20160425/006999.html ?

**Comment by oberon2007** [comment]
I meant the x86_64 of course, but anyway ...

**Comment by oberon2007** [comment]
I'm writing a USB now.

**Comment by oberon2007** [comment]
It DOES work on hardware!

**Comment by oberon2007** [comment]
I just downgraded **virtualbox**. It was udated last night :wink: But that also doesn't help ...

**Comment by oberon2007** [comment]
Your buildlog also says
```
linux44-virtualbox-guest-modules-5.0.20-1
virtualbox-guest-utils-5.0.20-0.1
```
So they were already the newest also.

**Comment by philmmanjaro** [comment]
I just did another build after pulling some packages from upstream. That one booted just fine.

**Comment by oberon2007** [comment]
That's vey strange! I tried a new i3-image, didn't work, and just now buit an xfce one and I still have the same problem! ... ...

**Comment by korrode** [comment]
@oberon2007 
That image you posted before, there may be errors earlier than that in the /var/log/Xorg.0.log, need to see the whole thing.

**Comment by philmmanjaro** [comment]
@oberon2007: two things. Does a **i686** build work for you. Did you tried the **stable branch** yet?

**Comment by philmmanjaro** [comment]
@oberon2007: these are the [current changes](https://gist.githubusercontent.com/philmmanjaro/86db3ad71a93fc8e8e9d825220727d0a/raw/47f30b9aba22a3cdbf4aa64b386c27c92e800610/packages-160503.txt) after **16.06-pre3**. So please check if the regression was already in **pre3** you're facing now.

**Comment by philmmanjaro** [comment]
... maybe also change the kernel to a different one ...

**Comment by oberon2007** [comment]
Here's the rest of the log:
![log1](https://cloud.githubusercontent.com/assets/11800714/14977361/7b6329f0-1113-11e6-9d43-bf91b9cb6693.png)
![log2](https://cloud.githubusercontent.com/assets/11800714/14977362/7b6e8e26-1113-11e6-9245-3a22f98b8a46.png)

**Comment by oberon2007** [comment]
trying stable branch next...

**Comment by oberon2007** [comment]
i3 64bit stable - not working for me
i3 32bit unstable - not working either
I'll try another xfce-minimal now ...

**Comment by korrode** [comment]
Trying more ISO's is fine and all, but what we really need to do is diagnose the problem.

Have you checked if all vbox guest modules are loaded (lsmod) and tried to load any that aren't (modprobe)?

**Comment by oberon2007** [comment]
I need a little more help there! What exactly am I looking for?

![lsmod1](https://cloud.githubusercontent.com/assets/11800714/14980574/d3ae3350-1129-11e6-8222-f279ec90c18b.png)
![lsmod2](https://cloud.githubusercontent.com/assets/11800714/14980575/d3c77a22-1129-11e6-88c9-a4164cc1733c.png)
![lsmod3](https://cloud.githubusercontent.com/assets/11800714/14980577/d3c86cc0-1129-11e6-8d52-da128834875d.png)
![lsmod4](https://cloud.githubusercontent.com/assets/11800714/14980576/d3c856b8-1129-11e6-94b4-1bea819710a0.png)
![lsmod5](https://cloud.githubusercontent.com/assets/11800714/14980578/d3c9f4aa-1129-11e6-986e-2aeda43b9e08.png)

**Comment by korrode** [comment]
what happens if you move/delete the mhwd file in /etc/X11/xorg.conf.d/ and then try to startx?

**Comment by oberon2007** [comment]
BINGO! I end up in a working session :smiley:
Nice avatar btw!!! :laughing:

**Comment by oberon2007** [comment]
Content is this:
![xorg1](https://cloud.githubusercontent.com/assets/11800714/14982641/160396a6-1138-11e6-9422-6782aac4068b.png)

**Comment by oberon2007** [comment]
Removing ``Driver "vboxvideo"`` alone is enough!

**Comment by oberon2007** [comment]
There were some [changes](https://github.com/manjaro/mhwd/commit/7fc67cc5accaa2549ed404b7a41ba48b43c3503e) in mhwd since March 29!
Is it that?

**Comment by oberon2007** [comment]
On the other hand the file is identical on my last working ISO:
```
##
## Generated by mhwd - Manjaro Hardware Detection
##


Section "Device"
        Identifier  "Device0"
        Driver      "vboxvideo"
EndSection


Section "InputDevice"
        Identifier  "Mouse0"
        Driver      "vboxmouse"
        Option      "Device" "/dev/vboxguest"
        Option      "CorePointer" "yes"
EndSection


Section "Extensions"
        Option "Composite" "Enable"
        Option "RENDER"    "Enable"
EndSection


Section "InputClass"
        Identifier          "Keyboard Defaults"
        MatchIsKeyboard     "yes"
        Option              "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection
```

**Comment by korrode** [comment]
Can you try leaving the vboxvideo section, but get rid of the vboxmouse section, let us know if it then works.

**Comment by korrode** [comment]
If that fixes it, then line 28 to 35 has to be deleted from here and mhwd updated:
https://github.com/manjaro/mhwd-db/blob/1194411c06154029f067cf7ea61370bc799578e5/pci/graphic_drivers/virtualbox/MHWDCONFIG

**Comment by oberon2007** [comment]
Removing vboxmouse section does not help.

**Comment by korrode** [comment]
hmm ok

can you startx with vboxvideo section or the whole .conf file removed, then post the human readable parts of **glxinfo** output?

**Comment by udeved** [comment]
I'd be very cool if we had latest dkms in our repos.

I was gonna test against dkms guest modules, but it doesn't work with dkms in repos currently.

I updated my vbox install, among updates vbox guest modules, and after update, no xorg.

Will investigate logs now and update here.

**Comment by oberon2007** [comment]
![opengk](https://cloud.githubusercontent.com/assets/11800714/14989037/3dc9deac-1156-11e6-9d65-36cc0acff91b.png)

**Comment by udeved** [comment]
Fist error logged in Xorg.0.log

   (EE) Failed to load module "vboxmouse" (module does not exist, 0)

vboxvideo is loaded properly

Btw, I noticed you moved xf86-input-* in our repos.
Thing is, it looks like xf86-input-libinput may become default soon, and evdev is gonna be dropped.
May be related, and vbox makes already use of libinput.

**Comment by udeved** [comment]
vboxvideo, drm and glx are properly initialized.
dmesg is fine in that regard.

Leaves input devices somehow not working.

**Comment by udeved** [comment]
Could it be, vbox required xorg-1.188 ABI siomething?
Latest xf86-input-evdev is incompatible with xorg-1.17.

**Comment by korrode** [comment]
Your glxinfo output showing software rendering (llvmpipe) means vboxvideo is not in use by Xorg (despite being loaded in your lsmod output), so it's not just somehow an issue of the xorg.conf sections, vboxvideo is having some other failure...

**Comment by korrode** [comment]
@udeved 
Earlier oberon said:

_Removing Driver "vboxvideo" alone is enough!_

So even with vboxmouse section still in xorg.conf, X did start... so i'd think it's vboxvideo that's the issue...

**Comment by udeved** [comment]
Yes @korrode 

xorg can't find input devices, it also can't find screeen as a follow up error where it terminates.
vboxvideo is symptom, missing input device the cause I think.

**Comment by korrode** [comment]
@oberon2007 
on your ISO, does your **virtualbox-guest-utils** package version match your **linuxNN-virtualbox-guest-modules** version?

**Comment by philmmanjaro** [comment]
The **MHWDCONFIG** is from **2013.01.01** so maybe some adjustment is needed. I'll check when I'm home what can be done.

**Comment by oberon2007** [comment]
@korrode, well sort of match...:
**virtualbox-guest-utils** 5.0.18-**0.1** and **linux44-virtualbox-guest-modules** 5.0.18-**1**

**Comment by philmmanjaro** [comment]
Ok, to take out the heat. We know that the **i3 image** works with **vesa** driver just fine. 

![force-vesa](https://cloud.githubusercontent.com/assets/5050022/14992517/a15981f6-1166-11e6-88f4-e111830eb2fc.png)

Also we know that I'm able to produce working XFCE builds working with current **virtualbox MHWDCONFIG**. Also I was able to create a working **i686** image with **i3**. This rules out **lighdm**, **mhwd** and **manjaro-tools**. Now we have to look at the **virtualbox module** and **MHWDCONFIG** to find out what is broken. Since **manjaro-tools** allows us to add some files to the **mhwd-image** overlay we can add there some modified **MHWDCONFIG** file to find a proper solution for this. Deleting the config will result in using **vesa** most likely.

**Comment by oberon2007** [comment]
Yes. Boot Option vesa works for me, too.
The only difference I can think of when you build (some) images that work, while mine don't, is that I build the ISOs with host kernel **linux41**. Can that be relevant?

**Comment by philmmanjaro** [comment]
somehow **username** is empty and therefore the **lightdm.conf** is damaged. Also the **sudoers** file is damaged due that fact.

**Comment by oberon2007** [comment]
When booting with option vesa I do get a normal session.
**lightdm.conf** contains ``autologin-user=manjaro`` and **sodoers** has ``manjaro ALL=(ALL) NOPASSWD: ALL``.
Autologin and gtk-greeter work normally.

**Comment by philmmanjaro** [comment]
do you have a **/usr/share/manjaro-tools/profile.conf** on your broken image?

**Comment by udeved** [comment]
Its also happening with sddm.

**Comment by philmmanjaro** [comment]
@udeved: On my broken image the **profile.conf** was missing. However I still can't boot. I've to create a new image to get a matching **libdrm**.

```
copy_profile_conf(){
	msg2 "Copying profile.conf ..."
	[[ ! -d $1 ]] && mkdir -p $1

	cp ${profile_conf} $1

	write_profile_conf_entries $1
}
```

**profile_conf** is defined where?

**Comment by udeved** [comment]
Do you have /etc/manjaro-tools/cli-installer.conf?

The profile.conf, or cli-installer.conf is used by installers.

**Comment by udeved** [comment]
Look at util.sh -> load_profile_config()

The function is used by live service script and installer too.

**Comment by philmmanjaro** [comment]
I create a new **i3-x86_64** with latest packages to see if something has changed. This issue is weird. The last **i686** just worked ...

**Comment by oberon2007** [comment]
Just built an i3 64bit. Working fine! Thank you :smiley:

**Comment by korrode** [comment]
So, for the record, from what i can tell, our 'solution' currently is to disable the vboxvideo driver and all the benefits that come with it, and just run vesa with llvmpipe instead...

i.e. with Phil's changes to mhwd-db, glxinfo output i believe will be the same as Bernhard posted earlier - using llvmpipe, with no passthrough for host hardware 3D acceleration.

**Comment by oberon2007** [comment]
glxinfo output is the same, yes.

**Comment by philmmanjaro** [comment]
@korrode: No, it has the same support. I tested it by changing the window size of the guest system. Vesa won't change with it.

**Comment by philmmanjaro** [comment]
Here is the output of the last working **XFCE** without the **MHWDCONFIG** changes:
```
[manjaro@manjaro Desktop]$ glxinfo | grep OpenGLOpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.7, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.1
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.1
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
[manjaro@manjaro Desktop]$ cat /var/lib/mhwd/db/pci/graphic_drivers/virtualbox/M* | grep vboxvideo
	MHWD_ADD_DEVICE_SECTION "vboxvideo" "${XORGFILE}"
	echo "vboxvideo" >> "${MODULESFILE}"
	modprobe vboxvideo
```

After the modification it is still the same on the driver end. I simply simplified the config file to work better ...

**Comment by oberon2007** [comment]
![boxfetch](https://cloud.githubusercontent.com/assets/11800714/15009871/51bc8750-11e9-11e6-8364-e1197b9dcb62.png)

**Comment by korrode** [comment]
I'm going off memory, but i'm pretty sure there's missing OpenGL support... IIRC when i used to run glxinfo in virtual machines the render was different, and mention of my host's graphics adaptor (or brand at least) was there...

Try running even a basic game, or something, and see how it is.

**Comment by udeved** [comment]
I also think we only have a workaround, but not a real fix.
Will fiddle with it later today at home.

**Comment by udeved** [comment]
Well, if I get latest dkms from arch in a vbox install, and build vbox guest dkms, everything works as expected.
So something seems to be wrong with the binary guest module package and the way it is built.

**Comment by philmmanjaro** [comment]
@udeved: which xorg-server do you use in your VM? I built the xorg-drivers [as ususal](https://github.com/manjaro/packages-community/blob/8e8efe4b91428ac3ddf6e551f3ab2fea65c0448b/xorg/virtualbox/PKGBUILD) against 1.17. In [DKMS](https://github.com/manjaro/packages-extra/issues/57) there were some changes. However we can't use it yet as Arch does cos **spl/zfs** doesn't support it. What I don't understand ist, why I can use the old config just fine with my XFCE builds and others have issues with it. However it seems to be a [known issue](https://www.virtualbox.org/ticket/12746) with **x86_64**

**Comment by udeved** [comment]
Phil, I used default repo versions(so 1.17) except for dkms package, which enables alpm hooks if from arch upstream.
Next test will be with previous mhwd-db before you updated.

My test box with dkms modules has direct rendering enabled per glxinfo, but uses mesa as gl backend?

**Comment by hypnoglow** [comment]
Hello!
How do I fix this issue for my existing installation of Manjaro-i3 on VirtualBox?

**Comment by oberon2007** [comment]
The available install media should not have that issue. Which ISO did you install, @hypnoglow?

**Comment by hypnoglow** [comment]
@oberon2007 this one: **manjaro-i3-15.12-x86_64.iso** from [here](https://sourceforge.net/projects/manjarolinux/files/community/i3/2015.12/systemd/)

**Comment by oberon2007** [comment]
I don't have that ISO on my hdd any more - downloading it now :wink:
I haven't heard about any problems with that one until now - it definitely used to work without issues in a while ago. What exactly are you experiencing? Are you trying to run the live environment or is it installed in the virtualbox? So did it work previously?

**Comment by oberon2007** [comment]
**manjaro-i3-15.12-x86_64.iso** works perfectly fine for me in virtualbox.

**Comment by hypnoglow** [comment]
1) I have a virtual machine which was installed 2 months ago. After 2016-04-26 update it stopped working because of this issue. I cannot manage to fix this machine.

2) 2 days ago I tried to setup a fresh machine, so I installed that ISO - everything worked fine. After I did `pacman -Syu` and rebooted - this issue happened again.

I will try to setup another one later today.
But even if it will work, my question is, how to fix it for my 1st machine?

**Comment by oberon2007** [comment]
So that means, it boots to a black screen?
In your installed version in virtualbox try this:

- press the hostkey of your virtualbox plus F2
- login on the console
- sudo nano /etc/X11/xorg.conf.d/90-mhwd.conf
- comment out these lines:
```
#Section "Device"
#      Identifier  "Device0"
#       Driver      "vboxvideo"
#EndSection
```
- save the changes with <Ctrl>+o and <Enter> and close with <Ctrl>+x
- type ``startx``
If that works you should be able to login normally after reboot.

**Comment by hypnoglow** [comment]
So I have installed a fresh one. Again, all is fine after installation, and it brokes after system update. Same issue: black screen, lightdm fails to start, "no screens found(EE)" in `/var/log/Xorg.0.log`

Commenting lines in `90-mhwd.conf` worked for both machines, thank you. 
But I wonder why it doesn't work with clean install.

**Comment by oberon2007** [comment]
Well something seems to be wrong with the latest updated **video-virtualbox** driver...

**Comment by jacobHclarkson** [comment]
I'm having the same issue on both of my Manjaro VMs. Commenting out the necessary lines in "90-mhwd.conf" does indeed allow me to login normally, though there are some graphical foibles in the greeter and i3 bar. Hopefully this is resolved soon, workarounds make me nervous :P

**Comment by oberon2007** [comment]
Are your "graphical foibles" with the greeter maybe simply theme-related? If so that might be just solved by switching to a new gtk3.20 compatible theme like **vertex-maia**! What exactly is happening with your i3 bar? I would not know of any issues with that one... !

**Comment by philmmanjaro** [comment]
Seems it has something to do with **Virtualbox** itself. On our current **16.06-rc2** I've followed error message by loading the module `Failed to insert 'vboxvideo': Invalid argument`. Since we dropped to load it, this regression won't stop us from releasing **16.06** soon. However I'll reopen this one so we can track it further. Maybe **v5.1** might fix it by not depending on **dkms** builds anymore.

**Comment by udeved** [comment]
Please open issue for vbox to track it.
