### ISSUE TITLE
[profile] xfce-minimal doesn't boot

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#21]
After selecting your boot option you'll be presented with followed image:

![mt-xfce-minimal](https://cloud.githubusercontent.com/assets/5167332/5692993/ebca0344-990a-11e4-8889-b75ce9e59539.jpg)

After that it just hangs in plymouth.

**Comment by manjaro** [comment]
manjaro-tools 470cb9820937f7d4defdde3e3a88cce4566371e1 and manjaro-tools-iso-profiles [dd76918](https://github.com/manjaro/manjaro-tools-iso-profiles/commit/dd76918767282e98c61d07b75abd9e8271b416d6) were used

**Comment by udeved** [comment]
It could be that your profile still uses mdm, but pkglist installs lightdm.

Just set displaymanager to lightdm and rebuild. It should then add lightdm-plymouth as unit symlink

**Comment by manjaro** [comment]
Changed to lightdm and same result. Must be something else. Imo lots to do before we can replace ManjaroISO with this ...

**Comment by udeved** [comment]
Yes, I never said different.
Needs lots of testing.

**Comment by udeved** [comment]
PS: I may have screwed up the DM activation for systemd and I assumed wrong name for plymouth.

**Comment by manjaro** [comment]
Hmm, might be something else after all as latest dev-build by ManjaroISO also doesn't boot-up.

**Comment by manjaro** [comment]
Seems to be related to [systemd-firstboot](http://www.freedesktop.org/software/systemd/man/systemd-firstboot.html). Still wonder why it got activated ...

**Comment by manjaro** [comment]
After all it was machine-id once again. If not present systemd-firstboot get called, which messes everything up. Fixed with **manjaro-tools r516.859b6c8-1**
