### ISSUE TITLE
inexistent user icon

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#210]
[util-iso-image.sh](https://github.com/manjaro/manjaro-tools/blob/master/lib/util-iso-image.sh#L85) sets default user icon to **/var/lib/AccountsService/icons/majaro.png** which no package actually installs
In Xfce that doesn't seem to be a problem, but launching **mugshot** in for example i3 fails with
```
Traceback (most recent call last):
  File "/usr/bin/mugshot", line 36, in <module>
    mugshot.main()
  File "/usr/lib/python3.5/site-packages/mugshot/__init__.py", line 47, in main
    window = MugshotWindow.MugshotWindow()
  File "/usr/lib/python3.5/site-packages/mugshot_lib/Window.py", line 52, in __new__
    new_object.finish_initializing(builder)
  File "/usr/lib/python3.5/site-packages/mugshot/MugshotWindow.py", line 228, in finish_initializing
    self.init_user_details()
  File "/usr/lib/python3.5/site-packages/mugshot/MugshotWindow.py", line 259, in init_user_details
    if os.path.samefile(image, face):
  File "/usr/lib/python3.5/genericpath.py", line 90, in samefile
    s1 = os.stat(f1)
```
Should we either not define the icon there or otherwise deploy an icon?

**Comment by oberon2007** [comment]
Last line of the error was missing, sorry :wink:
```
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/AccountsService/icons/manjaro.png'
```

**Comment by philmmanjaro** [comment]
No, it installs the **user**.png file. The name of the user is here by default **manjaro**.

**Comment by oberon2007** [comment]
I recently added some [stock avatars](https://github.com/oberon2007/avatars) to [**mugshot**](https://github.com/manjaro/packages-community/blob/master/mugshot/PKGBUILD#L39)
Since no other package appears to install a **/var/lib/AccountsService/icons/manjaro.png**, how about having mugshot create a symlink to one of those avatars?

**Comment by philmmanjaro** [comment]
I've to check the code again. I think **MSM** creates those files for each user. I've to check were we mis now the **manjaro.png** file which is called that way as the user is named **manjaro**.

**Comment by oberon2007** [comment]
I see ... I definitely hasn't been there for a while. Already last year for the Deepin edition I deployed one via the profile.

**Comment by philmmanjaro** [comment]
The code develops and @udeved also copied some stuff from **manjaroiso**. Since we have now split files, I also have to check and remember in which we added it and why. Remember how many files and apps we had to change to get rid of the **BROWSER=** var.

**Comment by udeved** [comment]
Its Altlast with the accounts service image. 
I just remember it was needed, gdm perhaps?

**Comment by philmmanjaro** [comment]
Seems so, now we check if the file is there and add the line if so. Case closed.
