### ISSUE TITLE
Copying wrong pacman.conf file when creating isos

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools#211]
We copy a pacman.conf tailored for chroot builds, and we use that in the isos too. We need to copy the proper pacman.conf to the iso, or restore the default.

See this thread:
https://forum.manjaro.org/index.php?topic=33857.0

**Comment by udeved** [comment]
There should be no difference between pacman.conf from pacman package and our pacman.conf files for builds.
If there is a diff, we should just update the files, but, we don't have the stuff uncommented as the thread reports.
CacheDir is commented, and CheckSpace option is also present in both conf files.

**Comment by udeved** [comment]
Now, here is the golden washing machine question.
What edition was used to install? Was a custom pacman.conf used in the iso profile?

I am seriously thinking about removing support to add 3rd party repos to buildiso.

**Comment by Kirek** [comment]
This problem is present in the main editions, nothing to do with custom pacman.conf.
CacheDir should be commented, and CheckSpace should be uncommented.

We are overwriting the default pacman.conf https://github.com/manjaro/packages-core/blob/master/pacman/pacman.conf.x86_64 with the pacman.conf tailored for chroot builds https://github.com/manjaro/manjaro-tools/blob/master/data/pacman-multilib.conf, which is fine when creating the iso, but we don't restore the original file before squashing. So all isos end up with a wrong pacman.conf, without CheckSpace enabled.

**Comment by udeved** [comment]
Ok, so we won't copy pacman.conf in chroot-run and rely on the pacman.conf provided by pacman pkg.
This makes custom repos not possible, which is fine with me.

**Comment by philmmanjaro** [comment]
Ok, makes sense. Then we should not copy the **pacman.conf** ...

**Comment by udeved** [comment]
I confused the commit message and issue number.
https://github.com/manjaro/manjaro-tools/commit/2825dfaae4a7fd688fa4bd135655df67cf3ad9b6
