### ISSUE TITLE
Builds fail in docker.

### ISSUE THREAD

**Issue by edge226** [manjaro/manjaro-tools#212]
I'm trying to do some docker automation with Manjaro iso building, at first I had some issues with the chroot aspect but upon doing some research I found that running the container in --privileged mode resolves these issues.

Upon attempting to do a build again I was struck with another issue as shown below:

```
==> Prepare [Desktop installation] (xfce-image)
 --> overlayfs mount: [/var/lib/manjaro-tools/buildiso/xfce/x86_64/xfce-image]
mount: wrong fs type, bad option, bad superblock on overlay,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
==> ERROR: A failure occurred in make_image_custom().
    Aborting...
 --> overlayfs umount: []
```

Okay so lets see what `dmesg | tail` gives us:
`[ 8612.927652] overlayfs: filesystem on '/var/lib/manjaro-tools/buildiso/xfce/x86_64/xfce-image' not supported as upperdir`

I believe the issue has something to do with [this](https://github.com/manjaro/manjaro-tools/blob/master/lib/util-iso-overlayfs.sh#L18) function but I'm not sure how to fix it to work within the docker instance, It seems like its because upper and the resulting mount location are the same and you're thus essentially trying to mount /var/lib/manjaro-tools/buildiso/xfce/x86_64/root-image, /var/lib/manjaro-tools/buildiso/xfce/x86_64/xfce-image and /var/lib/manjaro-tools/buildiso/xfce/x86_64/work back into /var/lib/manjaro-tools/buildiso/xfce/x86_64/xfce-image.

I think this would be solved via doing something like:
```
mount_image(){
        IMAGE_ACTIVE_MOUNTS=()
	mkdir -p "${work_dir}/work"
        mkdir "${work_dir}/mnt"
	track_image -t overlay overlay -olowerdir="${work_dir}/root-image",upperdir="$1",workdir="${work_dir}/work" "${work_dir}/mnt"
}
```

This is based upon how the person does the ./entrypoint.sh script.

But then you need to change other parts of the sources to point to `"${work_dir}/mnt"` but I'm not familiar enough with the code to say any more speculation.

If you want to test the docker instance run:
`docker run --privileged -it --name manjaro-tools -v /etc/lsb-release:/etc/lsb-release orbos/manjaro:manjaro-tools`

**Comment by edge226** [comment]
I see that You've looked at this and I'm willing to work on potential solutions with you on these issues to get them resolved quickly. Can I get some responses to my feedback? Lack of feedback will cause things to move along slower.

**Comment by philmmanjaro** [comment]
@edge226: which platform is installed in docker? does it support overlayfs? If not you can still use the aufs option

**Comment by edge226** [comment]
@philmmanjaro Its an i5 2500k. x86_64
I believe it does from the info in [this](http://stackoverflow.com/questions/32510778/error-using-mount-command-within-dockerfile) post. I thought I modified the main post pointing to this but I must not have saved it. I was quite tired at the end of all the testing when I reported this.

I think I saw about the aufs option and I dont think it worked either. What is the correct flag for that?

**Comment by philmmanjaro** [comment]
It is in our **manjaro-tools.conf**. Simply uncomment it like this:

```
# experimental; use overlayfs instead of aufs
# requires minimum 4.0 kernel on the build host and on iso in profile.conf
use_overlayfs="false"
```

**Comment by edge226** [comment]
@philmmanjaro if you need i686 its pretty easy. Here are the two files used: [mkimage-manjaro.sh](https://raw.githubusercontent.com/edge226/docker/master/contrib/mkimage-manjaro.sh) and [mkimage-manjaro-pacman.conf](https://raw.githubusercontent.com/edge226/docker/master/contrib/mkimage-manjaro-pacman.conf).

I modded the arch ones to work on manjaro and shared them on the forum a few days before the SSL issue happened.

**Comment by edge226** [comment]
I think I need to build new docker images at this time. I tried to do the net profile and I get:
```
error: target not found: prebootloader
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
==> ERROR: A failure occurred in make_image_root().
    Aborting...
```

**Comment by edge226** [comment]
@philmmanjaro There are many applications for docker such as automated package building with a CI. I'm working on setting that stuff up for my OS and in a sense I already have a very good understanding of how it works due to me automating all my website builds via when markdown is pushed to the repo. But I use gitlab instead of github now.

**Comment by edge226** [comment]
New image is being pushed now.

**Comment by edge226** [comment]
Same thing happens with an updated image that was just refreshed, Does that mean I'm missing a dep for manjaro-tools or something?

**Comment by edge226** [comment]
Ah looked at the net install and removed that stuff as a test. Seems like something went wrong either on your end or on one of your mirrors.

**Comment by edge226** [comment]
```
==> Prepare [Desktop installation] (net-image)
 --> aufs mount: [/var/lib/manjaro-tools/buildiso/net/x86_64/net-image]
mount: wrong fs type, bad option, bad superblock on none,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
==> ERROR: A failure occurred in make_image_custom().
    Aborting...
```

**Comment by edge226** [comment]
@philmmanjaro You can see the rate at which it took me to update was around 10 minutes. Thats how  quick the docker turnaround time is and it can be made quicker through automation in a CI system.
