### ISSUE TITLE
I switch kinda doesn't work

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#216]
If I check **mkchrootpkg** I find this line: `[[ ! -f PKGBUILD && -z "${install_pkgs[*]}" ]] && die 'This must be run in a directory containing a PKGBUILD.'`. So we have to recheck that option on how we want to use it. I suggest it like this:

`buildpkg -p kpmcore-dev -i`

This will say to **buildpkg** that I want to build it, install it to the chroot and then move it to the cache dir. We can use some like `pacman -U kpmcore-dev-<VERSION>*z -r <PATH/TO/CHROOT>`.

**Comment by udeved** [comment]
I think ou confuse -i with -n flag.

~~~
    -n                 Install and run namcap check
~~~

as opposed to

~~~
-i <pkg>           Install a package into the working copy of the chroot
~~~

**Comment by philmmanjaro** [comment]
@udeved: at the current situation you can't install any package using the -i switch into the chroot. the -n switch will install the package to your host.

**Comment by udeved** [comment]
Strange that. It used to work, and had no complaints before.
Must have been introduced lately I think.

**Comment by udeved** [comment]
buildpkg -p kpmcore-dev -i

> This will say to buildpkg that I want to build it, install it to the chroot and then move it to the cache dir.

If you want to use it like that, what is the difference to -n switch then?
Do we misunderstand each other? You want -i for -n ? We got exactly what you ask on -n.

-i <pkg_name.pkg.tar.xz> should be the current way to use it.

**Comment by philmmanjaro** [comment]
Ok, with `buildpkg -p kpmcore-dev -i` I want to build the package and install it after in the chroot, or is it already possible and I missed it?

**Comment by udeved** [comment]
Yes, what you want is -n switch already if I understood you correctly.

**Comment by philmmanjaro** [comment]
ok, what does the -n switch? Build the package and install it on the host, or build the package and install it into the chroot? If it is the later, it is fine for me, then the -i switch needs to be checked to install a package manually into the chroot. If it is the first, then why do we check the package on the host?

**Comment by udeved** [comment]
Both -n and -i will install in the chroot.
We do not have an option to install on the host, because I always planned that this will get automated.
We wouldn't need an option to install on host, which is a build server.

We really need some direction here, and a prospect.
I think a build server should be absolutely  manjaro's next goal.

**Comment by philmmanjaro** [comment]
@udeved: yes, we are working on a plan to get a build server. So if -n is also installing into the chroot. I'm fine with it. However we should check the -i switch once again. I didn't get a package installed with it lately. Maybe I miss some ...

**Comment by udeved** [comment]
How did you use the -i switch?

I have only tested it once, after kirek requested this feature to install depend packages in chroot.

Should be something like

buildpkg -p foo -i /path/to/bar.pkg.tar.xz

**Comment by udeved** [comment]
- [ ] solved
