### ISSUE TITLE
when generateing iso profiles on my system system over heats and shutts down

### ISSUE THREAD

**Issue by mhussaincov** [manjaro/manjaro-tools#217]
as the subject states when I start building the iso, my pc starts over heating and turns off.
could the process priority of manjaro-tools be changed or something?
currently i'm unable to build an iso.
or would it be possable to spesiphy  how many cpu threads the manjaro tools processes  can use?
I have 2 cpu's in my system,
my specks are,
toshiba l670 4gb ram 465 gb disk space
2 cpu
building on sonar gnu-linux branch is unstable.
thanks for reading.

**Comment by udeved** [comment]
Hi there,

I think your have cooling issues on your system.
Lowering process priority will only slow down the death of cpu if you don't act.

**Comment by mhussaincov** [comment]
strange,
when I run vms, there are no problems?
what about the option to set how many cpu the process will use?
curious,

Majid HUssain

**Comment by udeved** [comment]
I close this, since it is definitely a problem with your system.
