### ISSUE TITLE
default login shell

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#219]
If we want to default to zsh, should the login_shell setting apply for all profiles, or should it be profile based.
manjaro-tools.conf vs profile.conf

**Comment by philmmanjaro** [comment]
Make it profile based and put **bash** by default. Every switch to a new shell needs to be tested first.

**Comment by udeved** [comment]
Its why I had it in manjaro-tools.conf initially.
I think we can close this now. :)
