### ISSUE TITLE
[buildiso] deletes image-folders on re-run

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#22]
Seems clears workdir on re-run. Within ManjaroISO we have the option to remove for example xfce-image and call buildiso once again. As root-image was already created it skips that step and continues with xfce-image. This feature is missing within manjaro-tools. Therefore we have to add an option to disable workdir clearing.

**Comment by udeved** [comment]
Its already done, use -c switch.
It will disable cleaning.

**Comment by manjaro** [comment]
Yes, I found it now.

**Comment by aadityabagga** [comment]
I had asked for this feature too (ie, reusing previous images).

It worked for me when I changed something in overlay and rebuilt, but I didnt try with others.
