### ISSUE TITLE
Default session in GDM

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#220]
We are currently don't set the default session in GDM.

A global default session can be defined in `/etc/gdm/custom.conf`:

```
[daemon]
DefaultSession=mate.desktop
```

That said, GDM stores each user's last session in `/var/lib/AccountsService/users/$USER`:

```
[User]
Language=en_US.utf8
XSession=mate
SystemAccount=false
```

I do not know of a way to configure GDM to ignore the last session used and force using a desired default with each new login. A work-around would be to run a PostSession script to always modify `/var/lib/AccountsService/users/$USER`.

In /etc/gdm/PostSession/Default, try adding something like this:

`sed -i 's|^XSession=.*|XSession=mate|' /var/lib/AccountsService/users/$USER`

**Comment by philmmanjaro** [comment]
In **Thus** we use this for GDM:

```
        # Setup gdm
        if os.path.exists("{0}/usr/bin/gdm".format(DEST_DIR)):
            default_desktop_environment = self.find_desktop_environment()
            os.system("echo \"[User]\" > {0}/var/lib/AccountsService/users/{1}".format(DEST_DIR, username))
            if default_desktop_environment is not None:
                os.system("echo \"XSession={0}\" >> \
                {1}/var/lib/AccountsService/users/{2}".format(default_desktop_environment.desktop_file, DEST_DIR, username))
                os.system("echo \"Icon=\" >> {0}/var/lib/AccountsService/users/{1}".format(DEST_DIR, username))
            self.desktop_manager = 'gdm'
```

**Comment by philmmanjaro** [comment]
Hmm, seems we have it after all ...

```
# $1: chroot
# $2: user
configure_accountsservice(){
	msg2 "Configuring accountsservice ..."
	local path=$1/var/lib/AccountsService/users
	if [ -d "${path}" ] ; then
		echo "[User]" > ${path}/$2
		echo "XSession=${default_desktop_file}" >> ${path}/$2
		if [[ -f "/var/lib/AccountsService/icons/$2.png" ]];then
			echo "Icon=/var/lib/AccountsService/icons/$2.png" >> ${path}/$2
		fi
	fi
}
```

**Comment by udeved** [comment]
Yep, that's the way we configure gdm.
Does it still need to attention?

**Comment by philmmanjaro** [comment]
Hmm, I don't think so. If I'll reopen it.
