### ISSUE TITLE
user-repos.conf

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#221]
We likely need some check.
If we use it in the "HOME, we got to make sure 3rd party packages get disabled in the profile.

So if file not exists, we need checking for 3rd party packages and disable them.
Otherwise the build fails, if 3rd party packages are defined in pkglist.

- [x] We also need to filter out local repos.
- [x] Or we move user-repos.conf back in the profile.

**Comment by philmmanjaro** [comment]
Move it back to the profile folder. They store it there anyway. Also checking for packages being 3rd-party might be hard to do. However the option would be to parse all packages given with the standard pacman.conf file. If we don't find them, then they must be 3rd-party. However, without those the build might also fail, so doing the extra hassle makes no sense at all ...

**Comment by udeved** [comment]
Yep.
