### ISSUE TITLE
-s option broken

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#223]
with **manjaro-tools-pkg-git r2037.1d22459** option -s has stopped working for me. It just does nothing.

**Comment by udeved** [comment]
I'll be reenabled before 0.12 release.

**Comment by oberon2007** [comment]
So which commit can I still use to have the function available? Or should I use release **0.11.7** now?

**Comment by udeved** [comment]
You should always use point release if you plan to publish.
git version is always development version, and not necessarily stable.
Reason you shouldn't have too many git packages in the repos, and you point releases too if available.

**Comment by philmmanjaro** [comment]
Please use stable branch. Current release is **v0.11.7**.
