### ISSUE TITLE
[buildpkg] pkgver problem with updated git and pkgs with an epoch

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#224]
This is not solved for me with latest commits about moving packages.
I have set ``cache_dir=/home/bernhard/manjaro/``
When pkgver is being updated during  build, buildpkg is at the end still looking for the old pkgver and ``mv`` fails:
```
==> Finished making: lemonpanel 0.20.r176.09c153d-1 (Tue Jun  7 13:02:18 UTC 2016)
  -> Moving [lemonpanel-0.20.r172.1cb03c6-1-any.pkg.tar.xz] -> [/home/bernhard/manjaro//pkg/unstable/x86_64]
mv: cannot stat '/home/bernhard/manjaro/pkg/lemonpanel-0.20.r172.1cb03c6-1-any.pkg.tar.xz': No such file or directory
  -> Archiving log files lemonpanel-0.20.r172.1cb03c6-1-x86_64.log.tar.xz ...
  -> Cleaning log files ...
==> Finished building [lemonpanel]
```
There is also a problem handling pkgver with an epoch:
```
==> Finished making: lxsession 1:0.5.2-1.1 (Tue Jun  7 13:01:07 UTC 2016)
  -> Moving [lxsession-1:0.5.2-1.1-x86_64.pkg.tar.xz] -> [/home/bernhard/manjaro//pkg/unstable/x86_64]
  -> Archiving log files lxsession-1:0.5.2-1.1-x86_64.log.tar.xz ...
tar (child): Cannot connect to lxsession-1: resolve failed
tar: Child returned status 128
tar: Error is not recoverable: exiting now
  -> Cleaning log files ...
chown: cannot access 'lxsession-1:0.5.2-1.1-x86_64.log.tar.xz': No such file or directory
==> Finished building [lxsession]
```

**Comment by udeved** [comment]
Do you have PKGDEST enabled?

**Comment by udeved** [comment]
You need to set precise git version, buildpkg does not update pkgver like makepkg does.

does -w switch help?

**Comment by oberon2007** [comment]
I have set ``PKGDEST=/home/bernhard/manjaro/pkg`` in **.makepkg.conf**

**Comment by oberon2007** [comment]
No difference with -w option.
So looks like I still have to run ``makepkg -o`` before running buildpkg for git pkgs...

**Comment by udeved** [comment]
Has always been this way, but why do you build git packages for the repo?

**Comment by oberon2007** [comment]
Obviously because we have quite some packages with a pkgver() in our repos ;) :laughing: 

extra:
```
./manjaro-cli-installer/PKGBUILD:pkgver() {
./manjaro-base-skel/PKGBUILD:pkgver() {
./sonar-isolinux/PKGBUILD:pkgver() {
./calamares-exp/PKGBUILD:pkgver() {
./calamares-dev/PKGBUILD:pkgver() {
./manjaro-efi-shell/PKGBUILD:pkgver() {
./partitionmanager-dev/PKGBUILD:pkgver() {
./xorg/xf86-video-intel/PKGBUILD:pkgver() {
./manjaro-live/PKGBUILD:pkgver() {
./manjaro-isolinux/PKGBUILD:pkgver() {
./sonar-desktop-settings/PKGBUILD:pkgver() {
./kpmcore-dev/PKGBUILD:pkgver() {
```

multilib:
```
./lib32-qtcurve/PKGBUILD:pkgver() {
./lib32-rtmpdump/PKGBUILD:pkgver() {

```

community:
```
community]$ grep -re "pkgver()" .
./ttf-dejavu-sans-mono-powerline/PKGBUILD:pkgver() {
./alternating-layouts/PKGBUILD:pkgver() {
./manjaro-openbox-settings/PKGBUILD:pkgver() {
./obkey/PKGBUILD:pkgver() {
./entrance-git-manjaro/PKGBUILD:pkgver() {
./skippy-xd/PKGBUILD:pkgver() {
./gnome-wallpapers/PKGBUILD:pkgver() {
./menda-lxqt-panel/PKGBUILD:pkgver() {
./forecasts/PKGBUILD:pkgver() {
./pantheon-wallpaper/PKGBUILD:pkgver() {
./python-i3/PKGBUILD:pkgver() {
./tintin-alteraeon/PKGBUILD:pkgver() {
./gnome-shell-extension-openweather/PKGBUILD:pkgver() {
./equate-git/PKGBUILD:pkgver() {
./pcaudiolib/PKGBUILD:pkgver() {
./manjaro-xfce-settings/PKGBUILD:pkgver() {
./evopop-icon-theme/PKGBUILD:pkgver() {
./liri-browser/PKGBUILD:pkgver() {
./sutils/PKGBUILD:pkgver() {
./blather/PKGBUILD:pkgver() {
./sxhkd/PKGBUILD:pkgver() {
./gnome-shell-extension-mediaplayer/PKGBUILD:pkgver() {
./xwinfo/PKGBUILD:pkgver() {
./xlogin/PKGBUILD:pkgver() {
./limepanel/PKGBUILD:pkgver() {
./emacs-speechd-el/PKGBUILD:pkgver() {
./numix-reborn-themes/PKGBUILD:pkgver() {
./libcpuid/PKGBUILD:pkgver() {
./manjaro-kde-settings/PKGBUILD:pkgver() {
./lemonbar-xft-clicky/PKGBUILD:pkgver() {
./desktop-settings/PKGBUILD:pkgver() {
./manjaro-budgie-settings-extra/PKGBUILD:pkgver() {
./networkmanager-dmenu/PKGBUILD:pkgver() {
./xdo/PKGBUILD:pkgver() {
./manjaro-lxqt-settings/PKGBUILD:pkgver() {
./espeak/PKGBUILD:pkgver() {
./manjaro-browser-settings/PKGBUILD:pkgver() {
./console-solarized/PKGBUILD:pkgver() {
./xtitle/PKGBUILD:pkgver() {
./wmutils/PKGBUILD:pkgver() {
./lemonpanel/src/lemonpanel/PKGBUILD:pkgver() {
./lemonpanel/PKGBUILD:pkgver() {
./ephoto-git/PKGBUILD:pkgver() {
./ecrire-git/PKGBUILD:pkgver() {
./mygtkmenui/PKGBUILD:pkgver() {
./budgie-wallpapers/PKGBUILD:pkgver() {
./pdf2img-c/PKGBUILD:pkgver() {
./i3/i3exit/PKGBUILD:pkgver() {
./i3/i3status-manjaro/PKGBUILD:pkgver() {
./i3/i3-theme-dust/PKGBUILD:pkgver() {
./i3/i3-theme-dark/PKGBUILD:pkgver() {
./i3/i3-gaps/PKGBUILD:pkgver() {
```

**Comment by philmmanjaro** [comment]
It works without issues if you use the default settings. Therefore I never changed it ...

**Comment by oberon2007** [comment]
"Has always been this way" is not a very valid argument I think. The problem is not only with git versions but also with dated packages and as I said, there is also a problem with epoch packages. I think it should be fixed. Or if setting a custom pkgdir doesn't work, maybe this option should just be removed? I don't think the issue is to be closed.

**Comment by udeved** [comment]
May I suggest you think about changing to point releases for your packages?
The moving cannot work if you don't set the vcs commit properly in PKGBUILD.
Again, auto version does not work in chroot.

**Comment by philmmanjaro** [comment]
Let me cut in here. Autoversion works in chroot if you use the default settings and no custom setting to save the packages, for example in your homedir. I'm building calamares-dev with a git-versioning without issues using pkgbuild. The problem only occurs if you have it personalized. However the PKGBUILD itself won't get updated during this process, which is also not needed in my opinion as the result of the final package is there. So this issue only exist if your target is located in your home-dir.

**Comment by udeved** [comment]
I believe the problem comes if you don't set a proper commit in the PKGBUILD.
The pkgver does not get updated, not matter there is a pkgver() function.

Example:

pkgver=123.abcdef

latest commit 124.fedcba

Resulting package foo-124.fedcba.pkg.tar.xz

BUT, pkgver is still at 123.abcdef.

Moving will fail, because the PKGBUILD is sourced to get version.

**Comment by philmmanjaro** [comment]
On my end I never had that issue. All was moved just fine to **/var/cache/manjaro-tools**. We should simply copy the PKGBUILD back from `/var/lib/manjaro-tools/buildpkg/$branch/$arch/$user/srcdest/` to `/var/lib/manjaro-tools/buildpkg/$branch/$arch/$user/srcdest_host/` and source the proper file if needed. This should solve the issue.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/8983d1956bea71b5e47c83a7ba7294ab670c9747

This should fix it.

Btw, we mount the src dir with PKGBUILD readonly.

**Comment by philmmanjaro** [comment]
adding **--holdver** makes no sense in git releases. This should get reverted. Chroot also alters the PKGBUILD as same as done with **makepkg**. We only have to copy the proper file. However the file is found in `/var/lib/manjaro-tools/buildpkg/$branch/$arch$/user/build/$pkgname/src/` and should be copied pack to the host srcdir.

**Comment by udeved** [comment]
What you want is no good.

man makepkg

~~~
--holdver
           When using VCS sources (PKGBUILD(5)) any currently checked out source will not
           be updated to the latest revision.
~~~

So the commit defined in pkgver will be used.
Arch also have this set.

**Comment by philmmanjaro** [comment]
We want to have the latest revision and **auto-versioning** working. If I create **calamares-dev** I don't want to define which git-snapshot should be used. So I call the **PKGBUILD** with **buildpkg** which just fine updates the given **PKGBUILD** in the build-dir to latest git-snapshot. Package gets build, packaged and moved to **/var/cache/manjaro-tools/pkg/$branch" just fine. What doesn't happen is that the updated **PKGBUILD** get copied back to the host srcdir.

Bernhard claims to have an issue when he is using his home dir path, which I don't. Then it seems the package can't be moved properly, cos a wrong **PKGBUILD** get sourced to get the version.

So holding back a version is here not an option. Therefore find a way that it will work properly as created. Same as it is possible with **makepkg** directly.

**Comment by udeved** [comment]
Give it a try with the changes, works absolutely fine.
