### ISSUE TITLE
Please keep the team informed!

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#225]
@udeved 
It's not helpful for the packaging team, that [functions just disappear](https://github.com/manjaro/manjaro-tools/issues/223) and [variables change](https://github.com/manjaro/manjaro-tools/commit/870b0d62715c0b2bfa97fe51b430f2706c8b4ca7) without notice while I think the team is working with git snapshots of the tools.
We just have to realize suddenly that packages are built against stable branch instead of unstable because our config is suddenly not compatible any more and that the packages are not signed because the -s switch has been deactivated. 
It would be helpful if you announce changes like that for everybody to keep pace and for us to kow what's going on. Maybe everybody should use the latest release tag while things are being worked on, or tell us which commit is the one we can temporarily rely on!
Thank you.

**Comment by udeved** [comment]
Changes will be announced with the release announcement of the point release.
I will not and can not inform on every commit.

**Comment by oberon2007** [comment]
Well more often than once latest git commits were needed for bug-fixes and my understanding was that our production tools are always the latest available git.
You like to work on your own and decide what procedure works best for you but you tend to forget that you are not alone but supposed to work with a team here.
This defensive attitude and the habit of slamming the door by immediately closing every github issue that you take as a criticism is also not very helpful for a feeling of teambuilding btw ...

**Comment by udeved** [comment]
Nope oberon, you simply have wrong assumptions, repos versions, point releases are never latest vcs commits, never. 
Developers decide when to release a point release deemed stable or unstable whatever that is based on a certain commit.
You made a tempest in the tea pot, this is just normal that things in git versions can break or change, they are no point releases.

**Comment by udeved** [comment]
Btw, but it is a good example why you should generally avoid vcs package versions in the repos, if a point release is available.
The manjaro-tools are just script packages, but vcs packages that are truly compiled may cause breakage.
Its really no good idea to have vcs packages in repos if avoidable.

**Comment by oberon2007** [comment]
Just a while ago you kept telling people that they should always use the latest git version and whenever they had an issue with the tools your first assumption was that they had not updated the tools as they should.
So now it's using the latest point release, ok. But there has to be some kind of proper communication! Please understand that you are not on your own here!

**Comment by udeved** [comment]
Right, we are nearing manjaro-tools-1.0 at some point, so tools have stabilized and its the proper way now to use repo version for productive means.
I always said, to put this correctly, that if you use git version, it its your responsibility to keep your tools up to date, this includes manjaro-tools.conf.

**Comment by philmmanjaro** [comment]
@oberon2007: please use the stable branch for production. **master** branch is free for all changes and development. At the current state **master** is no use for production releases. Therefore we have the stable branch which get updated on regular bases including fixes added to **master** branch. Current release for given iso-profiles is **v0.11.7**. End of discussion. Thx.

**Comment by philmmanjaro** [comment]
All relevant information and changes to each release can been found [here](https://github.com/manjaro/manjaro-tools/releases).

**Comment by oberon2007** [comment]
yes. makes perfect sense. thank you :+1:

**Comment by udeved** [comment]
You could still use the git PKGBUILD, but set the branch to stable-12x
