### ISSUE TITLE
log archiver has issues with epoch

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#226]
when using **epoch** our log archiver seems to have some issue:

```
==> Finished making: plymouth 1:0.8.8-2 (Sat Jun 11 08:19:40 UTC 2016)
  -> Moving [plymouth-1:0.8.8-2-x86_64.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/x86_64]
  -> Archiving log files plymouth-1:0.8.8-2-x86_64.log.tar.xz ...
tar (child): Cannot connect to plymouth-1: resolve failed
tar: Child returned status 128
tar: Error is not recoverable: exiting now
  -> Cleaning log files ...
chown: cannot access 'plymouth-1:0.8.8-2-x86_64.log.tar.xz': No such file or directory
==> Finished building [plymouth]
 --> Time make_pkg: 1.17 minutes
```

**Comment by philmmanjaro** [comment]
tested with **v0.11.901**

**Comment by udeved** [comment]
The new moving uses get_full_version() in util-pkg.
This function came from devtools(?)

**Comment by philmmanjaro** [comment]
It is not about the moving rather how we archive our logs.

**Comment by udeved** [comment]
Well, the archiving uses the full pkg name, and this is determined at moving, before tar.
It gets an array of log files to tar.
Need to check.

**Comment by udeved** [comment]
~~~
if [[ -z $LOGDEST ]];then
		local name=${pkgbase:-$pkgname} ver logsrc archive
		ver=$(get_full_version "$name")
		archive=$name-$ver-${target_arch}
		logsrc=$(find . -maxdepth 1 -name "$archive*.log")
		archive_logs "$archive" "${logsrc[@]}"
	fi
~~~

get_full_version should return version string, with epoch.

**Comment by philmmanjaro** [comment]
Correct, but the archiver is searching for a folder with the epoch, which is wrong. So we have to find a solution for epoch in regard of archiving. Moving is fine.

**Comment by udeved** [comment]
The solution is by fixing get_full_version() my guess.

**Comment by philmmanjaro** [comment]
The error here is `tar (child): Cannot connect to plymouth-1: resolve failed`. Tar should look for folder **plymouth** and not for **plymouth-1:**.

**Comment by udeved** [comment]
Hmm, perhaps some missing double quotes, since the epoch bit works obviously.

**Comment by udeved** [comment]
I have no idea why tar adds a back slash for each array element.
~~~
--> src: plymouth-1:0.8.8-1-x86_64-build.log
plymouth-1:0.8.8-1-x86_64-package.log
plymouth-1:0.8.8-1-x86_64-prepare.log
tar: plymouth-1\:0.8.8-1-x86_64-build.log\nplymouth-1\:0.8.8-1-x86_64-package.log\nplymouth-1\:0.8.8-1-x86_64-prepare.log: Cannot stat: No such file or directory
~~~

The src array is fine, the tar command somehow uses a back slash where it should not be.
