### ISSUE TITLE
vmlinuz* might expand to more than one file

### ISSUE THREAD

**Issue by ActualizeInMaterial** [manjaro/manjaro-tools#227]
This line: https://github.com/manjaro/manjaro-tools/blob/800ec6798addbe0b850aca52172556b5a7a2df31/lib/util-iso.sh#L308
seems to expect `vmlinuz*` to expand to only one filename, but when more than one kernel is installed you get something like this:

```bash
+ cp /var/lib/manjaro-tools/buildiso/xfce/x86_64/root-image/boot/vmlinuz-4.4-x86_64 /var/lib/manjaro-tools/buildiso/xfce/x86_64/root-image/boot/vmlinuz-linux-git /var/lib/manjaro-tools/buildiso/xfce/x86_64/iso/manjaro/boot/x86_64/manjaro
cp: target '/var/lib/manjaro-tools/buildiso/xfce/x86_64/iso/manjaro/boot/x86_64/manjaro' is not a directory
```

**Comment by udeved** [comment]
There is always only one kernel installed in chroot for the iso.

**Comment by ActualizeInMaterial** [comment]
Possibly untrue if (1) file `/etc/manjaro-tools/manjaro-tools.conf` contains line:
`kernel="linux-git"`
as opposed to line:
`#kernel="linux44"`
apparently because the `linux-git` package doesn't satisfy `linux>=3.4` thus causing another kernel to be installed.

```
resolving dependencies...
:: There are 11 providers available for linux>=3.4:
:: Repository core
   1) linux310  2) linux312  3) linux314  4) linux316  5) linux318  6) linux319
   7) linux41  8) linux42  9) linux44  10) linux45  11) linux46

Enter a number (default=1): 
```

```
...
               linux-api-headers(4.5.5-1)  linux310(3.10.101-2)
               llvm-libs(3.8.0-1)  lz4(131-1)  lzo(2.09-1)
...
               linux-git(4.7.rc3.r0.g5edb564-1)  logrotate(3.9.2-1)
...
```

Or, another way is: (2) user manually adds another kernel in Packages-Root instead of Packages-Xfce. (which was my case above, but I now fixed the `linux-git` package to provide `linux>=3.4` so, I've worked around the issue)

**Comment by philmmanjaro** [comment]
Well, normally we only support packages provided by our repositories and not from 3rd-party repositories.

**Comment by ActualizeInMaterial** [comment]
It makes sense, indeed; not arguing.

Cheers.
