### ISSUE TITLE
eval_build_list

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#228]
Just installed **manjaro-tools-iso 0.11.903**
running buildiso gives this error:
``/usr/bin/buildiso: line 178: eval_build_list: command not found``

**Comment by philmmanjaro** [comment]
Seems to be a regression introduced with **0.11.903**. The version before was fine. Thx for reporting it. If you don't have the old version in cache, please try 902 by using the tarball and following git-commit: a3ac87df321e99e5bbf15ed0a3c5ebc430eba9cd

**Comment by oberon2007** [comment]
I'm running commit **e0dfc44** (stable-0.12.x) now. That one seems fine. Can't really check the package - the PKGBUILD seems to be updated only locally on your branch ;)

**Comment by philmmanjaro** [comment]
This is not a bug. You have to adopt to the changes made to **manjaro-tools.conf**. See also 570ac4750d0b80540ee43bfb3b0bc3cc485f1f1b

```
-# default pkg buildset; name without .set extension
-# buildset_pkg=default
+# default pkg build list; name without .list extension
+# build_list_pkg=default
 
 ################ buildiso ################
 
 # the name of the profiles directory
 # profile_repo='manjaro-tools-iso-profiles'
 
-# default iso buildset; name without .set extension
-# buildset_iso=default
+# default iso build list; name without .list extension
+# build_list_iso=default
```

**Comment by oberon2007** [comment]
I see. ok. Thanks ;)

**Comment by philmmanjaro** [comment]
**v0.11.903** is followed commit: e0dfc44134514ec75828e464a7a42253b3f015db

**Comment by oberon2007** [comment]
To me it looks like you applied some patch in your PKGBUILD then, because as I said, my git build works fine while the repo package doesn't. Also the config should not make any difference because those lines are commented anyway! ;)

**Comment by philmmanjaro** [comment]
Ok, please compare the content of both package versions. So we find the culeprint on the matter. Back home I've to check what might went wrong.

**Comment by philmmanjaro** [comment]
@oberon2007: check if revision 2 works. If yes, please upload that verison and close this issue.

**Comment by oberon2007** [comment]
Well it looks like my manjaro-tools-base was not at the same version. The package is fine apparently after reinstalling the whole set. Sorry for that.

**Comment by philmmanjaro** [comment]
No problem.
