### ISSUE TITLE
check why logfiles sometimes not get cleaned properly

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#229]
In some occasions the logfiles won't get cleaned properly:

```
==> Leaving fakeroot environment.
==> Finished making: snapd 2.0.8.1-1 (Wed Jun 15 06:20:41 UTC 2016)
  -> Moving [snapd-2.0.8.1-1-x86_64.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/x86_64]
  -> Archiving log files [snapd-2.0.8.1-1-x86_64.log.tar.xz] ...
  -> Cleaning log files ...
chown: cannot access 'snapd-2.0.8.1-1-x86_64.log.tar.xz': No such file or directory
==> Finished building [snapd]
```

**Comment by oberon2007** [comment]
Seems like the tools are looking for the log in the wrong place. They are not found while they are infact present in ``$log_dir``

**Comment by oberon2007** [comment]
If I'm not mistaken the logs used to reside in ``$startdir/$pkgname`` while now they are placed in ``$log_dir`` ?

**Comment by udeved** [comment]
logs will are stored depending if $LOGDEST is set in makepkg.conf.
If unset, log files stay in the dir of the PKGBUILD, if set, logs go to $LOGDEST.
Archiving log files will create the archive in /var/log/manjaro-tools by default, but log files are only deleted, if $LOGDET is not set.

**Comment by oberon2007** [comment]
So I think in the case @philmmanjaro describes, I think the log files in the PKGBUILD dir are deleted and afterwards we still try to chown it :wink:

**Comment by udeved** [comment]
Wrong, chown will be executed on the created archive only.

**Comment by oberon2007** [comment]
In that case it's looking in the wrong place:
``chown: cannot access 'manjaro-i3-solarized-settings-20160614-1-x86_64.log.tar.xz': No such file or directory``
while
```
ls /var/log/manjaro-tools/
manjaro-i3-solarized-settings-20160614-1-x86_64.log.tar.xz
```

**Comment by oberon2007** [comment]
Or if I understand correctly when you say
> If unset, log files stay in the dir of the PKGBUILD, if set, logs go to $LOGDEST.
there is something not right on that end. Because when I leave log_dir at the default, right now logs are in fact removed in the PKGBUILD dir and written to log_dir

**Comment by udeved** [comment]
github seems to autoclose.

**Comment by oberon2007** [comment]
yes, when you use "fix" or "close" in the commit message :wink:

**Comment by oberon2007** [comment]
It's working for me in any case. So I think it can be closed. Thanks! :)

**Comment by oberon2007** [comment]
Oh well maybe not.
When I set log_dir to a custom destination now, I get
```
  -> Archiving log files [manjaro-i3-solarized-settings-20160614-1-x86_64.log.tar.xz] ...
tar: Removing leading `/' from member names
tar (child): /home/bernhard/manjaro/logs/manjaro-i3-solarized-settings-20160614-1-x86_64.log.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: /home/bernhard/manjaro/logs/manjaro-i3-solarized-settings-20160614-1-x86_64.log.tar.xz: Cannot write: Broken pipe
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by oberon2007** [comment]
I see. $log_dir does not get created. Maybe that's intentional.

**Comment by udeved** [comment]
Just let me fix it later, I know the problem.

**Comment by oberon2007** [comment]
:+1:

**Comment by philmmanjaro** [comment]
The problem is still there ...

```
==> Finished making: linux316 3.16.36-1 (Fri Jun 17 21:01:57 UTC 2016)
  -> Moving [linux316-3.16.36-1-i686.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/i686]
  -> Moving [linux316-headers-3.16.36-1-i686.pkg.tar.xz] -> [/var/cache/manjaro-tools/pkg/unstable/i686]
  -> Archiving log files [linux316-3.16.36-1-i686.log.tar.xz] ...
tar (child): /var/log/manjaro-tools/linux316-3.16.36-1-i686.log.tar.xz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: /var/log/manjaro-tools/linux316-3.16.36-1-i686.log.tar.xz: Wrote only 4096 of 10240 bytes
tar: Child returned status 2
tar: Error is not recoverable: exiting now
  -> Cleaning log files ...
```

**Comment by udeved** [comment]
I am really tempted to remove this archiving, which is kind if useless if you ask me.
We got to cover two cases, with and without makepkg vars, and we don't have a central location where PKGBUILDs are stored, so to implement something similar to how we handle iso profiles.

**Comment by udeved** [comment]
I would also like to ask to please not publish a new release unless a bug is 100% fixed.

**Comment by udeved** [comment]
Please provide more detail @philmmanjaro 

For example if you set any makepkg.conf vars, and the /tmp/manjaro-tools/archives.list would also be nice.

**Comment by philmmanjaro** [comment]
Well, do we create the folder `/var/log/manjaro-tools/`. Currently it doesn't exist, so that is why it creates an error.
