### ISSUE TITLE
Fix error handling

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#230]
The error handling introduced with https://github.com/manjaro/manjaro-tools/commit/52ce7f86befcdce48dfea0e42539ac954971d840 creates issues. See also [my efforts](https://github.com/manjaro/manjaro-tools/compare/0.12.0...master) to fix it, as I found following error:

```
[phil@manjaro manjaro-tools-iso-profiles]$ buildiso -p kde-minimal -a i686 -qv
/usr/bin/buildiso: line 200: trap_exit: command not found
```

Master will quit now with:

```
[phil@manjaro manjaro-tools-iso-profiles]$ buildiso -p kde-minimal -qv
==> ERROR: An unknown error has occurred. Exiting...
```

**Comment by udeved** [comment]
I get clean build in 0.12.2 branch.
Wasn't sure about the state of master, since merge conflicts I didn't pull master and branched out.

**Comment by philmmanjaro** [comment]
Ok, I pulled you changes after removing my changes. Currently testing it. Seems to be fine.
