### ISSUE TITLE
Buildpkg leave a broken link in the pkg folder

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#233]
Hi @artoo , today i have build a pkg and used manjaro-tools 0.12.2 : is intentional leave broken link in the pkg folder ? 
![schermata del 2016-06-25 18-24-03](https://cloud.githubusercontent.com/assets/11218234/16357828/13a375f4-3b02-11e6-872e-cef9dc3c68f1.png)

**Comment by udeved** [comment]
Ah, you have PKGDEST set, and makepkg creates a symlink to the moved package.
I can make it so to remove the symlink.

**Comment by philmmanjaro** [comment]
pls test **manjaro-tools-pkg-0.12.2-2** from unstable branch.

**Comment by Ste74** [comment]
@philmmanjaro , @udeved . Now all is ok i can close :+1:
