### ISSUE TITLE
buildpkg -i ?

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#234]
Is this feature not available or am I doing somthing wrong?
man buildpkg says
```
-i PKG Install a package into the working copy of the chroot.
```
but
```
buildpkg -i linux-rt-manjaro-4.6.3_rt5-1-x86_64.pkg.tar.xz
[sudo] password for bernhard: 
 --> Loading compiler settings: x86_64
==> Updating chroot for [unstable] (x86_64)...
:: Synchronizing package databases...
 core is up to date
 extra                                                           1904.0 KiB   213K/s 00:09 [#####################################################] 100%
 community                                                          3.8 MiB   203K/s 00:19 [#####################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
 --> Time chroot_init: 0.53 minutes
==> ERROR: manjaro-system is not a valid package or build list!
```
I'm using **manjaro-tools-pkg 0.12.2-2**

**Comment by philmmanjaro** [comment]
The **i-switch** is for a package to be installed before you create another one. So you have to add also the package you want to build next. I think you want to have the **n-switch** for installing the package after you have built it. I know, it is a little confusing. Check also this: https://github.com/manjaro/manjaro-tools/issues/216

**Comment by oberon2007** [comment]
Ah. Exactly. I didn't get the syntax right, yes! :wink:
