### ISSUE TITLE
makepkg work fine , buildpkg no whit ruby-bundle (?)

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#235]
Hi guys .. i have modified this theme for manjaro : https://github.com/manjaro/packages-community/commit/66436e2c289670d238f038fdc071d50d844cf4e5 and no problem with makepkg : 
https://gist.github.com/Ste74/a75484c1f8381c13832b73809535294a ( i have blocked ..but the build was fine ) 
this whit buildpkg
https://gist.github.com/Ste74/ac63e745dc0992dd57c7859d4db58889 also blocked but you see the difference .
When start build i see difference for ruby-gem : in buildpkg it seems not work

**Comment by udeved** [comment]
Ibelive you have a depend missing in your PKGBUILD, something canberra which is installed on your system, hence makepkg works, buildpkg doesn't in chroot.

**Comment by philmmanjaro** [comment]
Add **libcanberra** as build dependency and also check following [issue](https://bugs.archlinux.org/task/23655).

**Comment by Ste74** [comment]
Added .. work .. now wait the rendering ... (15') :wink: 
always forget to read better the terminal :smile:

**Comment by udeved** [comment]
No problem Ste, I think you do fine job and nobody knows everything. :)

**Comment by philmmanjaro** [comment]
Steve, no issues mate. If you have an issue with **buildpkg** most likely you forgot a dependency. It is always good on errors to create a clean chroot. Using a chroot also gives us the option to reproduce your problem, as we all use the same installed packages on a fresh start. If you however use **makepkg** it depends on your local package installation which might create issues you can't track. So if you build for our repo, please always use **buildpkg** for it.

**Comment by Ste74** [comment]
Yep always use this way :wink:

**Comment by udeved** [comment]
What Phil was gonna say, is that you hit with the issue the reason why a chroot is needed. It will always produce errors if makedepends are missing, unlike makepkg. ;)
