### ISSUE TITLE
switch to OSDN for iso hosting

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#236]
This looks good, it doesn't state that a project needs to start the shell server manually like on SF.
It seems to be available if a project is hosted there.

https://en.osdn.jp/docs/ShellServer

**Comment by philmmanjaro** [comment]
I created a project called **manjaro**. Will create another one called **manjaro-community**.

**Comment by philmmanjaro** [comment]
Seems you can only upload with **sftp**. You have **ssh** for **homepage** management. The structure however is totally different. With **sf.net** you have [more options](https://sourceforge.net/p/forge/documentation/File Management/) to manage your files. Using rsync there is no shell server needed.  **sshpass** can be used if you use a bash script to upload your files without a password request. If not used, the password gets asked to type in. Since OSDN doesn't support **rsync upload** yet, I see no option to follow up this further ...

**Comment by udeved** [comment]
ah, ok.

Yes, SF is ok, but, folder creation is ugly with rsync as workaround to ssh shell, which is available, but you need to start it manually, it  lasts iirc 1 hour.
Can you also delete projects on SF? There are too many projects with manjaro hosting iso on SF.

**Comment by philmmanjaro** [comment]
No, I can only delete projects which I own. Which is [manjarolinux](https://sourceforge.net/projects/manjarolinux/), [manjarodev](https://sourceforge.net/projects/manjarodev/) and [manjarotest](https://sourceforge.net/projects/manjarotest/).

**Comment by udeved** [comment]
I also have 3 basically play projects on SF with manjaro in name. But how/where can I delete it on SF?

**Comment by philmmanjaro** [comment]
Regarding the **shell**. You need it only to get the file structure done. That I do mostly in front with the webservices directly on SF.net as I can hide the folder for 3 days. Then I modify my release script and use that for uploading:

```
#!/bin/sh
user=johndoe
project=foo
path=bar/1.0
files=foobar-1.0*iso
pwfile=./passwd
sshpass -f $pwfile rsync -vP  --progress -e ssh $files $user,$project@frs.sourceforge.net:/home/frs/project/$project/$path
```

**Comment by udeved** [comment]
deployiso does the same but with ssh keys instead of pwd files, and creates eventually missing folders with a switch with rsync.

**Comment by philmmanjaro** [comment]
Ok, so in which case the **shell** is needed then? Regarding deletion of a project, you have to talk to a [staff member](https://sourceforge.net/p/forge/documentation/How%20to%20Remove%20a%20Project/).

**Comment by udeved** [comment]
No, current state does missing subfolders with rsync on switch, but each subfolder one rsync call.
Ideally, we create folders with shell, and the rsync the files or folder.
There is no way without shell to check for folder existence.

~~~
create_subtree(){
	msg2 "Create (%s) ..." "${edition}/$1/${dist_release}"
	rsync ${rsync_args[*]} /dev/null ${sf_url}/${edition}/
	rsync ${rsync_args[*]} /dev/null ${sf_url}/${edition}/$1/
	rsync ${rsync_args[*]} /dev/null ${sf_url}/${edition}/$1/${dist_release}/
	msg2 "Done"
	show_elapsed_time "${FUNCNAME}" "${timer_start}"
}
~~~

ugly, and on switch, pretty static.

**Comment by udeved** [comment]
The is the unused code, if there was a permanent shell access.

~~~
create_subtree_ssh(){
	local tree=${remote_target}/${remote_project}/${remote_dir}
        ssh !${remote_user}@${shell_url} [[ ! -d $tree ]] && mkdir -pv $tree
}
~~~

**Comment by udeved** [comment]
Would it be better to spilt the deployment in a separate package that depends on ruby?

**Comment by philmmanjaro** [comment]
You mean **deployiso**? Regarding Sado's email you were CCed in?

 https://osdn.jp/docs/FileRelease_Guide
 https://osdn.jp/projects/osdn-codes/wiki/APIGuide
 https://osdn.jp/projects/osdn-codes/wiki/CommandLineInterface

Let us test it first how it works. Maybe we are on to something here. If we need some, Sado told me that the development team will implement it.

**Comment by udeved** [comment]
I have added a ruby-osdn-cli package.

https://github.com/manjaro/packages-extra/tree/master/ruby-osdn-cli

**Comment by udeved** [comment]
buildlist:

pkg.list.d/osdn.list

```
ruby-ffi
ruby-ethon
ruby-typhoeus
ruby-hashie
ruby-json
ruby-osdn-client
ruby-osdn-cli
```

**Comment by udeved** [comment]
https://osdn.jp/projects/deployment-test/

This is my testing and evaluation account.

**Comment by udeved** [comment]
Tested ruby gem packages

- [x] x86_64
- [ ] i686

~~~
$ osdn help
/usr/bin/osdn [global-options] <command> [command-options] [args]
/usr/bin/osdn help <command>
Global Options:
  -h --help      Show help message. use 'help <command>' for specific command. 
  -v --verbose   Increase log level (multiple)
  -q --quiet     Decrease log level (multiple)
Avaiable Commands:
  help
  login          Login and save access token.
  package        Manipulate frs packages of project
  release        Manipulate frs releases of project
  relfile        Manipulate frs files of project
  frs_mkdirs     Make directory tree for current project release
  frs_upload     Upload local file tree and create package/release implicitly.
  ping           Test API request.
  vars           Get/set request environment variable.
~~~

**Comment by philmmanjaro** [comment]
Can this tool resume the upload if for example the connection breaks down?

**Comment by udeved** [comment]
Haven't found info on that.
I tested a bit yesterday osdn-cli.

It has its downside, but I read on osdn, that they also offer ssh and rsync, which I would prefer.
osdn-cli seems to be pretty new tool, and perhaps not feature complete.
I missed bandwidth control.
I also find the osdn login command not so nice, because I need to manually enter a generated token, no idea how to automatically get this token yet.
But, the login token expires after 24 hours, which is nice.

We would also need to come up with different server directory structure. The osdn can't handle more than two levels depth of directories.
