### ISSUE TITLE
[buildiso] with "custom" local repo : the config (for AUR packages) is still here in the live

### ISSUE THREAD

**Issue by Salamandar** [manjaro/manjaro-tools#237]
I added a local repo to add some custom packages. I start the live iso I created, and the repo is still in pacman.conf (and, of course, pacman doesn't find it) :
![capture du 2016-07-10 18-22-21](https://cloud.githubusercontent.com/assets/6552989/16714694/41cbbc8c-46cb-11e6-8f98-6ccc6fcfc42d.png)

**Comment by udeved** [comment]
local repos are intentionally not supported.

**Comment by Salamandar** [comment]
Well, I read the wiki : https://wiki.manjaro.org/index.php?title=Buildiso_with_AUR_packages:_Using_buildpkg
I may have missunderstood something then.

**Comment by Salamandar** [comment]
Oh, got it. I have to add the custom repo to MY /etc/pacman.conf ? Not manjaro-tools/pacman.conf ?
If that's the case, okay, but I don't like it : if I have to build a custom iso, I shouldn't have to modify my system settings ;)

**Comment by udeved** [comment]
You need your custom repo to be accessible online.
buildiso does not accept repos in the local filesystem.

**Comment by Salamandar** [comment]
Well that works fine when I want to add terminix-git to the custom iso.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/README.md

Not sure what you say, but /etc/pacman.conf is not the place to add a repo for iso building.

**Comment by Salamandar** [comment]
Okay, then I need a small explanation :)

I added in /usr/share/manjaro-tools/pacman-multilib.conf :

    [local-repo]
    SigLevel = Optional TrustAll
    Server = file:///home/felix/manjaro-tools/pkg/stable/$arch

So I can install the locally-built packages in my iso. Is that not the intended way ?

**Comment by udeved** [comment]
No, you need to upload your repo.

    Server = file://

This is not supported, it needs to be http://
