### ISSUE TITLE
option to create torrent

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#238]
move torrent creation from deployiso to buildiso

**Comment by philmmanjaro** [comment]
Does this make sense to do so? I thought http seed should be part of our torrents. How should that **buildiso** know?

**Comment by udeved** [comment]
Well, from code pov, it would make sense.
I removed torrent from deployiso, because it duplicates code.
Since rsync syncs directories, the initsys and arch is only relevant to iso file name.
But rsync doesn't care for filenames.
So it would be better, if torrents could be created after build process.
Its perhaps also in Strits's interest, he would get the torrent files that deployiso uploads?

**Comment by udeved** [comment]
Oh. its easy to make buildiso know the webseed url from manjaro-tools.conf ;)

**Comment by udeved** [comment]
The last commit makes deployiso generate the SF project to use.
official goes to manjaro, community and minimal to manjaro-community.
