### ISSUE TITLE
[deployiso] connect() doesn't add project

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#239]
SF login fails with authentication error:
``oberon2007,@frs.sourceforge.net's password:``
I guess the comma between username and @ should not be there?
**manjaro-tools-iso-git r2122.c9bf20d**

**Comment by oberon2007** [comment]
Or, maybe it's not a superfluous comma, but the projectname is missing. Should it be ``oberon2007,manjarolinux-community@shell.sourceforge.net``?

**Comment by udeved** [comment]
Please post output of

    deployiso -p $profile -qv

**Comment by oberon2007** [comment]
project appears to be empty:
```
$ deployiso -p deepin -qv
==> manjaro-tools
  -> version: 0.12.2
  -> user_config: /home/bernhard/.config/manjaro-tools/manjaro-tools.conf
  -> log_dir: /home/bernhard/manjaro/logs
==> PROFILE:
  -> list_dir_iso: /etc/manjaro-tools/iso.list.d
  -> build_lists: community|default|minimal|official|sonar
  -> build_list_iso: deepin
  -> is_build_list: false
==> OPTIONS:
  -> limit: 100 kB/s
  -> dist_release: current
==> ARGS:
  -> update: false
  -> release: false
  -> verbose: true
  -> rsync_args: -aP --progress -e ssh -n -v --stats --bwlimit=100
==> REMOTE:
  -> account: oberon2007
  -> host: sourceforge.net
==> UPLOAD QUEUE:
 --> Profile: [deepin]
  -> project: 
  -> src_dir: /home/bernhard/manjaro//iso/iso/current/deepin
  -> target_dir: current/deepin
```

**Comment by udeved** [comment]
clean your iso cache dir. Delete it, recreate with buildiso -q and try again.

find gets confused, you still have old cache tree I guess.

**Comment by udeved** [comment]
It should look like this:

~~~
==> UPLOAD QUEUE:
 --> Profile: [i3]
  -> project: manjarolinux-community
  -> src_dir: /var/build/manjaro-tools/iso/community/current/i3
  -> target_dir: current/i3
~~~

**Comment by oberon2007** [comment]
Yes. That was the reason.

**Comment by oberon2007** [comment]
I just moved everything out of **$cache_dir/iso/community** except for the newly created **current** dir and now it works as intended.

**Comment by udeved** [comment]
We now have "release containers" that host the built profiles, I had proposed it some months ago already.
Its simply most efficient on SF, and two projects solve some difficulty to create a deeper level tree.

**Comment by oberon2007** [comment]
yes. looking good now! :)

**Comment by philmmanjaro** [comment]
If needed simply create the new project and add me as admin plus others as needed.

**Comment by oberon2007** [comment]
https://forum.manjaro.org/t/sf-download-locations/5690/33
https://sourceforge.net/projects/manjarolinux-community/
:)

**Comment by udeved** [comment]
It'd still be helpful, if I had access to both accounts via webinterface too.

**Comment by oberon2007** [comment]
I've enabled 'admin' for you on the community account. Does that work?

**Comment by udeved** [comment]
I don't have add buttons, no. I just checked.

What we do with the community folder that is currently on official project account?

**Comment by oberon2007** [comment]
![](http://imgur.com/TY3CIGMl.png)
I can't check any more boxes. Maybe try again! I have turned 'admin' off and on again just now.
In any case you can create directories with **filezilla** and it's even a lot more convenient because you can enter whole paths with parent dirs.
