### ISSUE TITLE
[util-iso] gen_iso_fn() should source actual branch

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#240]
When building with the ``-c`` switch ISOs will end up with a wrong branch in the filename if it is not explicitly passed with the build command and when it's different from $target_branch set in manjaro-tools.conf
So when for example you build ``-b testing -x`` while your default target_branch is unstable and then later you do ``-zc`` (without adding -b testing once more) you will end up with an ISO labelled "unstable" while in fact it is "testing".
Maybe the safest solution would be to source **chroots_dir/etc/pacman-mirrors.conf** for the actual branch?

**Comment by udeved** [comment]
I don't see how this is a bug.
You decide to run buildiso twice, build in two steps.

**Comment by oberon2007** [comment]
It's maybe not a bug. I just think it would be good to rule out file names with the wrong branch :)
Also I thought it would be easy to have the actual branch read from chroot_dir, but maybe that's different from the coder's POV.

**Comment by udeved** [comment]
Not gonna happen, there is nothing broken.
If you build in two steps, its your responsibility to use proper args.

**Comment by udeved** [comment]
The easiest way to make sure is to set target_branch in manjaro-tools.conf.

**Comment by oberon2007** [comment]
I can deal with it personally, no problem.

**Comment by udeved** [comment]
I mean, there is absolutely nothing broken or needs to be fixed.
source for branch may even create problems. branch is an input arg.
