### ISSUE TITLE
Secure Boot systems require signed Systemd-Boot

### ISSUE THREAD

**Issue by mirh** [manjaro/manjaro-tools#242]
When I boot latest Manjaro iso I get a 
`Secure Boot Violation: Invalid signature detected. Check Secure Boot Policy in Setup` error. 
On the other hand if I replace .\EFI\boot\bootx64.efi contained in last 16.06 iso, with that of 15.12 it works. 

People at systemd [haven't](https://github.com/systemd/systemd/commits/master/src/boot) touched relevant code, nor it seems arch [packages](https://archive.archlinux.org/packages/s/systemd/) contains any different boot images. 

So I can't understand where the previous EFI exe (signed by Microsoft itself) came from.

**Comment by udeved** [comment]
Systemd issue if any, systemd provides the efi file.

**Comment by mirh** [comment]
As I said, I checked systemd binaries, and the image is still the same. 
I can't understand where you pulled 15.12 one from.

**Comment by udeved** [comment]
As I said, there have been no code changes, but systemd got several arch bumps.

**Comment by mirh** [comment]
Systemd-boot didn't receive any special bump. 
And aside of that, I'm telling you 15.12 one doesn't even match the one they provide themselves (in usr\lib\systemd\boot\efi\systemd-bootx64.efi)

**Comment by udeved** [comment]
I have no idea what you mean, can you please finally be specific?
 What edition did you install from?

There have been no code changes regarding boot mechnism on iso from 15.12 to 16.06, same code.

**Comment by mirh** [comment]
Ok it seems bootx64 in ISO isn't exactly the same bootx64 systemd-boot talks about. 
It's instead the linux foundation [preloader](http://blog.hansenpartnership.com/linux-foundation-secure-boot-system-released/) (at least this was included in 15.12). 

16.06 is probably instead using a [newer version](http://git.kernel.org/cgit/linux/kernel/git/jejb/efitools.git/log/) (albeit I must have been to dumb to notice it in the code). 
Not a manjaro bug then. Thanks for the time.
