### ISSUE TITLE
[buildpkg] feature request: install multiple pkgs with -i switch

### ISSUE THREAD

**Issue by oberon2007** [manjaro/manjaro-tools#243]
Currently
```
buildpkg -p <pkg> -i <depend1> <depend2>
```
will only install the first package.
It would be very helpful to be able to install more than one dependency like that to the chroot.

**Comment by udeved** [comment]
Use case?

**Comment by oberon2007** [comment]
virtualbox-modules -i /home/bernhard/manjaro/pkg/unstable/x86_64/virtualbox-guest-dkms-5.1.2-0.1-x86_64.pkg.tar.xz /home/bernhard/manjaro/pkg/unstable/x86_64/virtualbox-host-dkms-5.1.2-0.1-x86_64.pkg.tar.xz

**Comment by udeved** [comment]
Whats the point?

**Comment by oberon2007** [comment]
virtualbox-{host/guest}-dkms built from source just now, so the extramodules can be built before the new virtualbox version arrives from upstream

**Comment by oberon2007** [comment]
We have to compile them anyway for our overlay **virtualbox-guest-utils** pkgs. So I have them offline already

**Comment by udeved** [comment]
Why don't you simply use -n flag?

**Comment by oberon2007** [comment]
Well then it will install everything in virtualbox pkgbase... Not a big problem, ok. But also, it occurs that you forget, and then recompiling everythig again wastes a lot of time, just to apply the -n switch :wink:

**Comment by oberon2007** [comment]
what's the -l option? I don't see that in man buildpkg!

**Comment by udeved** [comment]
Typo, -i

**Comment by oberon2007** [comment]
I don't need to install a chain of pkgs, just two dependencies! Like it is now I have to run buildpkg twice and have it fail the first time ...

**Comment by udeved** [comment]
Use a build list.

I am really against dirty compilation against packages not in the repos.
It doesn't matter, if I were to enable accepting more than one packages on -i, it will accept any number, because it will be an array of packages.

**Comment by oberon2007** [comment]
ok. I see.

**Comment by oberon2007** [comment]
understood, yes! :+1:
