### ISSUE TITLE
[buildpkg] read group settings from /etc/group file instead of assuming

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#248]
I get this:

```
==> Updating chroot for [unstable] (x86_64)...
==> ERROR: chroot '/var/lib/manjaro-tools/buildpkg/unstable/x86_64/phil' is not at version 0.13.0. Please rebuild.
==> ERROR: Aborting...
[phil@manjaro extra]$ buildpkg -p calamares-dev -c
 --> Loading compiler settings: x86_64
chown: invalid group: 'phil:phil'
```
You have to read the group settings and not assume they are set as suggested. Some still use the old setup like **phil:users**.

**Comment by udeved** [comment]
Urgs, simple fix would be to chown the folder or let it be recreated after deletion..

**Comment by udeved** [comment]
I don't know if manjaro-tools should do user and group management.

All install media have user:user settings, so best to create a phil group and add user phil and delete all folders manjaro-tools creates.

**Comment by philmmanjaro** [comment]
I don't expect **manjaro-tools** to do user management. I expect however, that it doesn't assume some which is not existing. We should read-out the user and group and use the proper settings.

**Comment by udeved** [comment]
I am against reading /etc/group.

The problem is caused by our switch away from users default group. 
This is a one time issue, a group creation will do, and all install media don't use users group.

**Comment by philmmanjaro** [comment]
Well, you can use the given variables then:
```
[phil@manjaro extra]$ echo $USER:$GROUPS
phil:100
```

**Comment by udeved** [comment]
But why not do this in manjaro-system-ng?

Detect if group exists with getent and if not create the group and add matching user to it?
This is not a manjaro-tools problem, its system wide.
Why should I fix it here, if it is of general use for systems that still use the old default group?

**Comment by philmmanjaro** [comment]
Well, you should not force somebody to change a group. It makes more work as use. Please fix the code to read out the given values instead. Sure it makes sense not to use the **users** group, however others might use some different like **private** or such. We simply should not assume that the user will use the same group named as the user. Simple like that.

**Comment by udeved** [comment]
But you did, or whoever decided to drop users group.
I reacted to that decision, so don't complain I follow manjaro decisions.

**Comment by philmmanjaro** [comment]
It is simple. With your current code you assume that everybody uses for the user the same name also for the group. This might not be always. So it is a must to read the current config out and not assume some which might not be. That is why the system wide values $USER and $GROUPS exist. It is an issue with **manjaro-tools**.

**Comment by udeved** [comment]
Even simpler, we should have provided a upgrade addition to manjaro-system when the group was droped. This is crazy you blame me for adopting "upstream" changes.

**Comment by philmmanjaro** [comment]
I don't blame you. However you assume that some exists which is not. It is not set that a user uses the same name as the user name. It might be **users** or even some other group. We simply have to read the settings and not set some which leads to an error. Nothing more.

Example - Set folder rights of current user to his primary group:

`sudo chown -R :$GROUPS /media/FOLDER`

**Comment by philmmanjaro** [comment]
Another way would be this: `id --group $(whoami)`

**Comment by udeved** [comment]
I assume a system that is installed from install media.
Its the other way round, the users group was dropped, and manjaro-tools was one consumer of this group, there could be others. 
You are asking me to fix this on app level, when this is a system problem, when the user group was dropped and nobody took care to add some upgrade to ease transition.

**Comment by udeved** [comment]
Perhaps sonra have problems because they are still users member on their system?

**Comment by philmmanjaro** [comment]
It is not about dropping the **users** group at all. The group name simply might differ from the user name. I recommend to read the given settings instead of assuming some. On my case the group **phil** simply don't exist. It doesn't matter why. With the **chown** command you orginally want to change the rights to the **user** and its **primary group**. So please use either `chown $USER:$GROUPS` and if not possible by setting the user first when `$USER` reflects to **root** it would be `chown ${OWNER}:$(id --group ${OWNER})`.

**Comment by udeved** [comment]
yes, and group phil should have been created when the group users was dropped as default group for **any** user. Now the default user group is group "username", like on ubuntu for example.
Don't you understand that this needs adressing system wide, not app specific?

**Comment by udeved** [comment]
For example @oberon2007  has his manjaro-tools configured to use $home for package cache, so either we leave group "oberon" or we add a "developer" group and manjaro-tools will user this group.
