### ISSUE TITLE
lxqt and vertex-maia-theme-dark

### ISSUE THREAD

**Issue by Esclapion** [manjaro/manjaro-tools#249]
1) please add lxqt to the list at line 66 of  /lib/util-iso-image.sh. After, it works.

2) when installed in VBox, /etc/environment is empty. Where can I do the same change for lxqt ?

**Comment by philmmanjaro** [comment]
Be more precise what you mean with **/etc/environment**. If it is regarding theming, **lxqt** need still some work to get it working.

**Comment by udeved** [comment]
We don't do theme and stuff any longer in buildiso.
It has been moved to livecd repo.

**Comment by philmmanjaro** [comment]
We [still do](https://github.com/manjaro/manjaro-tools/tree/stable-0.12.x) in our **0.12.x series**, as the installers are not yet adopted to configure it. Therefore the modification will be done in the **desktop-image** rather than in the **live-session-image**.

**Comment by udeved** [comment]
Then don't forget to port it over in livecd.

**Comment by philmmanjaro** [comment]
Well, for now it should be moved back into libs of **manjaro-tools** until we decide how to approach this.

**Comment by udeved** [comment]
We need to talk anyway about point releases you do without coordinating with me.
We constantly make one step forward, and two steps back, and I will not go along with this.

**Comment by philmmanjaro** [comment]
Currently I'm using **0.12.x series** for Manjaro 16.08 as I found some regression in our new **0.13** release. I'm more relating on the **Calamares** release schedule. Currently I've no time to review the code. I see the effort to make a netinstaller version using **CAL**. However I don't see what is still missing and what is on your todo list for **0.13**. Best would be to discuss it via chat or Skype or whatever medium might suit you.

**Comment by udeved** [comment]
Ok, lets say 19.00 or 20.00 tonight on manjaro-dev irc if you have time.
We can also do it tomorrow if it suits better.
Regarding CAL, this is where I have no clue about schedules, hence I proposed forking calamares.
I switched already to working in a fork so I get upstream changes.

**Comment by philmmanjaro** [comment]
CAL has always a Friday release and is announced in our [upstream group](https://groups.google.com/forum/m/#!forum/calamares-dev). I try to release a new package either on Friday or Saturday each week.

**Comment by udeved** [comment]
So when are we gonna chat? Today fine with you?
I think you will agree with me once we talked and i outlined my plans more detailed.

**Comment by philmmanjaro** [comment]
In regard of CAL all patches are included, except this one: https://github.com/udeved/calamares-manjaro/commit/e98dbb1bce2165eeb4e2f8e6568665fe861b1537 **mt** and **manjaro-live** are both on the latest git version with given point releases. So I don't know the current status of given packages in **unstable** branch, on how they work nicely together. Do we already have a sample ISO out there with given new code?

**Comment by Esclapion** [comment]
(sorry, I haven't get the notifications of answer)

> Be more precise what you mean with /etc/environment. If it is regarding theming, lxqt need still some work to get it working.

It's regarding theming, I try to use the official theme in Lxqt.

If I add lxqt to the line mentioned, it works perfect on the live CD. /etc/environment contains:

```
QT_QPA_PLATFORMTHEME=qt5ct
QT_STYLE_OVERRIDE=gtk2
LANG=fr_FR.UTF-8

```

If I install the system in VBox,the theme is bad:

![mmmdz7a](https://cloud.githubusercontent.com/assets/3512979/17643038/d2fa194a-615d-11e6-97e9-54c4522c80fb.png)

If I look in /etc/environment, it only contains:

`LANG=fr_FR.UTF-8`

**Comment by udeved** [comment]
livecd packages in unstable already configure live session, what buildiso did formerly.
So nothing changed, only the target install will not be configured yet.

**Comment by philmmanjaro** [comment]
A fix would be easy. For **0.12.x** series it needs to be fixed within **mt** and with **0.13.x** series within **livecd-utils**. @Esclapion: did you already test it locally on your running version of **mt**? I think changing the line from `cinnamon*|deepin*|gnome|i3|lxde|mate|netbook|openbox|pantheon|xfce*)` to `cinnamon*|deepin*|gnome|i3|lxde|mate|netbook|openbox|pantheon|xfce*|lxqt)` might fix it. For **unstable** branch some work has to be done to CAL to make it work.

**Comment by Esclapion** [comment]
I tried the 0.13, but i have to change also other things (_get-project_ added, etc...), i prefer to stay xith 0.12 now.

I'm not sure to undrestand. As host, I'm also under lxqt and a modification of /etc/environment works fine.

I will have a look in livecd-utils, thanks.

**Comment by udeved** [comment]
CAL is next week the plan, to add config similar to livecd, and the release of updated mt 0.13.x.
Besides that, I almost finished updating progress bar for chrootcfg, didn't have much time this week.

**Comment by udeved** [comment]
@Esclapion 

>  get-project added

What do you mean by that?

**Comment by Esclapion** [comment]
I only installed the mt of unstable to tryh, and i got an error on that.

**Comment by udeved** [comment]
What error? Could you be please more precise?

I still don't know what you meant by "get-project added".

**Comment by Esclapion** [comment]
I can't reproduce this problem now... But also with manjaro-tools-iso 0.13, if I install in VBox, the theme is bad.

**Comment by philmmanjaro** [comment]
@Esclapion: we have to clarify two things here. In **unstable** things may break, as we use this branch as our testing bed. The given **mt** might not work as expected yet, as parts of configuration moved or changed. For now it is good to use the **testing** branch and its given packages. As already requested by you, please edit [line66](https://github.com/manjaro/manjaro-tools/blob/stable-0.12.x/lib/util-iso-image.sh#L66) in such a way it may work. I assume [adding](https://github.com/manjaro/manjaro-tools/issues/249#issuecomment-239617996) **lxqt** should do the trick. In regard of **0.13.x** series, there is still work do be done. You can join our discussion at `freenode.net:#manjaro-dev` at 19:00 CEST today.

**Comment by udeved** [comment]
The "problem" with lxqt atm, the theme engine is not yet finished, and we use stupid gtk themes on  qt based DE.

**Comment by Esclapion** [comment]
Yes, it was only for a try, absolutely not a criticism.

Else, as I said, editing line 66 does the trick in live, but not when installed, in vbox or real.
