### ISSUE TITLE
[branch] install-media defaults to stable branch

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#25]
Sure we use branches on creating our images, but is it wanted to default on stable rather than the branch we build our install-media on? We might call this after **root-image** creation:

<pre>cp "${PKGDATADIR}/pacman-mirrors-${branch}.conf" "${work_dir}/root-image/etc/pacman-mirrors.conf"</pre>

Otherwise we can add another switch if other options are wanted ...

**Comment by manjaro** [comment]
We might to edit **mirrorlist** also:
<pre>sed -i -e "s|stable|${branch}|g"  "${work_dir}/root-image/etc/pacman.d/mirrorlist"</pre>

**Comment by udeved** [comment]
We have several options for branch stuff.
I just commented out this stuff due to the umounting error, to reduce error sources.

**Comment by udeved** [comment]
I will activate branch setting again.
Its in mkchroot, last line, we just need to trigger chroot-run again, after basestrap properly terminated this wild processes from dbus.

**Comment by udeved** [comment]
Commit https://github.com/manjaro/manjaro-tools/commit/882627ffaf0f29f16fe506329abe4717e95593f0

should reactivate branch setting.

What locale do we want for images?

**Comment by manjaro** [comment]
None, as we generate them on bootup depending on your locale selection in isolinux menu by pressing **F2**. See also **set_locale** and **locale-gen** in **livecd** script. Else our images would gain size.

**Comment by udeved** [comment]
The fix should be fine then, as it runs locale-gen with only commented entires.
Ie no locales generated.

**Comment by manjaro** [comment]
Will check it later and close the issue when it is solved. I might recreate my **dev-build** with **3.19rc4** tomorrow.

**Comment by udeved** [comment]
I close it for now.
We can reopen if required.
