### ISSUE TITLE
buildpkg: fails to build with i686 from x86_64

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools#250]
Throws a `sudo: main: unable to allocate memory`. 
It compiles fine with x86_64.
Using **devtools** everything is fine.

Logs (with espeak and liblouis):
[failed-i686-builds.txt](https://github.com/manjaro/manjaro-tools/files/441119/failed-i686-builds.txt)

https://lists.manjaro.org/pipermail/manjaro-dev/Week-of-Mon-20160822/001400.html

I had the same issue back then when @oberon2007 had problems when building firefox-kde for i686, thought later he had another problems, see log: https://github.com/manjaro/packages-community/issues/212#issuecomment-238034007

**Comment by udeved** [comment]
~~~
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "dbus-openrc"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: dbus-openrc 1.10.10-1 (Sun Aug 28 13:59:51 UTC 2016)
  -> Moving [dbus-openrc-1.10.10-1-i686.pkg.tar.xz] -> [/var/build/manjaro-tools/pkg/unstable/i686]
~~~

Can't confirm. Just build dbus i686 on x86_64

**Comment by udeved** [comment]
Would it be reasonable to assume something is wrong with sudo i686 package?

**Comment by udeved** [comment]
~~~
cat > "$copydir/etc/sudoers.d/builduser-pacman" <<EOF
Defaults env_keep += "HOME"
builduser ALL = NOPASSWD: /usr/bin/pacman
EOF
	chmod 440 "$copydir/etc/sudoers.d/builduser-pacman"
~~~

That's the relevant part in mkchrootpkg, which is almost upstream arch.

**Comment by udeved** [comment]
Very strange that, but I think the sudo msg is raised by mkchrootpkg, something can't use the suders group created in chroot is my guess.

**Comment by oberon2007** [comment]
similar here, while strange that in my case it only happened with **linux47**, not with other kernels.
https://bugs.manjaro.org/index.php?do=details&task_id=12

**Comment by Kirek** [comment]
Ahh so it seems is a linux47 problem, nothing wrong with either manjaro-tools or sudo. Just tested it with linux46 and it compiles. Didn't notice the issue in bugs.manjaro.org.

**Comment by udeved** [comment]
So linux47 somehow allocates wrongly memory on i686 it seems.

**Comment by Strit** [comment]
Confirming this is happening when building i686 packages on x86_64 hosts with kernel 4.7.
Manjaro-Tools version 0.13.5-1.
