### ISSUE TITLE
[scripts] fancy reaction if you add wrong switches

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#26]
For example if you use **buildpkg -pv package** like in the wiki you get weird output as -v is not supported anymore. The script should break when some is wrongly entered.

For example some issue with **mkset**:

<pre>[phil@manjaro pacman.d]$ mkset -c
/usr/bin/mkset: option requires an argument -- c
/usr/bin/mkset: option requires an argument -- c
/usr/bin/mkset: line 105: load_sets: command not found
==> Available sets: </pre>

**Comment by manjaro** [comment]
Take a look here: a9f5ac728d8f5eff520fce2c25a2cc4e6494e3fc

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/a3004e0261faf813ab95919382d921597c13e337


Should fix set loading.
I forgot to move the function back to util.sh

**Comment by udeved** [comment]
Re buildpkg
-p parameter expects a package name or set name.
We could do check for wrong args, but this makes the issue more complex, as there are many combinations.
I thought getopts takes care of this?

**Comment by udeved** [comment]
[devtux@manjaro-openrc packages-openrc]$ mkset -h
Usage: mkset [options]
    -c <name>   Create set
    -r <name>   Remove set
    -d <name>   Display set
    -q          Show sets
    -h          This help


[devtux@manjaro-openrc packages-openrc]$ mkset -q
==> Available sets: default
[devtux@manjaro-openrc packages-openrc]$ mkset -c foo
==> Creating [/etc/manjaro-tools/sets/foo.set] ...
  -> Adding consolekit
  -> Adding eudev
  -> Adding eudev-systemdcompat
  -> Adding kde-servicemenus-pkg-tools
  -> Adding kf5-servicemenus-pkg-tools
  -> Adding lib32-eudev
  -> Adding lib32-eudev-systemdcompat
  -> Adding lxqt-lightdm-greeter
  -> Adding manjaro-openrc
  -> Adding manjaro-tools
  -> Adding manjaro-tools-git
  -> Adding manjaro-tools-git-devel
  -> Adding manjaro-tools-iso-profiles
  -> Adding manjaro-tools-livecd
  -> Adding networkmanager-openrc
  -> Adding openrc-aur
  -> Adding openrc-base
  -> Adding openrc-core
  -> Adding openrc-desktop
  -> Adding openrc-devel
  -> Adding openrc-misc
  -> Adding openrc-net
  -> Adding openrc-systemdcompat
  -> Adding openrc-video
  -> Adding polkit-consolekit
  -> Adding sddm-consolekit
  -> Adding sysvinit
  -> Adding upower-pm-utils
[devtux@manjaro-openrc packages-openrc]$ mkset -q
==> Available sets: default|foo

latest commit works I think

**Comment by manjaro** [comment]
I'm talking here about the -v switch you had some day in **buildpkg**. You can find it in the [wiki](https://wiki.manjaro.org/index.php?title=Manjaro-tools#buildpkg).

**Comment by udeved** [comment]
This is an error in the wiki.
The author used v for whatever reason there.
I don't recall that it was ever meant to be used like this.
I certainly never did.

**Comment by manjaro** [comment]
I just say we should get smarter in wrong inputs and break our scripts if so. **buildpkg** needs some more work regarding this. User may come up with weird stuff and wonder why they lockup their chroot mounts.

**Comment by udeved** [comment]
Yes, I was hoping we could address this with bash completion or zsh completion.

**Comment by manjaro** [comment]
Now I get it why you come up with this and I understand now #4 way more better ...

**Comment by aadityabagga** [comment]
When I had written that page buildpkg was named *build-set* and there was a **-v** option for verbose.

I corrected the wiki now.
https://wiki.manjaro.org/index.php?title=Manjaro-tools#buildpkg

**Comment by anexation** [comment]
@ aadityabagga, Are you planning on adding a section for buildiso options for manjaro-tools?

**Comment by aadityabagga** [comment]
Hi Anex, not at the moment, as I am not too familiar with the buildiso options yet.
Thats why I linked the [github](https://github.com/manjaro/manjaro-tools) page at the [beginning](https://wiki.manjaro.org/index.php?title=Manjaro-tools#Introduction).

**Comment by udeved** [comment]
The question is, should buildpkg support split packages.
Ie, do we want to maintain the option to pass makepkg args?

**Comment by manjaro** [comment]
What do you mean by that? If you have a split package in your openrc-base as in your example dbus-openrc it would been build anyway. It would be on the other hand a nice feature to be able to build only dbus-openrc also. Create a poll in our forum for that. Adding a --pkg switch don't seem to me overblown. If you say it is regarding switches and to be to complex then simply add split-packages to mkset and make set creates some like:

<pre>openrc-base
%dbus-openrc
%bla-openrc
%blub-openrc
openrc-extra
%doof-openrc
%roof-openrc</pre>

So all pkgs with prefix % are subpkgs. Maybe that apporach might help you further ...

**Comment by udeved** [comment]
I will make a poll.

A direct --pkg switch is more complicated than passing makepkg args. I experimented with this some time ago.
The feature doesn't hurt, it can be useful to pass makepkg args.

Currently, say I want to build dbus-openrc only, I pass args as in posted example.

**Comment by manjaro** [comment]
Then it is fine with me ...
