### ISSUE TITLE
manjaro-hello

### ISSUE THREAD

**Issue by Ram3zani** [manjaro/manjaro-tools#277]
Hello
I make customize manjaro with manjaro-tools. It is perfect but I have an issue. How can I disable manjaro-hello screen in live mode?

**Comment by philmmanjaro** [comment]
You want to disable or remove it?

**Comment by Ram3zani** [comment]
I want it doesn't show when I boot my customize manjaro.

**Comment by philmmanjaro** [comment]
Well, the package **manjaro-hello** creates a file called `/etc/skel/.config/autostart/manjaro-hello.desktop`. You can add a similar named blank file to the same folder to your **desktop-overlay** in your custom **manjaro-tools profile** to prevent **manjaro-hello** from starting.

**Comment by oberon2007** [comment]
Why not simply removed **manjaro-hello** from **Packages-live**? :smile:
