### ISSUE TITLE
Packages need rebuild

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#28]
After we release manjaro-tools-0.9.5.7, we should rebuild the livecd packages and the iso profiles.
Should I tag those packages 0.9.0-pre1 or something or as 0.8.11-2 ?

**Comment by manjaro** [comment]
Well livecd packages are already with revision 9960b19f2254a2b6540aa4cb4b9a1a47c800e91c in unstable. So there is nothing to be done there. iso-profiles we have no packages yet. Are they even all ready to be used? Most use git anyway and build the images as they go.

**Comment by anexation** [comment]
there is no reason to build the iso profiles yet

**Comment by udeved** [comment]
Well, lets delete the iso-profiles package in unstabke

**Comment by manjaro** [comment]
Actually it doesn't matter if there are any packages yet. But if we do, we should have the iso-profiles in-sync or at least working with the given manjaro-tools snapshot.

**Comment by udeved** [comment]
Agreed.

I didn't realize you updated the livecd packages.

Btw, I think the cli installer package needs a couple of depends.

**Comment by anexation** [comment]
yes, and really anyone that's building with manjaro-tools now anyways is going to clone the latest from git i think anyways.. the only real reason to have this package in our repo's i think is when we are about to release 0.9.0. for the populace to use
