### ISSUE TITLE
buildiso failure conflicting files (calamares)

### ISSUE THREAD

**Issue by anexation** [manjaro/manjaro-tools#29]
any ideas?

manjaro-tools version: r541.7619636-1
```
:: Synchronizing package databases...
 core is up to date
 manjaro-livecd-repo is up to date
 kf5-apps is up to date
 extra is up to date
 community is up to date
 multilib is up to date
resolving dependencies...
looking for conflicting packages...

Packages (5) boost-1.57.0-2  yaml-cpp-0.5.1-1  calamares-0.17.7-1  manjaro-livecd-cli-installer-r42.9960b19-1  manjaro-livecd-systemd-r42.9960b19-1

Total Installed Size:  145.61 MiB

:: Proceed with installation? [Y/n] 
(5/5) checking keys in keyring                                                                                    [####################################################################] 100%
(5/5) checking package integrity                                                                                  [####################################################################] 100%
(5/5) loading package files                                                                                       [####################################################################] 100%
(5/5) checking for file conflicts                                                                                 [####################################################################] 100%
error: failed to commit transaction (conflicting files)
calamares: /opt/buildiso/plasma5/kde5/x86_64/livecd-image/usr/lib64 exists in filesystem
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
==> ERROR: Failed to retrieve one or more packages!
==> ERROR: Please check you Packages-Livecd file! Exiting.
[anex@manjaro kde5]$ 
```

**Comment by anexation** [comment]
I cleared my cache and deleted work directories and reboot and still samething

**Comment by anexation** [comment]
Ok, I built myself the latest git snap shot of calamares and everything started building again.. Something wrong with the package you made philm?
```
git clone https://github.com/calamares/calamares.git --branch manjaro
```

**Comment by anexation** [comment]
Philm,  There is a bug with calamares that prevents install with latest git pull https://github.com/calamares/calamares/commit/2857eeb685c99d85a448c0df1ff5219b7bba4372 . We dont have a proper place to report issue with our version of calamares so since I was already having a related issue im going to put it here.. I would recommend forking calamares to our github account then go into settings and make the manjaro branch the default, and when ever you update calamares just do a 2 second pull request to update our github fork and we can report and deal with issues there.. Here is my failed install error..

p.s. - the CLI installer works fine.. with this git commit version https://github.com/manjaro/manjaro-tools-livecd/commit/9960b19f2254a2b6540aa4cb4b9a1a47c800e91c

https://gist.github.com/anexation/7fb3db5386a25c36ac84


![image](https://cloud.githubusercontent.com/assets/6136025/5703318/b56e6ae4-9a2a-11e4-8164-0c37ca00b183.png)

**Comment by manjaro** [comment]
Calamares issue with conflicting files I've to check manjaro-tools once more as I used it the first time. Second issue is related to your profile, which is not yet supported by manjaro tools. Please adjust **lib/util-lived.sh** to your needs.

current code:
<pre>configure_live_image () {

    if [ -e "$1" ] ; then
	sed -i "s|_root-image_|/bootmnt/${install_dir}/_ARCH_/root-image.sqfs|g" $1

	if [ -e "/bootmnt/${install_dir}/${arch}/xfce-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/xfce-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/gnome-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/gnome-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/cinnamon-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/cinnamon-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/openbox-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/openbox-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/mate-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/mate-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/kde-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/kde-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/lxde-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/lxde-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/lxqt-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/lxqt-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/enlightenment-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/enlightenment-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/pekwm-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/pekwm-image.sqfs|g" $1
	fi
	if [ -e "/bootmnt/${install_dir}/${arch}/custom-image.sqfs" ] ; then
	    sed -i "s|_desktop-image_|/bootmnt/${install_dir}/_ARCH_/custom-image.sqfs|g" $1
	fi
	if [ "${arch}" == "i686" ] ; then
	    sed -i "s|_ARCH_|i686|g" $1
	else
	    sed -i "s|_ARCH_|x86_64|g" $1
	fi
    fi
}</pre>

**Comment by manjaro** [comment]
Have to check if it is somehow related to #26 as regarding in conflicting files ...

**Comment by anexation** [comment]
what isnt support in my profile?

**Comment by anexation** [comment]
heres my iso mounts

@ARCH@/livecd-image.sqfs @ARCH@ / squashfs
@ARCH@/lng-image.sqfs @ARCH@ / squashfs
@ARCH@/pkgs-image.sqfs @ARCH@ / squashfs
@ARCH@/kde-image.sqfs @ARCH@ / squashfs
@ARCH@/root-image.sqfs @ARCH@ / squashfs

**Comment by anexation** [comment]
Just want to emphasize CLI installer is working but not calamares

**Comment by manjaro** [comment]
By default we ship Calamares with this [unpackfs.conf](https://github.com/manjaro/packages-extra/blob/master/calamares/unpackfs.conf). The script is editing it on bootup thru livecd script. Before you start calamares, please check the content. The default conf is just a place-holder. There is never a _root_ image. And installing calamares on a live-session should keep the conf which was modified on bootup. File conflicts are solved by updating unstable branch. There was an issue with **extra-cmake-modules** package which got fixed by upstream.
