### ISSUE TITLE
Displaymanager settings on images

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#34]
Should the Dm be configured on DE image or on livecd image?

I think calamares does this for the install, but what about thus and cli?

**Comment by manjaro** [comment]
It needs to be done in our DE-Image as Calamares, Thus or CLI don't setup any systemd services. They just assume that was already done. That's why I had to resquash my 0.9.0-pre1 several times to find these issues.

**Comment by udeved** [comment]
Ok I close this as I already changed it to be configured on DE image.
