### ISSUE TITLE
[buildiso] add option to overwrite iso files if they exists

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#35]
By default we error out when ISO files exist. Add an option to overwrite them.

**Comment by udeved** [comment]
Ok, I currently have set the -f switch for mkiso statically and it removes iso file before writing.

Should I tie this to some already existing clean arg in buildiso?

**Comment by manjaro** [comment]
Well, I don't know. Do we need to error out or do we overwrite them by default? May add an -o switch for overwrite iso. Else it would make no sense to add it to some existing one. Or do you see any?

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/126731ddacd2c32701dd47dd69f5aa7f56d51b44

Is this sufficient?
If yes, we can close it.

**Comment by udeved** [comment]
Re sense, I don't know, since the -f arg for mkiso basically removes the iso, it doesn't overwrite it, but it eroors out if a file is present. Its why I set it to always remove iso file, as it makes no sense to me to produce an error by default.

Should I set the new switch to true by default?

**Comment by manjaro** [comment]
Ah, I got it now. Only when -c was passed it overwrote the iso files. Sometimes I don't use that switch but keep the name. With -w switch it is fine for me. Will test it later.

**Comment by udeved** [comment]
Not quite, as -c also leaves chroots_dir, so we just have to work out defaults and if we need this new switch.

**Comment by udeved** [comment]
Implemented a -w switch to remove iso file, enabled by default.

I close this for now.
