### ISSUE TITLE
[mkchroot] revisit locale-gen

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#37]
By default we have followed locale.conf
<pre>LANG=en_US.utf8
LC_COLLATE=C</pre>

Somehow we end up with:
<pre>LANG=C</pre>

This is wrong and needs another look. Also it might create lot of issues during live-session bootup.

**Comment by manjaro** [comment]
6108431a6e0cd43f20b158a14c3843de683cbc95 might fix it. Needs testing ...

**Comment by udeved** [comment]
This is only default for buildpkg, ie build_locale=true (-L)

buildiso calls mkchroot without -L

Will take a look later.

**Comment by manjaro** [comment]
I get errors in live-session bootup regarding C locale. I've to check my buildiso work folder later when I'm home.

**Comment by udeved** [comment]
If I output the concerning vars at iso build I get this:

  -> build_locales: false
  -> build_mirror: 


which is correct for buildiso.

Will investigate further, but code wise, no lang.conf or locale is changed or set for buildiso.

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/7ec1ea51cf7d0535c41f699082beb94b2d8e226a

I believe this commit fixes it.
Please test also.

**Comment by manjaro** [comment]
I check it now. As of now no locales get generated. I've to check if some are needed at all.

**Comment by udeved** [comment]
The locale.conf on root-image is now created as expected.

    LANG=en_US.UTF-8
    LC_MESSAGES=C


and locale-gin is set to

    en_US.UTF-8 UTF-8 

and en locales generated.

Looks fine to me. The iso now is set to default english and probably won't default to C locales due to unset loacles.

**Comment by manjaro** [comment]
Well it works. We need to add routine to start locale-gen only after we created root-image and only for that image, else we have it on all images.

**Comment by udeved** [comment]
Urgs, then mkchroot has to check it root-image is in the work_dir path.

**Comment by manjaro** [comment]
Getting closer now 89b0396159de1518a9586d40f7c22276979377c3

**Comment by manjaro** [comment]
finally fixed with 306985356091fa88e0c158feb2194b7fae881a3f

**Comment by udeved** [comment]
I think I can now remove the build_locales bool var from mkchroot, since mkiso basically calls the buildpkg routine
