### ISSUE TITLE
new mounting of aufs images leaves unmounted stuff

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#39]
After a second try on xfce-minimal in this case, which failed first try due to netkit-bsd not in repos, the second run produces this:
~~~
==> Removing [/build/buildiso/xfce-minimal/x86_64] ...
rm: cannot remove '/build/buildiso/xfce-minimal/x86_64/xfce-image': Device or resource busy
rm: cannot remove '/build/buildiso/xfce-minimal/x86_64/root-image': Device or resource busy
~~~

**Comment by udeved** [comment]
Solution would be to add umount before error handling  of mkiso create create call I think.

**Comment by manjaro** [comment]
Well if it breaks it doesn't unmount. So we have to add a check to unmount before handling new mounts.

**Comment by udeved** [comment]
What do we do`unmount before mounting new image, ie calling aufs_remove_image twice with different param, or/and add a umount calls before mkiso call dies?

**Comment by manjaro** [comment]
Whatever works best. Both sound sane ...

**Comment by udeved** [comment]
Another idea is to move the unmounting to the clean chroots function and remove the clean arg so it always cleans, which it does already? We'd just have to make sure clean is always set, since clean runs before any chroot is created.

**Comment by udeved** [comment]
I believe the umount_image_handler fixes this and should not leave mounted images in any case.

Will deliberately do a fail build test to check, and if it works I close it.

**Comment by udeved** [comment]
This commit completes unmounting and there shouldn't be any mounted image left in any case.
Reopen if this somehow does not work in certain cases, it does for me.
