### ISSUE TITLE
[buildiso] set -w switch by default?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#40]
Currently, we need to use -w switch everytime, or we get this mkiso error message:
~~~
==> Making bootable image
==> ERROR: Image /build/manjaro-tools/iso/manjaro-xfce-0.9.0-x86_64.iso already exists.
==> ERROR: Aborting...
~~~

**Comment by manjaro** [comment]
You changed it. I fixed it before to be default. See 7905f9498dfa969f523aa2992abcc23c36d1232c, 69147f4863ea3f001e595b4627bc38c6aa844c62 and a93e44ead0948ff3910fc6819f057150f1378ee8

**Comment by udeved** [comment]
https://github.com/manjaro/manjaro-tools/commit/d55c552049a1f709ec35c456149b058d484fe360
This commit should do.

**Comment by manjaro** [comment]
Now it works 303d8db1d6fdcbf4931542f8830b7b72a8c1bb8d
