### ISSUE TITLE
[systemd/openrc_service_live] Do we really need it?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#41]
I wondered if it makes sense at all to separate services for DE image and live image.
Do we need this specific array to start services only in live session, or can we move them to DE images too?

**Comment by udeved** [comment]
I guess we'd only need changes in cli installer and what serices it installs.
We could use for that the manjaro-rools.conf array instead of statically supplying services in cli installer.

**Comment by manjaro** [comment]
CLI-Installer we depreciate soon or later anyway. Sure we can still develop this software until we do the big switch and only use Calamares.

**Comment by udeved** [comment]
I just wondered if the start_systemd_live array has any use case, or if we can move these services to DE, ie start_systemd array?

**Comment by udeved** [comment]
What I mean, can we go with just one service array per init?

I think, from user perspective, it tends to be confusing having 2 arrays per init.

The more I think, the more I come to conclusion that buildiso should only do live session services, and installer should do the install.

**Comment by udeved** [comment]
@manjaro 

What the approximate time table for deprecating cli-installer?

I am tempted to move all services to livecd image, and let installers configure the actual extracted root and De images.

**Comment by udeved** [comment]
I'd think we need it still.
