### ISSUE TITLE
[buildpkg] archive log files similar to pkgs

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#42]
If you build a lot you will be soon or later cluttered with log files. Would be nice to have them moved to a log archive.

**Comment by udeved** [comment]
Good idea.
I dislike how it handles logs right now.

**Comment by udeved** [comment]
I see one little problem.
How do we handle makepkg.conf settings?

They are currently supported, so if you set LOGDEST, you have them all centrally stored.

**Comment by udeved** [comment]
Or do you mean create log tarballs, eg like logrotate does?

**Comment by udeved** [comment]
So what do we do with log files?

Make archives? And how do we handle makepkg.conf vars?
Is it ok as it is?

**Comment by udeved** [comment]
Ok, I will commit a reworking of the logs, it creates an archive after build and will delete log files.
Should I do a new log cache dir, where pkg log archives get moved?

**Comment by udeved** [comment]
If I understood the request right, this commit should do.
https://github.com/manjaro/manjaro-tools/commit/19234b89e8e36808b4a96a58aaa5d67bd58132c7

Please reopen if required.
