### ISSUE TITLE
[buildiso] generate log and shasum files for each build

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#43]
Devtools have the option to create log files and also display what is going on to a terminal. We can use this code to create automatically log files for each build. After iso image creation we should automatically create shasum files.

**Comment by udeved** [comment]
On a specified arg or by default?

**Comment by manjaro** [comment]
Default would be fine and arg optional if you want to have it to disable it if needed/wanted

**Comment by udeved** [comment]
Can you point me to the code you mentioned to reuse?
The logging stuff would be interesting.

I implemented a checksum creation, its sha256sum.
https://github.com/manjaro/manjaro-tools/commit/85466eb309cf0f601aaef78c12cbe713cf6f561a

We could make it dynamic according to makepkg.conf, ie we could chose what checksum method to use.

**Comment by udeved** [comment]
I close this and open a new issue for the logging.
The checksum works and is implemented, I think logging would be target for later version.

Btw, I think you meant the code in makepkg which does the logging, nothing in devtools I found which logs. ;)
