### ISSUE TITLE
[buildiso] ERROR: Please check your Packages-xfce file! Exiting.

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#44]
<pre>(386/386) installing ttf-droid                     [######################] 100%
Updating font cache... done.
Generating locales...
Generation complete.
  -> Cleaning up what we can
==> ERROR: Please check your Packages-xfce file! Exiting.
</pre>

Why **Packages-xfce** if it is **Packages-Xfce** ?!?

**Comment by udeved** [comment]
I think you got a wrong commit.

I fixed this. If your util-iso contains before the die unmount_image_handler, it is an old version, and you should rebuild pkg.

**Comment by manjaro** [comment]
Yes, got fixed with ffec1d50ee3ca2b3d84c176d1df14040b7ef145c
