### ISSUE TITLE
[buildpkg] create chroot for multilib

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#46]
As of now if we create lib32 packages we have to recreate x86_64 chroot. Else we would have normal gcc and not gcc-multilib. I would rather create a chroot called multilib for that case.

**Comment by udeved** [comment]
This is already possible.
Just specify multilib for arch.

**Comment by manjaro** [comment]
I know that, but it creates a chroot called **x86_64** and not **multilib**. I simply expected to have: **/opt/buildpkg/unstable/multilib/**

**Comment by udeved** [comment]
Ah, ok, so its just naming issue.
Will change it.

**Comment by udeved** [comment]
Should work with this:
https://github.com/manjaro/manjaro-tools/commit/8d8c0299cb1cd88094cd68735bc30c2d5f4cf963

Reopen if required please.
