### ISSUE TITLE
[buildpkg|buildiso] add switch to clean pkg cache

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#47]
As we added pkg cache to both binaries we should also add a switch to clean that cache up. Soon or later you might have a full harddrive cos of caching outdated packages in several places (pacman cache , etc).

**Comment by udeved** [comment]
Hmm, actually the two cache dirs for buildiso are cleaned by default except you use -x and/or -l.

I can do a switch for buildpkg cache.

As for buildtree, its wip, and I welcome suggestions.

**Comment by udeved** [comment]
I close this, I believe we got all clean up cases in cache dir covered, except buildtree.

I added a clean up of pkg cache in buildpkg on -w switch.
