### ISSUE TITLE
[buildpkg] mhwd-gpu --setgl mesa needs to be called in multilib

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#48]
As of now **mhwd-gpu --setgl** gets only called in root chroot. When you try to build any lib32 pkg related on lib32-libgl it will fail. You have to call **manjaro-chroot > mhwd-gpu --setgl mesa** before you can compile such a package in your user chroot.

**Comment by udeved** [comment]
Should work with this:
8d8c029

Reopen if required please.

**Comment by philmmanjaro** [comment]
This is still happening. I just tried to build lib32-gtk3:
<pre>/usr/bin/ld: warning: libEGL.so.1, needed by /usr/lib32/libcairo.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libGL.so.1, needed by /usr/lib32/libcairo.so, not found (try using -rpath or -rpath-link)
</pre>

**Comment by udeved** [comment]
Hmm, so I need to to set gl perhaps in the root chroot before it gets rsycnced as user copy.
Atm, it sets gl in user copy.

**Comment by udeved** [comment]
Oops, I realize, I had already chenged it to set gl in the root before the user copy is created.
I'll try with setting gl in user copy.

**Comment by udeved** [comment]
I know what's wrong, naturally, the chroot pulls only the devel and/or multilib-devel packages.
So mhwd is not installed in chroot, this mhwd-gpu command fails, it is not present.

So how to fix? At mhwd package level?

**Comment by alexandruianu** [comment]
Maybe put some mhwd-gpu scripts directly in the tool, with a variable that can set it on or off to work after the multilib build environment is created?

**Comment by udeved** [comment]
Hmm, I had the impression mhwd-gpr scrip is essential part of mhwd.

The easiest would be really to add mhwd to devel group too, not only base group.
It fails because mhwd is not present in chroot, its in my view a mhwd dependency issue.

**Comment by udeved** [comment]
Forget about the mhwd devel membership.

~~~
( 47/183) installing mhwd-db                                          [#######################################] 100%
( 48/183) installing v86d                                             [#######################################] 100%
( 49/183) installing mhwd                                             [#######################################] 100%
Using default
Default lib32 support: true
libGl and libglx symlinks are invalid!
Falling back to default...
libGl: '/usr/lib/mesa/libGL.so.1.2.0'
libGLESv1: '/usr/lib/mesa/libGLESv1_CM.so.1.1.0'
libGLESv2: '/usr/lib/mesa/libGLESv2.so.2.0.0'
libEGL: '/usr/lib/mesa/libEGL.so.1.0.0'
warning: could not find '/usr/lib/xorg/modules/extensions/libglx.xorg'!
==> use mhwd-gpu to set catalyst as default: 'mhwd-gpu --setgl catalyst'
==> use mhwd-gpu to set mesa as default: 'mhwd-gpu --setgl mesa'
Optional dependencies for mhwd
    lib32-mesa: for 32bit support [pending]
~~~

~~~
(172/183) installing lib32-mesa                                       [#######################################] 100%
Optional dependencies for lib32-mesa
    opengl-man-pages: for the OpenGL API man pages
    lib32-mesa-vdpau: for accelerated video playback
(173/183) installing lib32-cairo                                      [#######################################] 100%
(174/183) installing lib32-libxft                                     [#######################################] 100%
(175/183) installing lib32-pango                                      [#######################################] 100%
(176/183) installing lib32-libxml2                                    [#######################################] 100%
(177/183) installing lib32-libsoup                                    [#######################################] 100%
(178/183) installing lib32-rest                                       [#######################################] 100%
(179/183) installing lib32-libxcomposite                              [#######################################] 100%
(180/183) installing lib32-libxcursor                                 [#######################################] 100%
(181/183) installing lib32-libxinerama                                [#######################################] 100%
(182/183) installing lib32-libxkbcommon                               [#######################################] 100%
(183/183) installing lib32-libxrandr                                  [#######################################] 100%
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (2) gobject-introspection-1.42.0-1  python2-2.7.9-1

Total Installed Size:  79.49 MiB
~~~

The process creates a multilib devel chroot, then it copies with rsyc the root to a user copy.
From there, the PKGBUILD pulls in depends, mhwd is one of the depends.
but, how do we update the gl symlinks, lib32-mesa has not been installed yet, but mhwd has already set the symlinks for x86_64 only.

**Comment by philmmanjaro** [comment]
Hmm, let me check it once again ...

**Comment by philmmanjaro** [comment]
**lib32-mesa-libgl** needs to been installed, as it runs **mhwd-gpu --check** once again.

**Comment by udeved** [comment]
There is no such packages.
I suspect you dropped it in favour of lib32-mesa, which comes from arch.

**Comment by udeved** [comment]
I think thats ugly solution, because it pulls lib32-mesa for every single lib32 packages you want to build.
Better would be to do lib32-mesa ourselves and call mhwd-gpu post_install

**Comment by udeved** [comment]
Its also no good for depends, since the initial chroot already has lib32-mesa installed.

**Comment by philmmanjaro** [comment]
With 571ac87fdf6967d973efe8a97dc438271a431d3b it works now. **mhwd** needs to been installed, though.

**Comment by udeved** [comment]
So why don't add mhwd to devel group?

**Comment by philmmanjaro** [comment]
Arg, this is bull. We have to add lib32-mesa to fix it or modify that package what I don't like to do ... Hmm.

**Comment by udeved** [comment]
Yes, naugty, I think if we want to do it properly without any dirty hacks, we got to maintain lib32-mesa with a modified .install script.

**Comment by philmmanjaro** [comment]
I don't like that ... Hmm.

**Comment by udeved** [comment]
Well, mhwd would need a mechanism to autoupdate if libgl providers are installed.
There is no way we can hook into the process once pacman pulls the depends, and mhwd comes before the lib32.mesa.

**Comment by philmmanjaro** [comment]
Well, seems we have to repack lib32-mesa after all ...

**Comment by udeved** [comment]
I fear yes.

**Comment by philmmanjaro** [comment]
This is fixed with new [lib32-mesa](https://github.com/manjaro/packages-multilib/commit/19650d98ed9220592994e7500c3bc2d6ff26ffcd) package ...

**Comment by udeved** [comment]
Withz the new package, we should not need any mhwd-gpu call in chroot, ie we can likely remove all the workarounds.

**Comment by philmmanjaro** [comment]
Check the code. I already did that ...

**Comment by udeved** [comment]
Great!
I already spotted it. :)
