### ISSUE TITLE
[buildiso] should error out when no profile was found

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#50]
Example:
<pre>==> BUILD QUEUE:
/usr/bin/buildiso: line 82: cd: xfce-minimal: No such file or directory
 --> Profile: [xfce-minimal] ...
ls: cannot access Packages*: No such file or directory
cat: displaymanager: No such file or directory
cat: initsys: No such file or directory
  -> initsys: 
  -> displaymanager: 
  -> pacman_conf: /usr/share/manjaro-tools/pacman-multilib.conf
  -> work_dir: /opt/buildiso/xfce-minimal/x86_64
  -> iso_file: manjaro--0.9.0-dev-x86_64.iso
  -> start_openrc: cronie cupsd metalog dbus consolekit acpid
  -> start_openrc_live: bluetooth NetworkManager
</pre>

**Comment by udeved** [comment]
I was gonna open an issue on that.
I plan to generally implement more checks, such as a valid profile param in buildiso/buildpkg

**Comment by udeved** [comment]
I probably add an identifier file to the iso profiles, as it may not be enough to only check for the shared folder.

**Comment by udeved** [comment]
$ buildiso -p xfce-minimal -q
    ==> ERROR: You are not running buildiso in the manjaro-iso-profiles folder!

fixed with commit https://github.com/manjaro/manjaro-tools/commit/76cb86daf9cfb9f3938d0a642f37e8660549a29b
and commit
https://github.com/manjaro/manjaro-tools/commit/070bbf41fafb4f2a2c235d4655d37ca582d45a55

We can extend the check function if required.
