### ISSUE TITLE
[buildiso] make displaymanager settings more dynamic

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#52]
The reason for this, lightdm autologin doesn't work if I provide a lightdm.conf in profile.

Problem here, I want to use the lxqt greeter, which needs greeter settings set.

the displaymanager file in profile could be expanded with a theme variable or we put it in manjaro-tools.conf. 
Thats a special case for non gtk greeter, as lightdm defaults to gtk greeters.

Apart from that, lightdm needs VT7 on openrc which can be easily done in code.

Is lightdm the only DM which needs such specific stuff to fix autologin issues?

**Comment by manjaro** [comment]
Maybe, I didn't test others yet. We should add those "fixes" as we need them.

**Comment by udeved** [comment]
I will make lightdm.conf set the greeter according to greeter,conf name, so we can avoid a variable for the theme.
I fixed VT for openrc, it should work without lightfm.conf now.

**Comment by udeved** [comment]
We need to set lightdm non gtk greeters in desktop-image, otherwise first start after install will fail due to wrong greeter.
We set it atm only for live session, which is wrong.
