### ISSUE TITLE
[util-iso-calamares] Should lib use manjaro-tools.conf vars?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#53]
Should the library use the manjaro-tools.conf variables to write calamares modules configs?
I had a look at services.conf, wouldn't be a problem to feed calamares services from our variables.

**Comment by philmmanjaro** [comment]
If needed yes. Soon or later we should find a standard and document it. Also we have to fix existing issues before we add new features.

**Comment by udeved** [comment]
It is basically not needed, since it would only apply for systemd services.

As it is now, we write modules configs for openrc disabling systemd stuff calamares calls.

I just wondered, since we basically have all we'd need to feed calamares.

I guess, the to be found standard is behind this issue. :)

**Comment by udeved** [comment]
see here
https://github.com/manjaro/manjaro-tools/commit/1fc449b5c4243a6a7a7d7840a45843e79f8738fb

Its specific for openrc, but we could write systemd serivce.conf with the content of our services array.

**Comment by philmmanjaro** [comment]
Well, either you manage it with manjaro-tools or you do it with a package. It is up to you. Calamares will default to systemd settings on Manjaro for now.

**Comment by udeved** [comment]
You misunderstand, I ask if it makes sense to reuse the manjaro-tools.conf array to also configure systemd services for calamares.
Default is NM and cups, but we could write as many entires as we have in the array. :)

**Comment by udeved** [comment]
Like this commit
https://github.com/manjaro/manjaro-tools/commit/c9d53e586c2296be2f1f2b81177c8f354754205c

**Comment by udeved** [comment]
Appears to be working.

For openrc, the services.conf looks like this:

~~~
services:

 - name: cronie
mandatory: false

 - name: cupsd
mandatory: false

 - name: metalog
mandatory: false

 - name: dbus
mandatory: false

 - name: consolekit
mandatory: false

 - name: acpid
mandatory: false

 - name: connman
mandatory: false
 
- name: "graphical"
mandatory: false
~~~

**Comment by udeved** [comment]
services.conf needs formatting, else calamares crashes.

**Comment by manjaro** [comment]
What do you mean by that?

**Comment by udeved** [comment]
services.conf get now populated with start_systemd/start_openrc array elements.
Ie you can configure calamares serivices via manjaro-tools.conf.
