### ISSUE TITLE
Ideas for abs and manjaro tree merge?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#55]
I think we need a merge strategy for the abs/manjaro git repos.

Ideally, we end up with binary repo names for the merged git trees.

Perhaps create local branches?

**Comment by philmmanjaro** [comment]
Well, we can prefex them with **arch-** so we know these **PKGBUILD**s are synced from Archlinux.

**Comment by udeved** [comment]
Yes, but I somehow had buried deep in my mind the request to merge the two trees?
Atm, I simply call the folder abs, but its no problem to rename it.

**Comment by udeved** [comment]
I think its not easily done to merge the two trees, due to the layout of arch's git repo.
