### ISSUE TITLE
[buildpkg] unable to build pkgs

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#56]
With latest git-version I'm now unable to build pkgs:
<pre>[phil@manjaro extra]$ ls xfdesktop
PKGBUILD   xfdesktop-4.11.8-7.tar.bz2            xfdesktop-4.11.8-8.tar.bz2
PKGBUILD~  xfdesktop-4.11.8-7-x86_64.log.tar.xz  xfdesktop.install
[phil@manjaro extra]$ sudo buildpkg -p xfdesktop
==> Updating chroot for [unstable] (x86_64)...
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
==> Start building []
==> ERROR: This must be run in a directory containing a PKGBUILD.
==> ERROR: Aborting...
</pre>

**Comment by udeved** [comment]
Will fix it.

I changed some checks.

**Comment by udeved** [comment]
Should work now 890f726ca66bf3b8102720b5479678bca25366f0

**Comment by manjaro** [comment]
Yep, works now. Thx for fast fix ;)

**Comment by udeved** [comment]
Btw, is the libgl multilib one working now?

I changed it to call it before the chroot gets rsynced as user copy, so it should be set to mesa.
But I haven't tested it.
