### ISSUE TITLE
add the feature to calculate how long a build takes

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#57]
I always wonder why **manjaro-tools** is some how faster to build my install medias. It would be realy nice to see how long it actually takes to do so. We should add that information to our terminal output.

**Comment by udeved** [comment]
You mean a timer starting when build starts?
like the timers for squashing but for entire process?

**Comment by udeved** [comment]
==> Finished building [lxqt-openrc] in 27.32 minutes

;)

**Comment by manjaro** [comment]
You're so fast! I'm not even able to answer your questions ;) - Yep, some like that.

**Comment by udeved** [comment]
We can break it down more if you want.
like overall time for images and time for squashing

**Comment by manjaro** [comment]
Sure, why not. As more info we have the better ;)

**Comment by udeved** [comment]
I would be interested in benchmarks, just curiosity.
The time I posted was with a clean pacman cache and all packages downloaded.

**Comment by udeved** [comment]
~~~
--> Finished Images in 3.30 minutes
--> Finished compression in 7.07 minutes
==> Finished building [lxqt-openrc] in 10.38 minutes
~~~

with xorg cache and pacman cache :)
