### ISSUE TITLE
[buildiso] dbus in chroot/machine-id again

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#58]
I just open it as a reminder for us to possibly investigate.

Something is still strange with machine-id.

~~~
(172/246) installing libgksu                                          [#######################################] 100%
process 18251: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
usr/sbin/gconfpkg: line 18: 18251 Aborted                 GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source` /usr/bin/gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/${pkgname}.schemas > /dev/null
error: command failed to execute correctly
~~~

Profile is openrc based.

**Comment by Kirek** [comment]
Maybe you need to initialize it manually when mounting the chroot "dbus-uuidgen > /etc/machine-id"

**Comment by udeved** [comment]
its nothing disturbing the build process, and I also don't get some dbus process killed like in some systemd profiles.
Its just curiosity to track it, and probably approach the uuid creation differently in chroot.
Atm, we do uuid at livesession boot up.

**Comment by manjaro** [comment]
So this openrc related only?

**Comment by udeved** [comment]
I dunno, the error in not new.
But this is perhaps reason why systemd profiles need dbus process killed.

its no problem with openrc, because dbus script runs uuid-gen when it starts and no uuid file is present.

**Comment by udeved** [comment]
I did a test.

Profile: lxqt-openrc

without supplying a machne-id file in chroot/var/lib/dbus, no dbus process is killed when building.

If I supply a machine-id on custom image, dbus processes are killed when building.

**Comment by philmmanjaro** [comment]
hmm. really weird issue, so ...

**Comment by udeved** [comment]
I notice that this error is related to gtk/gnome whatever packages.
I won'tget this error with pure qt apps, but as soon as I add gtk apps, the dbus process spawned in chroot needs to be killed.

**Comment by philmmanjaro** [comment]
I noticed it once again during building KDE5 images.

**Comment by udeved** [comment]
You mean the kde5 big profile?
Would stillbe nice to have a list what packages cause this.
No issue with the minimal one.

**Comment by philmmanjaro** [comment]
Well, it happens also with XFCE. You can follow it within my [build-logs](https://gist.github.com/philmmanjaro) ...

**Comment by udeved** [comment]
~~~
(205/279) installing libgksu                            [##############################] 100%
process 28255: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace
usr/sbin/gconfpkg: line 18: 28255 Aborted                 (core dumped) GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source` /usr/bin/gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/${pkgname}.schemas > /dev/null
error: command failed to execute correctly
~~~

That' with systemd build host.

**Comment by udeved** [comment]
Just adding #150 to keep track of the never ending dbus adventure.
