### ISSUE TITLE
v0.9.6.4 ready to be released?

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#59]
As we have nothing added since couple of day it seems v0.9.6.4 seems to be ready for release. We should bundle a current profile snapshot with it. This way our community has a tested basis to do some experiments with it.

**Comment by udeved** [comment]
Agreed.

I can tag 0.9.6.4 today.

As for profiles, should we merge devel in master before doing a snapshot?

**Comment by udeved** [comment]
Btw, should I push it to testing too, or do you want to do this at some point later?

**Comment by philmmanjaro** [comment]
no problem. Testing would have been merged anyway. For the profiles, yes. Master needs to been updated ...

**Comment by philmmanjaro** [comment]
I'll snap it over with current packages in unstable branch. Simply push it to unstable and I'll get notified by boxit anyway ...

**Comment by udeved** [comment]
Both packages are now in unstable.
