### ISSUE TITLE
[livecd] strange behaviour with keymaps

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#60]
Lets fix it.

**Comment by Esclapion** [comment]
If I choose French by F2 at start, the keyboard in the live-cd remains US, so QWERTY instead AZERTY.

**Comment by udeved** [comment]
I believe I fixed this with latest commit.
I forgot to re-enable the xorg layout in the previous commit.

**Comment by Esclapion** [comment]
No change :-( manjaro-tools re-generated just before.

**Comment by udeved** [comment]
http://s7.postimg.org/erq1jh1sr/livecd.png

**Comment by Esclapion** [comment]
Try with France, and look at 20-keyboard.conf ?

I generate another ISO, now.

**Comment by udeved** [comment]
<a href='http://postimage.org/' target='_blank'><img src='http://s3.postimg.org/4sx3naotv/livecd1.png' border='0' alt="livecd1" /></a><br /><a target='_blank' href='http://postimage.org/index.php?lang=german'>kostenlose bilder</a><br /><br />


Italian works.

I dunno franch keyboard layout, so I struggle to login in live session with french. :/

**Comment by Ste74** [comment]
Hello ... i rebuild manjaro-tools and build iso ..

**Comment by udeved** [comment]
ste74, you are italian right?

Make sure you build the devel branch pkgbuild. :)

**Comment by Ste74** [comment]
I rebuild whit this pkgbuild :
https://github.com/manjaro/packages-openrc/tree/master/manjaro-tools-git-devel

**Comment by udeved** [comment]
thats the right one.

**Comment by Ste74** [comment]
i start build

**Comment by Esclapion** [comment]
![sc](https://cloud.githubusercontent.com/assets/3512979/6401365/1f969272-be00-11e4-8795-a30cda9c01ba.png)


Doesn't work for me.

**Comment by udeved** [comment]
@Esclapion 

after a big fight with french keyboard, I had to look it up...

<a href='http://postimage.org/' target='_blank'><img src='http://s27.postimg.org/wxy037w4z/livecd2.png' border='0' alt="livecd2" /></a><br /><a target='_blank' href='http://postimage.org/index.php?lang=german'>bilder uploaden</a><br /><br />

**Comment by Kirek** [comment]
@Esclapion  please test without keyboardctl in your iso...

**Comment by Kirek** [comment]
And in systemd system check 00-keyboard.conf file

**Comment by udeved** [comment]
Yep, on systemd, it should be 00-keyboard.conf.

**Comment by Esclapion** [comment]
Works also not for me in italiano.

@ kirek : how to do that ?

**Comment by udeved** [comment]
@Esclapion 

You do have 0.9.6.5?
Please check with 
    buildiso -q

**Comment by Kirek** [comment]
check the package list and remove it, also thus pulls keyboardctl too, so remove it.

**Comment by Ste74** [comment]
the italian adsl is bad at this time the download of packages is slow  :-(

**Comment by udeved** [comment]
Have an espresso. :)

**Comment by Ste74** [comment]
yeah  ;-) better a chamomile

**Comment by Esclapion** [comment]
keyboardctl is in "Package", a link to ../shared/Packages-Systemd. I commented that out and regenerate an ISO.

**Comment by Esclapion** [comment]
==> manjaro-tools
  -> version: 0.9.6.5

**Comment by udeved** [comment]
Yep, looks good.
I will remove the package from the list in shared.
Wasn't sure about keyboardctl, kirek said something along the lines that it will be deprecated.
openrc doesn't need it anyway.

**Comment by Kirek** [comment]
Yes, should be removed everywhere for 0.9.0, thus too is deprecated.

**Comment by udeved** [comment]
I will do and push updated profiles in unstable.
But I need to merge profile devel branch first.

**Comment by Esclapion** [comment]
Pfffffffffffffffff.. WORKS !!!!

I don't understand exactly why, but the result is good :-)

**Comment by Esclapion** [comment]
I verified italiano, it must work also ;)

**Comment by Ste74** [comment]
i am at the first squashing singh :-(

**Comment by Ste74** [comment]
You work ... finally  is set correctly. Now it remains just another little thing: in livecd asks to download packages of english which in theory is not correct if imposed in Italian language. At max you open another bug

**Comment by udeved** [comment]
No, I can activate it easily.
I commented out to make sure the general settings works.

Can you post from live session

~~~
$ locale 
~~~

Just to verify.

**Comment by Ste74** [comment]
![pearos](https://cloud.githubusercontent.com/assets/11218234/6402656/9e2b3a8a-be09-11e4-93a2-9419ffebd666.png)

**Comment by udeved** [comment]
so your terminal is set properly.

The problem is with pamac or octopi? ie no localized desktop?

**Comment by Ste74** [comment]
no totally localized but manjaro ask to install lang 
![pearos](https://cloud.githubusercontent.com/assets/11218234/6402737/38855ade-be0a-11e4-9d67-a96cffd3224c.png)
packages

**Comment by udeved** [comment]
I dunno if the localization function grabs gimp, but it should install the spell dictionaries on boot.
I'll check that.

**Comment by Ste74** [comment]
Now I go to bed otherwise in the morning is hard ... we update?

**Comment by philmmanjaro** [comment]
Please post output of:
<pre>[phil@manjaro community]$ cat /etc/locale.gen | grep -v '#'
de_DE.UTF-8 UTF-8  
de_DE ISO-8859-1  
en_US.UTF-8 UTF-8  
en_US ISO-8859-1 </pre>

**Comment by Ste74** [comment]
![pearos](https://cloud.githubusercontent.com/assets/11218234/6402941/cfc618a6-be0b-11e4-9f68-1d59d6a9f0e5.png)

**Comment by philmmanjaro** [comment]
As you have en_GB enabled it asks for that language. So no issue.

**Comment by Ste74** [comment]
During the build pkg how to disable en-GB ?

**Comment by udeved** [comment]
I set en_GB as fallback instead of en_US, I can change it easily.

**Comment by philmmanjaro** [comment]
normally we enable de/en_us on creation.

**Comment by Ste74** [comment]
I disagree, however, as a matter of final user in livecd see you ask to update the language that's all ..

**Comment by udeved** [comment]
@philmmanjaro 

Atm, we enable en and the selected language in locale.gen

**Comment by philmmanjaro** [comment]
On bootup or during creation?
**mkiso**
<pre>-L            Use build locale.gen en/de'</pre>

**Comment by udeved** [comment]
on boot up

you are right though, we create the chroots with de/en

**Comment by philmmanjaro** [comment]
As we have en already and if no locale found it always defaults to C an english fallback is on bootup not needed. We should keep de/en on creation, though.

**Comment by udeved** [comment]
I don't plan to change the chroot locale settings.

But I can remove fallback in live session to only setup system according to selection.

**Comment by Kirek** [comment]
the msm daemon only checks enabled locales in "/etc/locale.gen" file

**Comment by Esclapion** [comment]
I go back to the topic. Packages-Systemd is common to all desktop. Can we suppress keyboardctl from there without disturbing the others DEs ? If Yes, who will do it (and may be others things) ?

**Comment by Kirek** [comment]
We don't want keyboardctl in any DE. The only reason we keep it around its because thus expects keyboardctl to be installed to properly configure the keyboard layout, and with thus being deprecated with 0.9.0 this tool is gone. 
Keyboard layouts should be managed by localectl, modifying the config files directly or whatever tool the DE has for this job.

**Comment by Esclapion** [comment]
OK, it's clear, thanks.

**Comment by udeved** [comment]
I removed keyboardctl and thus from git sources. ;)

**Comment by Kirek** [comment]
Nice.

**Comment by Ste74** [comment]
Cool, thank`s.

**Comment by philmmanjaro** [comment]
@Esclapion: this kbctl dependency got introduced with [this](https://github.com/manjaro/thus/commit/e8ca539805b7efea3c8817231e9f62e0e7f0ef71). It was requested by our openrc guys cos **localectl** was systemd-only. As we don't use **thus** anymore, we don't care.
