### ISSUE TITLE
[buildpkg] ERROR: '/root' does not appear to be a Manjaro chroot.

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#62]
After running with -c switch I get this error:
<pre>==> Start building [lib32-gtk3]
==> ERROR: '/root' does not appear to be a Manjaro chroot.
==> Creating clean working copy [phil]...done
==> Making package: lib32-gtk3 3.14.9-1 (Fri Feb 27 22:21:01 CET 2015)
</pre>

**Comment by alexandruianu** [comment]
I always get that warning. Btw phil, I already built that package (just so you don't overwrite the same package in the repos)

**Comment by udeved** [comment]
This was caused by a missing param with now removed set_mesa function

**Comment by philmmanjaro** [comment]
Yep, works now with r845.14f878c-1
