### ISSUE TITLE
[buildiso] Add option for outputing the image to a specific filename/directory

### ISSUE THREAD

**Issue by Sleaker** [manjaro/manjaro-tools#68]
Enhancement request: Add -o (output) option to allow the user to give a specific filename & directory they would like the iso file to be written to.

Additional request: Don't overwrite the file by default, but instead warn with a y/n to overwrite before building and allow automatic overwrite through -f (force) or --force-overwrite.

**Comment by Sleaker** [comment]
@udeved - is this something that would be covered atleast config wise with #67 that I filed? If so this can be closed.

**Comment by udeved** [comment]
Well, I could re-implement the target dir switch for iso storage, But thats no biggie.
I removed it so we don't get crowded with atm too many features we do not urgently need.

**Comment by Sleaker** [comment]
@udeved - That would be awesome, doesn't need to be done right away.

 - Thanks
