### ISSUE TITLE
add man pages for all of the related manjaro-tools commands

### ISSUE THREAD

**Issue by Sleaker** [manjaro/manjaro-tools#69]
Enhancement request: Add in man pages for all of the commands related to manjaro-tools along with a man page for manjaro-tools detailing the different commands that are installed in the package.

Right now a lack of documentation for manjaro-tools means needing to open up a web-browser and go hunting for documentation on the wiki and forums, or lessing through the README on the manjaro-tools git.  It would be much preferred if the manjaro-tools binary came with man docs.

**Comment by udeved** [comment]
@Kirek 

Whats the status of the man branch?

Should it be merged it in devel?

**Comment by Kirek** [comment]
It's only a couple of pages its not finished at all

**Comment by udeved** [comment]
I don't mind mergin it and already installing what we got.
But its your decision if man should be finished first.
