### ISSUE TITLE
[buildiso/conf] Introduce branding

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#70]
We need branding.

**Comment by philmmanjaro** [comment]
I just talked to Kyle from Sonar Linux and he told me that changing username, password and hostname in our config file doesn't do anything. We have to actually check it once more. Also we have to check how to create efiboot loader entries on the fly as they are now hardcoded to Manjaro in our shared/profiles folder.

**Comment by udeved** [comment]
I can't see anything wrong with user, password and host, we also call the configure stuff.
Is this with the latest changes and profile.conf?

As for efi, please elaborate, I didn't really get it.

**Comment by udeved** [comment]
I see, you want the efiboot directory and content on the fly?

**Comment by udeved** [comment]
Var renaming:

manjaro_kernel --> dist_kernel
manjaro_kernel_ver --> dist_kernel_ver
manjaroiso --> dist_iso
manjaro_version --> dist_version

**Comment by udeved** [comment]
Ok, one TODO left.
We need a better approach for generating the mkinitcpio image.
Currently we determine kernel modules version to use -k switch, but I think its better to create a preset with the $dist_kernel we already know with profile.conf.

**Comment by udeved** [comment]
Changes overview:

efi entries are now created on the fly and would in theory support 32bit efi.

isolinux.cfg is also created on the fly, but a isolinux-overlay cfg will overwrite the generated one.

**Comment by philmmanjaro** [comment]
Regarding the hostname, password, username. Sonar linux guys claim that with changing that their iso won't boot up. Did you ever tried to change username, host and password from default?

**Comment by udeved** [comment]
I tried some time ago and it used to work.
Will check again.

**Comment by philmmanjaro** [comment]
Ok, maybe then there was something else. They are both blind, so something might got mis-interpreted by them. We will figure it out when branding is done and tested by us.

**Comment by udeved** [comment]
Phil, could you test a custom hostname for a systemd iso please?

Its the only thing I can think of why a boot process would hang on systemd, meybe.

<a href='http://postimage.org/' target='_blank'><img src='http://s17.postimg.org/wlyg4qjwv/livetest.png' border='0' alt="livetest" /></a><br /><a target='_blank' href='http://postimage.org/index.php?lang=german'>kostenlose bilder</a><br /><br />

**Comment by philmmanjaro** [comment]
Ok, will do when I find time. So, I assume you have this now on the devel branch and latest code tested. Will do the same later on.

**Comment by udeved** [comment]
Yes, latest code.
I will also test the new mkinitcpio preset image generation.
Its ugly to check for kernel version in /usr/lib/modules .... as it is now.

**Comment by philmmanjaro** [comment]
On which part do we do that?

**Comment by udeved** [comment]
I just committed a better solution.
It was left over code from manjaroiso.

**Comment by udeved** [comment]
~~~
==> ISO SETTINGS:
  -> iso_label: TESTFOO090
  -> iso_version: 0.9.0
  -> code_name: Bellatrix
  -> dist_version: 2015.03
  -> dist_iso: fooiso
  -> img_name: foo
  -> install_dir: foobar
  -> compression: xz
  -> checksum_mode: md5
~~~

Appears to be working ;)

**Comment by udeved** [comment]
Ok, last thing is also done, the isolinux message file.

Now, I do think we got the branding stuff to much cluttered.

We got in:
* manjaro-tools.conf

~~
# unset defaults to given value
# iso_version=0.9.0

# unset defaults to given value
# branding="MJRO"

# unset defaults to given value, specify a date here of have it automatically set
# dist_version="$(date +%Y.%m)"

# unset defaults to given value
# install_dir=manjaro

# unset defaults to given value
# dist_iso="manjaroiso"

# unset defaults to value sourced from /etc/lsb-release
# code_name="Bellatrix"

# unset defaults to given value
# img_name=manjaro
~~~

* profile.conf

~~~
# unset defaults to given value
# dist_kernel="linux319"

# unset defaults to given value
# plymouth_theme=manjaro-elegant
~~~

Could we reduce some variables, such as install_dir equals img_name?

**Comment by philmmanjaro** [comment]
yes, simplify it as much as you can.

**Comment by udeved** [comment]
I close this, last commits did it and objective is met now.
