### ISSUE TITLE
create man pages

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#71]
**manjaro-tools** is great. as it is a complex set of tools we should start to write man pages or at least a better documentation. sure it was designed in mind for developers, but if more people are using it and don't have to have a diploma to even get started, it would be much easier to stabilize it. more users, more bug reports, more stability. and yes, we don't have to do it alone. we just give them a start and other can jump in. we simply have to lower the hurdle.

**Comment by udeved** [comment]
I had the early evening a look into md2man converters.

I fiddled around with a tool called ronn.

**Comment by philmmanjaro** [comment]
I'll close this as it is already requested with #69
