### ISSUE TITLE
[buildiso] add profile validation

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#72]
We already have chroot validation for **buildpkg**. We should do the same with our **iso-profiles**. At least we should add checks to validate a profile to be fit for current running **manjaro-tools**.

**Comment by udeved** [comment]
It already checks for a profile.conf in the profile dir and will error out if the condition is not met.
It also checks for 2 Packages files in shared dir before checking profile.

**Comment by udeved** [comment]
Can I close this, or is the current checking not sufficient?

**Comment by philmmanjaro** [comment]
I'll reopen it if needed ...
