### ISSUE TITLE
[buildiso] better error messages

### ISSUE THREAD

**Issue by Sleaker** [manjaro/manjaro-tools#73]
Updated from stable to unstable last night and the profiles are no longer working, this would be more easily dealt with if buildiso actually echoed back what was wrong with the profile instead of a generic 'invalid profile' message.  For instance, if an initsys file is missing the error shouldn't be 'invalid profile'  it should be 'missing initsys'  This goes for any other place the buildiso scripts simply dump out a generic error without actually stating what file or what the problem is.

Treat as an enhancement request.

**Comment by philmmanjaro** [comment]
We released manjaro-tools and a working snapshot to unstable branch. Please keep track on our changes we have done in **devel** branch for what has changed. Most of the profiles are adopted already. But we will work on better error messages.
