### ISSUE TITLE
unable to build from source

### ISSUE THREAD

**Issue by Sleaker** [manjaro/manjaro-tools#74]
can't build manjaro-tools from source as running make throws a recursive variable error on PREFIX and there is no pkgbuild.  README.md is missing build instructions, not sure how you guys are actually building this, help is appreciated, or providing pkgbuild/instructions would be helpful.  Thanks.

**Comment by philmmanjaro** [comment]
I don't get you. We have our **PKGBUILD**s online. Take a look at them:

- [development branch](https://raw.githubusercontent.com/manjaro/packages-openrc/master/manjaro-tools-git-devel/PKGBUILD) (recommend)
- [master branch](https://raw.githubusercontent.com/manjaro/packages-openrc/master/manjaro-tools-git/PKGBUILD)
- [stable release](https://raw.githubusercontent.com/manjaro/packages-openrc/master/manjaro-tools/PKGBUILD)

**Comment by Sleaker** [comment]
@philmmanjaro - hmm. not sure where I'm supposed to know these are available from.  I just git cloned and there isn't anyway to build the source.  manjaroiso had the pkgbuild in the repo before. There's also not really any instruction on how to install from git.
