### ISSUE TITLE
[buildiso] add feature to validate compatibilty of profiles

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#77]
Issue #76 is one of the best examples of broken profiles. We need a feature/routine to validate them:
- check key config files
- check key folders
- check version compatibility

**Comment by udeved** [comment]
Like to enhance ...

~~~
check_run_dir(){
	if [[ ! -f shared/Packages-Systemd ]] || [[ ! -f shared/Packages-Openrc ]];then
		die "${0##*/} is not run in a valid iso-profiles folder!"
	fi
}

I'll do that.
~~~

**Comment by udeved** [comment]
~~~
[manjaro-tools-iso-profiles] $ buildiso -p foo
==> ERROR: Profile sanity check failed.

[manjaro-tools] $ buildiso -p lxqt 
==> ERROR: buildiso is not run in a valid iso-profiles folder!

[manjaro-tools-iso-profiles] $ buildiso -p lxqt-openrc -ix
==> Checking profile [lxqt-openrc]
  -> has_keyfiles: true
  -> has_keydirs: true
 --> Profile sanity check passed.
==> Start building [lxqt-openrc]
~~~

**Comment by udeved** [comment]
The check is for a minimal profile build requirement.

If one file or dir is missing, the entire check fails for files and dirs respectively.

I also added a chroot version check against manjaro-tools version installed.
If chroot version is outdated, chroot will be recreated. It may be a useless check for buildiso, however, it works nicely with buildpkg, and the build won't error out with outdated chroot msg.
