### ISSUE TITLE
[buildiso] on error we should stop and not go on

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#78]
Currently we have the situation that **buildiso** still goes on, even we had an error. It normally should stop working in such a case ...

**Comment by philmmanjaro** [comment]
**Example**:
On **make_image_xorg** step a package can't be downloaded. We should stop here when it happend and not go on with repo-add:
<pre> lib32-mesa-10.4.6-1...     4.2 MiB  3.46M/s 00:01 [######################] 100%
error: failed retrieving file 'lib32-nvidia-utils-346.47-1-x86_64.pkg.tar.xz' from repo.manjaro.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
 lib32-libxv-1.0.10-...     7.2 KiB  2.34M/s 00:00 [######################] 100%
 lib32-libxvmc-1.0.8...    10.3 KiB  3.35M/s 00:00 [######################] 100%
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
  -> Copying xorg pkgs cache ...
==> Adding package '/opt/buildiso/xfce-minimal/x86_64/pkgs-image/opt/livecd/pkgs/bumblebee-3.2.1-5-x86_64.pkg.tar.xz'
  -> Computing checksums...
</pre>
So we have to find a way to catch pacman errors.

**Comment by philmmanjaro** [comment]
**Example**:
During working on #76 we found some other issue. In that case **mkinitcpio** created an error:
<pre>==> Done [pkgs-image]
==> Prepare [manjaro/boot]
  -> mount [boot-image] on [xfce-image]
  -> append [root-image] on [boot-image]
  -> Copying initcpio ...
==> ERROR: '/lib/modules/3.18.9-1-MANJARO' is not a valid kernel module directory
mv: cannot stat '/opt/buildiso/xfce-minimal/x86_64/boot-image/boot/manjaro.img': No such file or directory
  -> unmount boot-image
==> Done [manjaro/boot]
==> Prepare [manjaro/boot/EFI]
  -> Copying efi loaders ...
  -> Writing loader.conf ...
</pre>

Also here **buildiso** should have stopped and not going on to produce **efi-boot** ...

**Comment by philmmanjaro** [comment]
Seems it misses **stderr** and is related to #45.

**Comment by aadityabagga** [comment]
Thx, this was a long standing issue for me :)

**Comment by philmmanjaro** [comment]
https://github.com/manjaro/manjaro-tools-iso-profiles/issues/40 clearly shows that this issue is still not solved.

**Comment by udeved** [comment]
Please test, if I have not managed with these changes to get a still mounted image on error.
If this can be closed, I would do a 0.9.10 fix release.

**Comment by udeved** [comment]
Seems to work after some reports too.

**Comment by philmmanjaro** [comment]
Great news, mate ;)
