### ISSUE TITLE
[buildiso] leftover aufs files not deleted

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools#80]
I had a report of a failed installation with calamares that had /var and /usr in a different filesystem.
Tested it and when /var or /usr are in a different partition it fails to install. Log:

<pre>09:11:18 [0]: Starting job "Crear partició (sistema de fitxers: fat32, mida: 100 MB) a VMware, VMware Virtual S."  /boot/efi
09:11:19 [0]: Starting job "Crear partició (sistema de fitxers: linuxswap, mida: 4096 MB) a VMware, VMware Virtual S." 
09:11:19 [0]: Starting job "Crear partició (sistema de fitxers: ext2, mida: 1000 MB) a VMware, VMware Virtual S."  /boot
09:11:20 [0]: Starting job "Crear partició (sistema de fitxers: ext4, mida: 20000 MB) a VMware, VMware Virtual S."  /
09:11:22 [0]: Starting job "Crear partició (sistema de fitxers: ext4, mida: 20000 MB) a VMware, VMware Virtual S." /usr
09:11:25 [0]: Starting job "Crear partició (sistema de fitxers: ext2, mida: 36720 MB) a VMware, VMware Virtual S." /var
09:11:33 [0]: Starting job "Assignar la informació de la partició" 
09:11:33 [0]: Starting job "Executar l'script mount/main.py" 
mount: unknown filesystem type 'linuxswap'
09:11:34 [0]: Starting job "Executar l'script unpackfs/main.py" 
rsync: link "/tmp/calamares-root-t0ygy56b/var/lib/pacman/local/ttf-dejavu-2.34-2/.wh..wh..opq" => usr/lib/locale/.wh.locale-archive failed: Invalid cross-device link (18)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]
09:14:50 [0]: Installation failed: 
09:14:50 [0]: - message: "Failed to unpack image /bootmnt/manjaro/x86_64/xfce-image.sqfs" 
09:14:50 [0]: - details: "rsync failed with error code 23." </pre>

It's seems its related to some leftover aufs files (.wh)
<pre>[kirek@manjaro-vm ~]$ locate .wh.
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/usr/lib/locale/.wh.locale-archive
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/file-5.22-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/findutils-4.4.2-6/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/gawk-4.1.1-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/gettext-0.19.4-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/grep-2.21-2/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/groff-1.22.3-2/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/gzip-1.6-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/pacman-4.2.1-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/pkg-config-0.28-2/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/sed-4.2.2-3/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/sudo-1.8.12-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/texinfo-5.2-3/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/util-linux-2.25.2-1/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/kde-image/var/lib/pacman/local/which-2.20-7/.wh..wh..opq
/var/lib/manjaro-tools/buildiso/kde5/x86_64/livecd-image/etc/pacman.d/.wh.gnupg
/var/lib/manjaro-tools/buildiso/kde5/x86_64/livecd-image/usr/lib/locale/.wh.locale-archive</pre>

I think this files should be gone, isn't it?

**Comment by Kirek** [comment]
Maybe
find ${path} -type f -name '.wh.*' -exec rm -f {} \;
would be better than 
rm -R ${path}/.wh*
that we use now

**Comment by philmmanjaro** [comment]
This is fixed now.
