### ISSUE TITLE
[buildiso] split caching xorg-pkgs from -c switch

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/manjaro-tools#81]
Currently if we pass **buildiso** xorg-pkg-cache gets deleted, always. Normally it should been kept. You want to delete only your build folders. Add a -x or -g switch for deleting xorg-pkg-cache if the user wants it.

**Comment by Kirek** [comment]
We currently don't detect if xorg-pkg-cache is outdated or not, so I think the current behaviour to delete it by default is the correct one.
-x switch keeps the xorg cache.

**Comment by udeved** [comment]
I agree with Kirek.
the lng and xorg cache are not version aware.
For example, if some xorg package has a new release and you don't clean the cache, you end up having both versions on the iso. This can quickly increase size considerably.
We can use perhaps some version function from utils to do checks, but I am not really keen to implement such thing. Pacman also doesn't do it.

**Comment by philmmanjaro** [comment]
Ok, I got it now.

**Comment by udeved** [comment]
My consideration to implement this would lean to pacman, that should get such feature.
If new package, pacman deletes old one except specified otherwise. Something like this. :)

**Comment by Kirek** [comment]
I thing the problem with the xorg cache is that it downloads all packages every time the xorg cache is created, instead of using the pacman cache...

**Comment by udeved** [comment]
Yep kirek, we basically just change the pacman cache location. pacman treats it just like normal cache dir. I think we could do such checks with the functions in util.sh, but in my view, the better place to address this was pacman itself.
