### ISSUE TITLE
[buildiso] (optimization) Trim Xorg pkg cache before copying to ISO?

### ISSUE THREAD

**Issue by aadityabagga** [manjaro/manjaro-tools#86]
Currently, whichever packages are present in Xorg pkg cache are directly copied over to the ISO.

Can it be made like pacman cache, such that only the latest packages in cache are copied over?

One way to do this in my opinion would be to use ```paccache``` on the copied the repo, so that old versions of packages get removed, like:

~~~~
paccache -rv -k1 -c $XORG_PKG_CACHE
~~~~

Pull request https://github.com/manjaro/manjaro-tools/pull/85

Not completely tested though.

**Comment by philmmanjaro** [comment]
This makes sense. On my end though the xorg-cache gets always deleted. Please test it and post your result like:
<pre>ls [path/to/cache/folder]
[run buildiso]
ls [path/to/cache/folder]</pre>

**Comment by aadityabagga** [comment]
I can confirm something similar happened here too.

I am building and checking at which point the Xorg pkgs get erased. 

Dont know if it happened on making above change or was it broken before..

**Comment by aadityabagga** [comment]
Hmm, this time the packages in xorg cache did not get deleted.

Maybe I had made some mistake the first time..

I used it as follows:

~~~~
sudo geniso -b stable -p xfce-openrc -x
~~~~

geniso used above is a wrapper for buildiso which removes custom repo from pacman.conf while building.

**Comment by philmmanjaro** [comment]
Do you use the **-c** switch in any way?

**Comment by philmmanjaro** [comment]
Anyway, your changes don't harm:
<pre>  -> Copying xorg pkgs cache ...
  -> Trimming xorg pkgs ...
==> no candidate packages found for pruning
</pre>
Please test on your end, if they work for you.

**Comment by aadityabagga** [comment]
I get the same output as above.

Yes, I used -c.

This is the script I used:
https://forum.manjaro.org/index.php?topic=20637.msg198256#msg198256

I will do more testing with this commit and try to find any issues.

**Comment by philmmanjaro** [comment]
Then xorg-cache is kept and it is logical ...

**Comment by aadityabagga** [comment]
I generated some more ISOs and did not face again the issue of Xorg cache being removed.

I will try to do more testing, especially when there is more than one version of a package in xorg cache, before closing this.

**Comment by udeved** [comment]
This one looks good @aadityabagga 
I like it, it removed outdated packages I had in xorg cache.

Remember all, that now cleaning cache must be enabled with -x/-l respectively as opposed to default cleaning previously..

I am tempted to close this issue and reopen if needed. :)
