### ISSUE TITLE
[buildiso] error when using mkinitcpio-noplymouth.conf instead of mkinitcpio.conf

### ISSUE THREAD

**Issue by excalibur1234** [manjaro/manjaro-tools#88]
when i use a link to mkinitcpio-noplymouth.conf instead of mkinitcpio.conf in my ISO profile and query build, i receive the following error:

/usr/lib/manjaro-tools/util-iso.sh: line 498: mkinitcpio.conf: No such file or directory

is this a bug or can i no longer use mkinitcpio-noplymouth.conf ?

**Comment by udeved** [comment]
Did you symlink with a relative path?

~~~
../shared/mkinitcpio-noplymouth.conf
~~~

works for me and lxqt-openrc, which used it from the beginning.

**Comment by excalibur1234** [comment]
thanks. i forgot to rename my symlink.
