### ISSUE TITLE
[initcpio] msio install dir name

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#91]
As far as I can see, we need to sed miso hook to reflect our dynmaic install dir settings, ie in copy_initcpio().
Is this correct? Currently, miso expects a manjaro dir in bootmnt, but it is possible to change the location with manjaro-tools.conf when building image, in my case, its changed to manjaro-openrc.

**Comment by philmmanjaro** [comment]
Well, it only set it to manjaro if **misobasedir** is empty:
<pre>    if [ "x${misobasedir}" = "x" ]; then
        misobasedir="manjaro"
    fi</pre>

... but we define that already with our [kernel cmdline](https://github.com/manjaro/manjaro-tools-iso-profiles/blob/master/shared/isolinux/isolinux.cfg). So this is already covered.

**Comment by udeved** [comment]
Very well, thx, I just wondered and didn't have a close look. :)

**Comment by udeved** [comment]
Btw, I think I had made it so, that the isolinux,cfg/smg get written like isomount, so we don't need to change them in shaed all the time if we change something.
I'll have a look, it definitely works like this for isolinux-overlay.
