### ISSUE TITLE
Release 0.9.9

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#93]
I merged yesterday the nokmiso branch.
I'd like to ask to rebuild your devel pkg and to test.
After some more testing and closing #78, we should release.

I plan to focus in 0.9.8.x on error msg and error handling, logger eventually.

**Comment by philmmanjaro** [comment]
Fine. Will give you feedback as soon as I find time to do it ...

**Comment by philmmanjaro** [comment]
Here my feedback: it works ;)

**Comment by udeved** [comment]
I will merge devel in master today,, and tag 0.9.8

**Comment by udeved** [comment]
any objections to merging the devel brnches in master and release 0.9.9?

**Comment by Kirek** [comment]
No. manjaro-livecd-openrc and systemd needs to be released too.

**Comment by udeved** [comment]
regarding livecd, no commits since I last updated.
Or do you mean to remove the pacman-boot? Doesn't hurt to keep it in in my view.
If we want to rank mirrors, we need something root run to do it.

**Comment by Kirek** [comment]
I removed pacman-boot from there, yesterday.

**Comment by udeved** [comment]
Ah, missed that.
Ok, I will merge branches later.
I just wait for an issue Oberon had with custom local repo, and if it resolves.

**Comment by philmmanjaro** [comment]
I'm also fine with it. #115 should be closed as already mentioned.
