### ISSUE TITLE
Question : buildpkg not support local-repo ?

### ISSUE THREAD

**Issue by Ste74** [manjaro/manjaro-tools#95]
Hello guys , I used to build packages buildpkg script but had some dependencies that were not present in the repo Manjaro so I had to use the classic makepkg -s and add the missing files in my local repo  present in my pacman.conf
The problem comes when I have to build packages in chroot ( 32bit ) as Manjaro-tool and devtools arch are not compatible or not?

**Comment by udeved** [comment]
There is technically no support for a local repo, because you don't need it.

If some dependency is not in the repo, you have to install this dependency in the chroot.
After you installed all depends without cleaning the chroot, you can then build you target package.

**Comment by udeved** [comment]
You could create a buildset for your package, which contains all depends in order and just use the buildset, also using -n switch.

**Comment by Ste74** [comment]
@udeved Can you explain with an example ?
https://github.com/Ste74/Pantheon-PKGBUILD-Repo/tree/master/manjaro-gala-bzr
this pakages need this file 'granite-bzr' 'mutter-manjaro-pantheon' and give me error . I have build with makepkg and 'granite-bzr' 'mutter-manjaro-pantheon' i have compiled a part and copied in my local repo.
Thank artoo

**Comment by udeved** [comment]
I believe you need granite pkgbuild too.

You need to get all depends which are not in the repos.
Forget about local repo. ;)
After you got all depends, you need to order the depends. You can find out with pkgtree.

Then you create a buildset.

    nano -w /etc/manjaro-tools/sets/pkg/pantheon.set

    mutter-manjaro-pantheon
    manjaro-gala-bzr
    pantheon-session-manjaro-bzr

Add the ordered depends and finally you package.

    buildpkg -p pantheon -a i686 -b unstable

**Comment by Ste74** [comment]
Thanks Artoo friendly as always . Upon my packages for 32bit try and if I still have questions post them on our forum  ;-)
