### ISSUE TITLE
[buildpkg] Add local packages to the chroot

### ISSUE THREAD

**Issue by Kirek** [manjaro/manjaro-tools#98]
I want to add the option to add local packages to the chroot when building packages, but before starting I want to ask which way should we do it.

Basically this functions already exist with mkchrootpkg with the -I option, but buildpkg doesn't support it.
With devtools the extra arguments (options after --) that you pass with "unstable-x86_64-build" command are passed to the mkchrootpkg functions, but with buildpkg we pass them to makepkg.

So two options:
- We pass the extra arguments to mkchrootpkg instead of makepkg
- Add an extra option (-I for example) to buildpkg that will be passed to mkchrootpkg

So any thoughts which way we should go?

**Comment by udeved** [comment]
buildpkg can install built package in the chroot with -n switch, which also runs a namcap check.

**Comment by Kirek** [comment]
Yes, its about installing and already built package in the chroot that you only have in locally.

Using -n is useful if you do that in succession, but if you have a clean chroot and the package that you want to install, using the -n route would mean rebuilding a package that you already have.

It's not something I always use but from time to time I need to.

Also the functionality is pretty much there, there only thing left to do is pass the argument to mkchrootpkg.

**Comment by udeved** [comment]
Its ok, we can do a switch wrapper.
I just don't get use case, so its curiosity.

If you have clean chroot, say you want to build lxqt.
You would first have to install liblxqt, after you installed liblxqt, you don't clean chroot, you use the chroot for other packages which need liblxqt and so on.

**Comment by Kirek** [comment]
Well for use cases the other day I needed to compile firefox-kde with the nss package that was in arch testing so I downloaded the nss package and used mkchrootpkg with the -I option to do it.

This is not something I usually need, 99% of times I compile a package everything is already in the repos, or can be built in chain, but the rare case that I need it I prefer to be able to use buildpkg directly rather than mkchrootpkg.

**Comment by udeved** [comment]
I haven't tested this.
Does it work @Kirek ?
Can we close this?

**Comment by Kirek** [comment]
It works.
